(()=>{
  const M=(id,number,accent,kicker,title,question,A,S,C)=>({id,number,accent,kicker,title,question,amateur:{summary:A[0],narrative:A[1],beats:A[2],example:A[3],checkpoint:A[4]},student:{summary:S[0],concepts:S[1],argument:S[2],source:S[3],warning:S[4]},check:{question:C[0],options:C[1],correct:C[2],feedback:C[3],recovery:C[4]}});
  const Q=(q,options,correct,why,module)=>({q,options,correct,why,module});
  window.HOBBES_DATA={
    hotspots:{
      fear:{title:"La paura non è una vergogna",text:"La paura della morte violenta rivela una vulnerabilità condivisa. Proprio perché nessuno è invulnerabile, ciascuno ha una ragione per cercare una pace garantita."},
      nature:{title:"Una condizione, non un’epoca",text:"Lo stato di natura non è necessariamente la preistoria e non coincide con combattimenti continui. È una condizione priva di un potere comune capace di rendere affidabili regole e promesse."},
      leviathan:{title:"Una persona artificiale",text:"Il Leviatano nasce quando molti individui si autorizzano reciprocamente a riconoscere un unico rappresentante. Il sovrano non possiede lo Stato: ne incarna l’unità e deve proteggerne la pace."}
    },
    discovery:[
      {title:"Il deposito senza giudice",prompt:"Una tempesta ha distrutto i raccolti. Tre famiglie trovano lo stesso deposito di grano; nessuna autorità può stabilire quote o punire chi viola un accordo. Che cosa fai?",choices:[
        {label:"Prendo subito quanto posso",title:"La prudenza alimenta il conflitto",text:"Ti protegge nell’immediato, ma rende razionale agli altri anticiparti. Non serve la malvagità: bastano scarsità e assenza di garanzie."},
        {label:"Propongo una divisione equa",title:"La ragione vede la pace",text:"L’accordo conviene a tutti, ma resta fragile finché ciascuno teme che gli altri non lo rispettino."},
        {label:"Aspetto che decidano gli altri",title:"L’attesa non crea una regola",text:"Rinunciare all’iniziativa non garantisce che gli altri facciano lo stesso."}
      ]},
      {title:"La promessa al buio",prompt:"Le famiglie accettano di dividere il grano domani. Durante la notte scopri che una di esse si sta armando. Come interpreti il segnale?",choices:[
        {label:"È certamente malvagia",title:"Conclusione troppo forte",text:"Potrebbe armarsi perché teme esattamente ciò che tu temi di lei."},
        {label:"Mi armo anch’io",title:"La diffidenza diventa reciproca",text:"Una misura difensiva appare offensiva all’altro. Ciascuno può sentirsi razionale."},
        {label:"Mi fido senza condizioni",title:"La fiducia non è garanzia",text:"Può essere generosa, ma non risolve la domanda politica: chi farà valere il patto?"}
      ]},
      {title:"Una regola senza forza",prompt:"Scrivete una regola: nessuno prenderà più della propria quota. Tutti la riconoscono ragionevole. Che cosa manca?",choices:[
        {label:"Nulla: capire il bene basta",title:"La ragione non garantisce l’esecuzione",text:"Le leggi di natura indicano la pace, ma osservarle unilateralmente può essere pericoloso."},
        {label:"Un potere comune",title:"Qui nasce il problema dello Stato",text:"La coercizione rende ragionevole fidarsi perché la violazione non resta senza conseguenze."},
        {label:"Un uomo superiore per natura",title:"Nessun titolo naturale al comando",text:"L’autorità politica deve essere costruita mediante autorizzazione."}
      ]},
      {title:"Il rappresentante comune",prompt:"Tutti autorizzano una persona o assemblea a fissare le quote e punire le violazioni. Che cosa è avvenuto?",choices:[
        {label:"Il sovrano ha firmato con i sudditi",title:"Il patto non funziona così",text:"Gli individui pattuiscono l’uno con l’altro; il sovrano non è una delle parti."},
        {label:"La moltitudine è diventata persona politica",title:"È il passaggio decisivo",text:"L’unità nasce attraverso un rappresentante capace di agire per tutti."},
        {label:"Ogni diritto è scomparso",title:"Resta l’autoconservazione",text:"Non ci si obbliga a volere la propria distruzione: la resistenza a una minaccia diretta resta."}
      ]}
    ],
    modules:[
      M("precedente","01","#c28b43","Il mondo precedente","Natura, fini e gerarchie","Che cosa cambia quando la politica non è più fondata su un fine naturale dell’uomo?",
        ["Hobbes rompe con l’idea che la comunità politica sia il compimento naturale dell’uomo.","Per Aristotele la città compie una socialità naturale e può orientarsi al bene umano. Nel Seicento dinastie e autorità religiose rivendicano fondamenti anteriori al consenso. Hobbes parte invece da individui uguali e privi di un superiore politico naturale: l’ordine deve essere costruito.",["Natura classica letta attraverso fini.","Città come compimento della vita associata.","Gerarchie che pretendono legittimità propria.","Autorità ricostruita da individui uguali."],"Una famiglia può precedere le proprie regole; lo Stato hobbesiano non possiede unità finché non esiste un rappresentante autorizzato.","L’autorità non è trovata nella natura: deve essere prodotta e giustificata."],
        ["La critica allo zoon politikon sostituisce una teleologia del bene con una costruzione convenzionale dell’autorità.",["Zoon politikon","Teleologia","Uguaglianza naturale","Consenso","Artificio"],"Se nessuno possiede un titolo naturale al comando, occorre mostrare perché individui indipendenti abbiano ragione di autorizzare un potere comune.","Leviathan, Introduzione e capp. XIII, XVI–XVII; SEP, Thomas Hobbes §§1–4; Yale PLSC 114, lezioni 12–13.","Non trasformare Aristotele e la scolastica in un blocco uniforme."],
        ["Qual è la rottura decisiva?",["L’autorità è già naturale","L’autorità va costruita fra individui uguali","La politica non richiede giustificazione"],1,"Hobbes parte dall’assenza di un dominatore naturale.","Distingui una comunità naturale da un commonwealth autorizzato."]),
      M("guerra-civile","02","#9b5d45","Fratture biografiche","Una vita dentro la guerra civile","Quanto la paura personale spiega il sistema senza sostituire l’argomento?",
        ["Armada, viaggi, guerre civili ed esilio rendono urgente l’ordine, ma non dimostrano da soli l’assolutismo.","Nato nel 1588 vicino a Malmesbury, Hobbes studiò a Oxford e lavorò per i Cavendish. I viaggi lo introdussero nelle reti scientifiche europee. Nel 1640 lasciò l’Inghilterra per Parigi; lì pubblicò De Cive e preparò Leviathan.",["1588: nascita nell’anno dell’Armada.","Oxford e famiglia Cavendish.","Viaggi nell’Europa scientifica.","1640: esilio a Parigi.","1651: Leviathan e ritorno."],"Un terremoto può spingere un ingegnere a studiare edifici; la validità dei calcoli non dipende dalla sua paura.","La biografia pone il problema; non dimostra la soluzione."],
        ["Guerra civile, patronage aristocratico e reti europee formano il contesto del progetto.",["Armada","Cavendish","Esilio","Guerra civile","Contesto"],"Il conflitto rende visibile il sommo male della morte violenta, ma l’argomento pretende validità generale.","SEP, Thomas Hobbes §1; IEP, Hobbes: Moral and Political Philosophy §§2–3.","La frase sui gemelli ‘io e la paura’ è un’autocaratterizzazione, non una diagnosi totale."],
        ["Come va usata la biografia?",["Come prova conclusiva","Come contesto di un argomento","Come dettaglio inutile"],1,"Contesto e validità dell’argomento restano distinti.","Chiedi se un fatto spiega una domanda o dimostra una tesi."]),
      M("scienza","03","#728492","Metodo","Scomporre e ricostruire","Può la politica diventare una scienza simile alla geometria?",
        ["Hobbes analizza il commonwealth dividendolo nei suoi elementi e poi lo ricostruisce.","Come una macchina viene scomposta negli ingranaggi, lo Stato viene risolto in individui, passioni e movimenti; poi è ricomposto fino al potere comune. La geometria offre un ideale, ma Hobbes usa anche esperienza, introspezione e retorica.",["Risoluzione: dal tutto alle parti.","Composizione: dalle parti al sistema.","Ideale dimostrativo della geometria.","Esperienza e introspezione.","Scienza civile come costruzione umana."],"Per capire un orologio separi gli ingranaggi; per capire lo Stato distingui passioni, patto e rappresentanza.","Il metodo ordina il progetto senza cancellarne le controversie."],
        ["Il metodo risolutivo-compositivo collega corpo, uomo e cittadino senza una riduzione perfettamente lineare.",["Risoluzione","Composizione","Scientia","Geometria","Causa"],"Il commonwealth, prodotto umano, sembra conoscibile attraverso la sua generazione; ma il testo combina definizioni, esperienza e retorica.","De Corpore, parte I; IEP, Hobbes: Methodology §§2–3; SEP, Hobbes’ Philosophy of Science.","Non presentare Leviathan come una catena geometrica senza residui."],
        ["Che significa risolvere il commonwealth?",["Distruggerlo","Analizzarlo e ricostruirne le cause","Ridurre ogni legge a equazione"],1,"La risoluzione è analisi causale.","Pensa al rapporto macchina–ingranaggi–ricostruzione."]),
      M("mente","04","#64888d","Materia e linguaggio","Dal movimento al pensiero","Che cosa resta della mente se tutto ciò che esiste è corpo?",
        ["Sensazioni, immagini e ragionamenti sono spiegati come movimenti corporei e uso di segni.","Gli oggetti agiscono sugli organi; l’immaginazione è una sensazione che si indebolisce. Ragionare significa collegare nomi quasi calcolando conseguenze. Il linguaggio rende possibile la scienza, ma produce assurdità quando le parole non sono definite.",["Movimento esterno e organi.","Senso come apparenza.","Immaginazione come senso che decade.","Nomi e calcolo.","Definizioni e assurdità."],"‘Giustizia’ non è un oggetto visto: il suo significato civile dipende da regole e istituzioni.","Il materialismo non elimina il pensiero: prova a spiegarne la genesi."],
        ["Materialismo, nominalismo ed empirismo convergono in una teoria utile alla scienza civile.",["Corpo","Movimento","Senso","Immaginazione","Nominalismo"],"Se le concezioni derivano dal senso e il ragionamento opera sui nomi, la scienza richiede definizioni controllate.","Leviathan, capp. I–V; SEP, Thomas Hobbes §§2–4; SEP, Hobbes’ Philosophy of Science §1.","Non proiettare sul Seicento le neuroscienze contemporanee."],
        ["Che ruolo ha il linguaggio?",["Solo decorativo","Permette scienza e assurdità","Prova una mente immateriale"],1,"I nomi rendono possibile il ragionamento pubblico e i suoi errori.","Collega definizioni e calcolo delle conseguenze."]),
      M("passioni","05","#a56b52","Antropologia","Appetito, avversione e potere","La politica nasce dall’egoismo o da passioni più complesse?",
        ["Gli esseri umani inseguono ciò che desiderano, evitano ciò che temono e cercano mezzi per il futuro.","Il bene nomina ciò che si desidera, il male ciò che si evita. La felicità non è un riposo finale, ma il successo continuo dei desideri; per questo cerchiamo potere, cioè mezzi presenti per beni futuri. Agiscono anche orgoglio, compassione, curiosità e riconoscimento.",["Appetito e avversione.","Nessun sommo bene universale.","Felicità come movimento.","Potere per beni futuri.","Motivazioni plurali."],"Conservare cibo non soddisfa solo la fame presente: acquista potere contro una fame futura.","Il conflitto non richiede un egoismo elementare."],
        ["La psicologia del conatus sostituisce il fine oggettivo con valutazioni prospettiche e instabili.",["Conatus","Appetito","Avversione","Felicity","Potere"],"Poiché desideri e rischi cambiano, la ricerca di mezzi tende a continuare; l’insicurezza resta anche fra persone cooperative.","Leviathan, capp. VI, X–XI; SEP, Hobbes’s Moral and Political Philosophy §§3–5.","La formula ‘uomo egoista’ è troppo povera."],
        ["Perché la ricerca di potere continua?",["Esiste un bene finale","Servono mezzi per il futuro","Hobbes ammira la guerra"],1,"Il potere è capacità presente per un bene futuro.","Distingui soddisfazione e sicurezza nel tempo."]),
      M("uguaglianza","06","#8f7554","Vulnerabilità","Uguali abbastanza da minacciarsi","Come può l’uguaglianza produrre insicurezza?",
        ["Nessuno è tanto superiore da essere al riparo dall’astuzia o dalla coalizione altrui.","L’uguaglianza non significa capacità identiche. Le differenze non creano un dominatore invulnerabile: il più forte può essere sconfitto nel sonno o da un’alleanza. Speranze simili su beni scarsi producono rivalità.",["Differenze reali.","Vulnerabilità reciproca.","Capacità di nuocere.","Speranze simili.","Nessuna sicurezza solitaria."],"Un singolo utente debole può danneggiare una rete forte: vulnerabilità non significa identica forza.","L’uguaglianza è origine del rischio e base del consenso."],
        ["L’uguaglianza naturale è equivalenza strategica nella minaccia e assenza di autorità naturale.",["Uguaglianza","Vulnerabilità","Scarsità","Aspettativa","Strategia"],"La vulnerabilità fonda sia il conflitto potenziale sia l’interesse comune alla protezione.","Leviathan, cap. XIII; IEP, Hobbes: Methodology §3b; Yale, lezione 13.","Non confonderla con la moderna uguaglianza sociale."],
        ["In che senso siamo uguali?",["Talenti identici","Nessuno è invulnerabile","Stessi diritti civili già dati"],1,"L’uguaglianza decisiva è strategica.","Ricorda il forte vinto da coalizione o astuzia."]),
      M("natura","07","#73515b","Esperimento mentale","La guerra senza battaglie","Perché non combattere oggi non basta a produrre pace?",
        ["Lo stato di natura è insicurezza senza potere comune, non una rissa continua.","Guerra significa anche un tempo in cui è nota la disposizione al conflitto. Competizione, diffidenza e gloria rendono razionale prepararsi. Si può commerciare e cooperare, ma ogni relazione resta revocabile senza un giudice comune.",["Competizione per risorse.","Diffidenza per sicurezza.","Gloria e reputazione.","Disposizione al conflitto.","Assenza di giudice comune."],"Due Stati possono non sparare e vivere in allerta armata: l’assenza di battaglia non è pace sicura.","È una relazione non garantita, non per forza un’epoca primitiva."],
        ["La condizione naturale è una relazione anarchica strutturale visibile in guerra civile e rapporti fra sovrani.",["Stato di natura","Competizione","Diffidenza","Gloria","Anarchia"],"Le intenzioni pacifiche non sono verificabili; la prudenza può produrre anticipazione senza malvagità.","Leviathan, cap. XIII; SEP, Hobbes’s Moral and Political Philosophy §§4–6; Yale, lezione 13.","Non farne cronaca antropologica o combattimento ininterrotto."],
        ["Quando esiste guerra?",["Solo durante la battaglia","Quando permane una minaccia senza garanzia","Ogni volta che si discute"],1,"La guerra è una struttura temporale di insicurezza.","Confronta battaglia e allerta permanente."]),
      M("leggi","08","#7d8f72","Ragione e pace","Diritto e leggi di natura","Come può la ragione indicare la pace senza garantirla?",
        ["Il diritto permette i mezzi di conservazione; la legge naturale comanda di cercare la pace.","Il diritto a tutto mantiene la guerra. La ragione prescrive di cercare pace, deporre reciprocamente parte del diritto e mantenere i patti. Ma osservare unilateralmente queste regole può esporre alla distruzione.",["Diritto come libertà.","Legge come precetto.","Cercare la pace.","Rinuncia reciproca.","Sicurezza dell’adempimento."],"Essere liberi di pagare non equivale all’obbligo di pagare: diritto e legge hanno strutture diverse.","La ragione scopre l’uscita; il potere comune la rende praticabile."],
        ["Jus e lex sono distinti: il primo apre una libertà, la seconda restringe mediante un precetto.",["Jus naturale","Lex naturalis","Pace","Reciprocità","Obbligo"],"La libertà universale rende nessuno sicuro; la ragione prescrive limiti reciproci, efficaci solo con garanzie.","Leviathan, capp. XIV–XV; SEP, Hobbes’s Moral and Political Philosophy §§5–7.","Non trattare diritto e legge come sinonimi."],
        ["Qual è la differenza?",["Il diritto obbliga","Il diritto libera, la legge prescrive","Nessuna"],1,"Hobbes distingue libertà e obbligo.","Associa jus a spazio d’azione e lex a vincolo."]),
      M("patto","09","#b1874b","Autorizzazione","Dalla moltitudine alla persona","Chi pattuisce con chi, e come nasce un’unica voce?",
        ["Gli individui pattuiscono fra loro di autorizzare una persona o assemblea ad agire in loro nome.","Ciascuno dice agli altri: autorizzo questo rappresentante se anche tu lo fai. Il sovrano riceve azioni imputabili agli autori. Non firma un contratto con un popolo già unito: il popolo politico nasce attraverso la rappresentanza.",["Volontà separate.","Patto reciproco.","Rappresentante comune.","Azioni autorizzate.","Persona artificiale."],"Un coro diventa una voce riconoscibile attraverso una regola comune, non perché ogni voce scompaia.","Il popolo viene politicamente costituito dalla rappresentanza."],
        ["Il covenant trasferisce o rinuncia a diritti e produce autorizzazione: il sovrano è attore, i sudditi autori.",["Patto","Autore","Attore","Autorizzazione","Persona"],"L’unità dipende dal rappresentante; poiché il sovrano non è parte del patto reciproco, non lo viola nello stesso senso.","Leviathan, capp. XVI–XVIII; SEP, Hobbes’s Moral and Political Philosophy §7; Yale, lezione 14.","Non dire che ciascuno firma un contratto col re: può essere un’assemblea."],
        ["Chi stipula il patto?",["Sovrano e sudditi","Individui fra loro","Due monarchi"],1,"Il sovrano viene autorizzato dal patto.","Ricostruisci: io autorizzo se anche tu autorizzi."]),
      M("sovranita","10","#5f7188","Il Dio mortale","Potere assoluto e indivisibile","Perché Hobbes teme la divisione del potere?",
        ["Il sovrano deve decidere leggi, giudizi, guerra e pace senza un’autorità concorrente finale.","Se due poteri pretendono l’ultima parola, il conflitto su chi giudica riapre lo stato di natura. La sovranità può essere monarchica, aristocratica o democratica, purché protegga con efficacia. La soluzione resta esposta al problema dell’oppressione.",["Uno, pochi o molti.","Ultima istanza.","Poteri concorrenti.","Legge e forza pubblica.","Protezione come scopo."],"Due arbitri finali incompatibili non raddoppiano la giustizia: dissolvono la partita.","Assoluto significa senza superiore interno, non moralmente perfetto."],
        ["L’assolutismo riguarda non-limitazione giuridica e indivisibilità, non una monarchia necessaria.",["Sovranità","Indivisibilità","Legge civile","Ultima istanza","Protezione"],"Un limite imposto da un superiore rende quest’ultimo sovrano; senza giudice comune diventa oggetto di guerra.","Leviathan, capp. XVIII, XXVI, XXIX; SEP, Hobbes’s Moral and Political Philosophy §§7–9.","Non dedurre che ogni crudeltà sia razionale o protettiva."],
        ["Che rende assoluta la sovranità?",["Eroismo del re","Nessuna autorità interna superiore","Nessuna legge"],1,"Assolutezza indica l’ultima istanza.","Se qualcuno annulla definitivamente il sovrano, chi governa?"]),
      M("liberta","11","#8b6654","Obbedienza e limite","La libertà che non scompare","Che cosa resta al suddito dopo l’autorizzazione?",
        ["La libertà resta dove la legge tace; soprattutto non si rinuncia a difendere la propria vita.","Libertà è assenza di impedimenti esterni e può coesistere con necessità. Nello Stato il suddito è libero negli spazi non regolati. Non può trasferire davvero il diritto di difendersi dalla morte o di volere la propria distruzione.",["Assenza di impedimenti.","Silenzio della legge.","Libertà e necessità.","Autoconservazione.","Obbligo e protezione."],"Promettere di non difendersi da chi vuole ucciderti non cancella l’impulso fondamentale alla vita.","Il potere è vasto, ma non ti rende autore della tua distruzione."],
        ["Le vere libertà dei sudditi derivano da diritti inalienabili e limiti interni all’autorizzazione.",["Libertà negativa","Silenzio della legge","Autoconservazione","Resistenza","Protezione"],"Non autorizzo efficacemente un altro a distruggere lo scopo per cui l’autorità è istituita; l’obbligo cessa quando la protezione finisce.","Leviathan, capp. XIV, XXI; SEP, Hobbes’s Moral and Political Philosophy §§8–10.","Non trasformare la resistenza individuale in un moderno diritto generale alla rivoluzione."],
        ["Quale diritto resta?",["Imporre tasse","Autoconservazione","Essere sovrano"],1,"La resistenza alla propria distruzione è inalienabile.","Collega protezione e limite dell’obbligo."]),
      M("eredita","12","#8073a0","Opere ed eredità","La sfida lasciata ai moderni","Hobbes fonda lo Stato moderno o arma l’autoritarismo?",
        ["Locke e Rousseau trasformano il contratto; liberalismo, positivismo e realismo continuano a discutere Hobbes.","Lo Stato è un artificio umano giustificato dalla protezione, non un fatto sacro. Locke conserva contratto e uguaglianza ma limita il governo; Rousseau trasforma il patto nella volontà generale. Hobbes è letto come assolutista e come teorico di consenso, individuo e rappresentanza.",["Autorità giustificata.","Persona artificiale.","Locke limita il governo.","Rousseau e volontà generale.","Sicurezza e libertà."],"Ogni emergenza riapre la domanda: quali poteri proteggono e quali trasformano protezione in sudditanza?","L’attualità di Hobbes è una domanda critica, non una ricetta."],
        ["L’eredità comprende contratto, rappresentanza, sovranità, positivismo e analisi dell’anarchia.",["Contrattualismo","Rappresentanza","Positivismo","Realismo","Sicurezza"],"Hobbes rende artificiale l’autorità e concentra i poteri; i successori ne contestano necessità, estensione o titolare.","SEP, Thomas Hobbes §6; Yale, lezioni 14–16; IEP, Social Contract Theory.","Locke e Rousseau non sono versioni più buone: cambiano premesse e struttura."],
        ["Che ereditano i successori?",["Una soluzione identica","Il problema di giustificare l’autorità","Il rifiuto del consenso"],1,"Accettano il problema e cambiano la risposta.","Distingui domanda contrattualista e soluzione assolutista."])
    ],
    securityCases:[
      {symbol:"⚖",title:"Una legge senza forza",scene:"Tutti vogliono dividere una risorsa, ma nessuno può punire chi prende tutto.",question:"Qual è la diagnosi hobbesiana?",options:["La morale è inutile","Il patto è fragile senza garanzia","Vince il più forte"],correct:1,explanation:"Le leggi di natura orientano alla pace; il problema è la sicurezza dell’adempimento."},
      {symbol:"⊙",title:"Il vicino si arma",scene:"Non sai se prepari un’aggressione o tema la tua.",question:"Quale meccanismo emerge?",options:["Diffidenza reciproca","Malvagità provata","Giustizia civile"],correct:0,explanation:"L’incertezza rende prudente anticipare senza supporre una natura malvagia."},
      {symbol:"✦",title:"L’offesa minima",scene:"Una parola appare disprezzo e la reputazione influenza la sicurezza futura.",question:"Quale causa agisce?",options:["Competizione","Gloria","Legge di natura"],correct:1,explanation:"La gloria riguarda reputazione e riconoscimento; apparire deboli può aumentare il rischio."},
      {symbol:"▥",title:"L’ordine mortale",scene:"Il sovrano ordina a un suddito di esporsi a morte quasi certa.",question:"Ogni rifiuto scompare?",options:["Sì","No, resta l’autoconservazione","Solo in monarchia"],correct:1,explanation:"Il diritto di resistere alla propria distruzione non può essere efficacemente trasferito."},
      {symbol:"⌁",title:"Due corti supreme",scene:"Due istituzioni emettono decisioni finali incompatibili.",question:"Che cosa temerebbe Hobbes?",options:["Troppa geometria","Dissoluzione dell’ultima istanza","Pace eccessiva"],correct:1,explanation:"Senza un giudice del conflitto, la divisione riapre la guerra dentro lo Stato."},
      {symbol:"◐",title:"Sicurezza e censura",scene:"Il sovrano limita un testo accusato di alimentare la guerra civile.",question:"Come studiare il caso?",options:["Approvare sempre","Ricostruire Hobbes e poi giudicare criticamente","Ignorarlo"],correct:1,explanation:"Comprendere gli ampi poteri dottrinali non significa accettarli: interpretazione e giudizio restano distinti."}
    ],
    covenantSequence:[
      {id:"risk",label:"Vulnerabilità e paura",short:"Il diritto a tutto non dà sicurezza.",application:"Riconosci che la libertà illimitata rende nessuno protetto."},
      {id:"reason",label:"Leggi di natura",short:"La ragione ordina di cercare pace.",application:"Individua reciprocità e dovere di mantenere i patti."},
      {id:"pact",label:"Patto reciproco",short:"Ciascuno pattuisce con ciascuno.",application:"Non collocare il sovrano fra le parti."},
      {id:"authorize",label:"Autorizzazione",short:"Un unico rappresentante.",application:"La moltitudine diventa persona attribuendo azioni all’attore."},
      {id:"power",label:"Potere comune",short:"La forza garantisce i patti.",application:"L’obbedienza diventa prudente perché esiste una conseguenza pubblica."}
    ],
    sources:[
      {kind:"Fonte primaria",title:"Leviatano, capitolo XIII",text:"Uguaglianza vulnerabile, competizione, diffidenza e gloria spiegano la guerra senza postulare malvagità uniforme.",ref:"Leviathan, I.13 · University of Michigan / Columbia University"},
      {kind:"Fonte primaria",title:"Leviatano, capitoli XIV–XV",text:"Diritto e legge di natura vengono distinti; la ragione indica pace, reciprocità e patti.",ref:"Leviathan, I.14–15"},
      {kind:"Fonte primaria",title:"Leviatano, capitoli XVI–XVIII",text:"Persona, autore, attore e autorizzazione costruiscono il commonwealth.",ref:"Leviathan, I.16 e II.17–18"},
      {kind:"Fonte primaria",title:"Leviatano, capitolo XXI",text:"Il silenzio della legge e i diritti non cedibili definiscono la libertà dei sudditi.",ref:"Leviathan, II.21"},
      {kind:"Fonte primaria",title:"De Cive",text:"Libertà, dominio e religione compongono l’esposizione politica precedente al Leviatano.",ref:"De Cive, 1642/1647"},
      {kind:"Fonte primaria",title:"The Elements of Law",text:"La prima formulazione sistematica collega natura umana e corpo politico.",ref:"The Elements of Law, 1640"},
      {kind:"Contesto",title:"Behemoth",text:"La guerra civile inglese viene ricostruita in dialogo, fra storia del conflitto e teoria della sovranità.",ref:"Behemoth, composto negli anni 1660"},
      {kind:"Interpretazione",title:"Non basta dire ‘egoismo’",text:"L’insicurezza può nascere anche fra persone capaci di cooperazione e motivate in modi diversi.",ref:"IEP, Hobbes: Moral and Political Philosophy"},
      {kind:"Interpretazione",title:"Autorizzazione e protezione",text:"Rappresentanza e obbligo restano legati alla capacità effettiva di proteggere.",ref:"SEP, Hobbes’s Moral and Political Philosophy"},
      {kind:"Problema aperto",title:"Sicurezza contro dominio",text:"L’ultima istanza risponde alla guerra civile, ma espone a poteri estesi su legge, dottrina e dissenso.",ref:"Yale PLSC 114, lezione 14"}
    ],
    comics:[
      {year:"1588",icon:"◒",title:"Nato con la paura",text:"Nasce il 5 aprile vicino a Malmesbury, nell’anno dell’Armada.",status:"Data documentata; i ‘gemelli’ Hobbes e paura sono un’autocaratterizzazione"},
      {year:"1603–1608",icon:"▤",title:"Oxford",text:"Studia a Magdalen Hall in un ambiente ancora scolastico.",status:"Documentato"},
      {year:"dal 1608",icon:"⌂",title:"I Cavendish",text:"Diventa precettore e consigliere della famiglia Cavendish.",status:"Documentato"},
      {year:"1630–1636",icon:"⌁",title:"L’Europa scientifica",text:"Viaggi e soggiorni lo avvicinano a Mersenne e ai dibattiti su geometria e movimento.",status:"Documentato; distinguere incontri e influenze"},
      {year:"1640",icon:"⚑",title:"La fuga a Parigi",text:"Lascia l’Inghilterra mentre cresce la crisi politica.",status:"Documentato"},
      {year:"1642–1647",icon:"◇",title:"De Cive",text:"Pubblica prima la parte politica degli Elements of Philosophy.",status:"Documentato"},
      {year:"1651",icon:"▥",title:"Il Leviatano",text:"Pubblica il capolavoro e torna poco dopo in Inghilterra.",status:"Documentato"},
      {year:"1651–1679",icon:"∞",title:"Controversie",text:"Discute con Bramhall e Boyle, scrive Behemoth e difende il sistema.",status:"Documentato"}
    ],
    maps:[
      {id:"motion",title:"Dal movimento all’azione",intro:"La politica parte da una psicologia materialista.",nodes:[{title:"Corpo",text:"Movimento sugli organi."},{title:"Senso",text:"Apparenza nel soggetto."},{title:"Passione",text:"Appetito o avversione."},{title:"Azione",text:"La deliberazione termina."}]},
      {id:"conflict",title:"Dall’uguaglianza alla paura",intro:"La guerra nasce da vulnerabilità e incertezza.",nodes:[{title:"Uguaglianza",text:"Nessuno è invulnerabile."},{title:"Diffidenza",text:"Intenzioni opache."},{title:"Anticipazione",text:"Difesa che sembra attacco."},{title:"Paura",text:"Ricerca di sicurezza."}]},
      {id:"peace",title:"Dal diritto al sovrano",intro:"Libertà naturale e precetto non coincidono.",nodes:[{title:"Diritto",text:"Mezzi di conservazione."},{title:"Leggi",text:"Precetti di pace."},{title:"Patto",text:"Limite reciproco."},{title:"Potere",text:"Garanzia pubblica."}]},
      {id:"person",title:"Dalla moltitudine alla persona",intro:"L’unità è effetto della rappresentanza.",nodes:[{title:"Moltitudine",text:"Volontà separate."},{title:"Autori",text:"Individui che autorizzano."},{title:"Attore",text:"Rappresentante comune."},{title:"Stato",text:"Persona artificiale."}]},
      {id:"limits",title:"Sicurezza e libertà",intro:"L’obbligo resta connesso alla protezione.",nodes:[{title:"Sovranità",text:"Ultima istanza."},{title:"Legge",text:"Obblighi civili."},{title:"Libertà",text:"Silenzio della legge."},{title:"Vita",text:"Resistenza non cedibile."}]}
    ],
    glossary:[
      ["Appetito","Movimento verso ciò che si desidera."],["Autoconservazione","Protezione della vita e limite inalienabile."],["Autore","Chi riconosce come proprie le azioni rappresentate."],["Autorizzazione","Diritto attribuito a chi agisce in nostro nome."],["Avversione","Movimento da ciò che appare dannoso."],["Commonwealth","Persona politica artificiale per pace e difesa."],["Conatus","Inizio minimo del movimento interno."],["Contratto","Trasferimento reciproco di diritti."],["Diffidenza","Incertezza che induce ad anticipare."],["Felicity","Successo continuo dei desideri."],["Gloria","Ricerca di reputazione e riconoscimento."],["Giustizia","Adempimento dei patti garantiti."],["Legge civile","Regola resa vincolante dal sovrano."],["Legge di natura","Precetto razionale di conservazione e pace."],["Libertà","Assenza di impedimenti esterni."],["Materialismo","Tutto ciò che esiste è corpo."],["Meccanicismo","Spiegazione mediante corpo e movimento."],["Patto","Contratto con prestazione differita."],["Persona artificiale","Unità che agisce attraverso rappresentanza."],["Potere","Mezzi presenti per un bene futuro."],["Rappresentante","Attore autorizzato per gli autori."],["Sovrano","Persona o assemblea dell’ultima istanza."],["Sovranità","Potere pubblico assoluto e indivisibile."],["Stato di natura","Condizione senza potere comune."],["Summum bonum","Sommo bene finale rifiutato da Hobbes."],["Timore","Avversione con idea di danno futuro."],["Uguaglianza naturale","Vulnerabilità reciproca."],["Volontà","Ultimo appetito nella deliberazione."]
    ],
    timeline:[
      ["1588","Nasce il 5 aprile vicino a Malmesbury."],["1603 circa","Studia a Magdalen Hall, Oxford."],["1608","Entra al servizio dei Cavendish."],["1629","Pubblica la traduzione di Tucidide."],["1634–1636","Viaggio continentale e reti scientifiche."],["1640","Lascia l’Inghilterra per Parigi."],["1642","Prima edizione latina di De Cive."],["1646","Precettore del futuro Carlo II."],["1651","Leviathan e ritorno in Inghilterra."],["1655","De Corpore."],["1658","De Homine."],["anni 1660","Compone Behemoth."],["1679","Muore il 4 dicembre."],["1682","Behemoth esce postumo."]
    ],
    library:[
      ["The Elements of Law","1640, manoscritto","Prima sintesi di natura umana e corpo politico."],["De Cive","1642/1647","Libertà, dominio e religione."],["Leviathan","1651","Materia, forma e potere del commonwealth."],["De Corpore","1655","Logica, metodo, geometria e corpo."],["De Homine","1658","Ottica e natura umana."],["Behemoth","anni 1660; postumo 1682","Dialogo sulla guerra civile."],["Dialogue of the Common Laws","postumo 1681","Comando sovrano e common law."],["Tucidide","1629","Traduzione della Guerra del Peloponneso."]
    ],
    comparisons:[
      {thinker:"Aristotele",problem:"Perché nasce la città?",move:"Fine naturale e vivere bene.",limit:"Hobbes costruisce un artificio di sicurezza."},
      {thinker:"Machiavelli",problem:"Come reggere il conflitto?",move:"Forza, virtù e ordini.",limit:"Hobbes teorizza sovranità impersonale."},
      {thinker:"Cartesio",problem:"Mente e corpo?",move:"Dualismo delle sostanze.",limit:"Hobbes respinge l’incorporeo."},
      {thinker:"Locke",problem:"Che può il governo?",move:"Potere fiduciario limitato.",limit:"Contesta l’assolutezza."},
      {thinker:"Rousseau",problem:"Libertà nel patto?",move:"Volontà generale.",limit:"Sovranità popolare non rappresentata."},
      {thinker:"Kant",problem:"Fondamento dell’obbligo?",move:"Autonomia morale.",limit:"Non deriva il dovere dalla paura."},
      {thinker:"Realismo",problem:"Stati senza superiore?",move:"Anarchia e auto-aiuto.",limit:"L’uso di Hobbes resta discusso."}
    ],
    quiz:[
      Q("Perché Hobbes non deve dire che tutti sono malvagi?",["Conflitto da vulnerabilità e incertezza","Nega il conflitto","Solo i sovrani sono egoisti"],0,["Esatto: basta la diffidenza.","Il conflitto è centrale.","Non divide così gli uomini."],"natura"),
      Q("In che senso siamo uguali?",["Capacità identiche","Vulnerabilità reciproca","Cittadinanza già uguale"],1,["Ammette differenze.","Esatto: nessuno è invulnerabile.","Nasce nello Stato."],"uguaglianza"),
      Q("Quando esiste guerra?",["Solo in battaglia","Durante una minaccia senza garanzie","In ogni dissenso"],1,["È più ampia.","Esatto: è una condizione.","Il dissenso non basta."],"natura"),
      Q("Diritto e legge di natura?",["Libertà e precetto","Sinonimi","Solo del sovrano"],0,["Esatto.","La distinzione è esplicita.","Il diritto è individuale."],"leggi"),
      Q("Perché le leggi di natura non bastano?",["Sono irrazionali","Manca sicurezza dell’adempimento","Sono segrete"],1,["Indicano pace.","Esatto.","Sono esposte nel testo."],"leggi"),
      Q("Chi istituisce il sovrano?",["Sovrano e popolo","Individui fra loro","Autorità religiosa"],1,["Il popolo unitario nasce dopo.","Esatto.","Non nel modello."],"patto"),
      Q("Che cosa unifica il commonwealth?",["Volontà spontanea","Rappresentante autorizzato","Famiglia superiore"],1,["La moltitudine resta plurale.","Esatto.","Nessun titolo naturale."],"patto"),
      Q("Perché sovranità indivisibile?",["Evitare ultime istanze rivali","Il re è infallibile","Eliminare leggi"],0,["Esatto.","Non è infallibile.","Produce legge."],"sovranita"),
      Q("Quale diritto resta?",["Dominare","Resistere alla morte","Censurare"],1,["Viene regolato.","Esatto.","Non è un diritto generale."],"liberta"),
      Q("Che significa libertà?",["Assenza di cause","Assenza di impedimenti","Partecipazione al governo"],1,["Può coesistere con necessità.","Esatto.","Non dipende dalla forma."],"liberta"),
      Q("Quale descrizione del metodo è precisa?",["Geometria pura","Risoluzione, composizione ed esperienza","Rifiuto della scienza"],1,["Troppo rigida.","Esatto.","Il progetto è scientifico."],"scienza"),
      Q("Che eredità lascia?",["Problema chiuso","Monarchia obbligatoria","Giustificare l’ordine fra uguali"],2,["Resta aperto.","Non è la sola forma.","Esatto."],"eredita")
    ],
    academicSources:[
      {institution:"Stanford University",title:"Thomas Hobbes — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/hobbes/",supports:"Biografia, opere, mente, linguaggio, materialismo, metodo e ricezione."},
      {institution:"Stanford University",title:"Hobbes’s Moral and Political Philosophy",url:"https://plato.stanford.edu/entries/hobbes-moral/",supports:"Stato di natura, leggi, autorizzazione, assolutismo e libertà."},
      {institution:"Stanford University",title:"Hobbes’ Philosophy of Science",url:"https://plato.stanford.edu/entries/hobbes-science/",supports:"Materialismo, movimento, scientia e scienza civile."},
      {institution:"University of Tennessee at Martin",title:"Thomas Hobbes: Moral and Political Philosophy",url:"https://iep.utm.edu/hobmoral/",supports:"Ordine, motivazioni complesse, contratto e obbedienza."},
      {institution:"University of Tennessee at Martin",title:"Thomas Hobbes: Methodology",url:"https://iep.utm.edu/hobmeth/",supports:"Risoluzione, composizione, psicologia e commonwealth."},
      {institution:"Yale University",title:"Political Philosophy — Lecture 12",url:"https://openmedia.yale.edu/projects/iphone/departments/plsc/plsc114/transcript12.html",supports:"Contesto, Stato moderno e assolutismo."},
      {institution:"Yale University",title:"Political Philosophy — Lecture 13",url:"https://openmedia.yale.edu/projects/iphone/departments/plsc/plsc114/transcript13.html",supports:"Stato di natura, uguaglianza e autorità."},
      {institution:"Yale University",title:"Political Philosophy — Lecture 14",url:"https://openmedia.yale.edu/projects/iphone/departments/plsc/plsc114/transcript14.html",supports:"Sovranità, rappresentanza e legge."},
      {institution:"University of Michigan Library",title:"Leviathan — Early English Books Online",url:"https://quod.lib.umich.edu/e/eebo/A43998.0001.001?view=toc",supports:"Edizione digitale seicentesca del testo primario."},
      {institution:"Columbia University Libraries",title:"Electronic Edition of Leviathan",url:"https://www.columbia.edu/acis/ets/CCREAD/hoblevieds.html",supports:"Edizione ricercabile controllata sul 1651."}
    ]
  };
})();
