const MODULES=[...(window.STUDIO_PLATONE||[]),...(window.STUDIO_ARISTOTELE||[])];
const GLOSSARY=window.STUDIO_GLOSSARY||{};
const COMPARISONS=window.STUDIO_COMPARISONS||[];
const moduleGrid=document.querySelector('#moduleGrid'),compareList=document.querySelector('#compareList'),lessonLayer=document.querySelector('#lessonLayer'),lessonBadge=document.querySelector('#lessonBadge'),lessonSub=document.querySelector('#lessonSub'),lessonWho=document.querySelector('#lessonWho'),lessonTitle=document.querySelector('#lessonTitle'),lessonProblem=document.querySelector('#lessonProblem'),lessonText=document.querySelector('#lessonText'),lessonEssentials=document.querySelector('#lessonEssentials'),lessonTerms=document.querySelector('#lessonTerms'),termDefinition=document.querySelector('#termDefinition'),checkQ=document.querySelector('#checkQ'),checkAnswers=document.querySelector('#checkAnswers'),progressBar=document.querySelector('#progressBar'),progressLabel=document.querySelector('#progressLabel'),viewEyebrow=document.querySelector('#viewEyebrow'),viewTitle=document.querySelector('#viewTitle'),viewDesc=document.querySelector('#viewDesc'),viewCount=document.querySelector('#viewCount'),notes=document.querySelector('#notes'),toast=document.querySelector('#toast'),prevLesson=document.querySelector('#prevLesson'),nextLesson=document.querySelector('#nextLesson'),closeLesson=document.querySelector('#closeLesson'),closeLesson2=document.querySelector('#closeLesson2'),completeLesson=document.querySelector('#completeLesson'),copySummary=document.querySelector('#copySummary'),saveNotes=document.querySelector('#saveNotes'),clearNotes=document.querySelector('#clearNotes'),fontBtn=document.querySelector('#fontBtn'),focusBtn=document.querySelector('#focusBtn');
let currentView='platone',currentId=null,currentList=[],timer;
const done=new Set(JSON.parse(localStorage.getItem('pa-studio-done')||'[]'));
notes.value=localStorage.getItem('pa-studio-notes')||'';
function say(t){clearTimeout(timer);toast.textContent=t;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2800)}
function filtered(){return currentView==='tutti'?MODULES:MODULES.filter(m=>m.who===currentView)}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));if(currentView==='confronto'){moduleGrid.hidden=true;compareList.hidden=false;viewEyebrow.textContent='Confronto';viewTitle.textContent='Gli stessi problemi, due architetture';viewDesc.textContent='Le differenze non sono slogan: ogni risposta nasce da una diversa idea di realtà, conoscenza e vita buona.';viewCount.textContent=COMPARISONS.length+' problemi';compareList.innerHTML=COMPARISONS.map(c=>`<article class="compare"><h3>${c[0]}</h3><p class="p"><strong>Platone</strong><br>${c[1]}</p><p class="a"><strong>Aristotele</strong><br>${c[2]}</p></article>`).join('');return}moduleGrid.hidden=false;compareList.hidden=true;const list=filtered();currentList=list.map(m=>m.id);if(currentView==='platone'){viewEyebrow.textContent='Platone';viewTitle.textContent='Il problema della verità e della città';viewDesc.textContent='Sette moduli dalla crisi di Atene alla teoria delle Idee, dall’anima alla politica.'}else if(currentView==='aristotele'){viewEyebrow.textContent='Aristotele';viewTitle.textContent='Il laboratorio del reale';viewDesc.textContent='Dieci moduli dalla logica alla metafisica, dall’etica alla poetica.'}else{viewEyebrow.textContent='Percorso completo';viewTitle.textContent='Diciassette moduli';viewDesc.textContent='I due autori in sequenza, con avanzamento salvato sul dispositivo.'}viewCount.textContent=list.length+' moduli';moduleGrid.innerHTML=list.map(m=>`<button class="module ${m.who} ${done.has(m.id)?'done':''}" data-id="${m.id}"><span class="num">${m.n}</span><span class="tick">✓</span><h3>${m.title}</h3><p>${m.subtitle}</p></button>`).join('');updateProgress()}
function openLesson(id){delete checkAnswers.dataset.done;const m=MODULES.find(x=>x.id===id);if(!m)return;currentId=id;currentList=filtered().map(x=>x.id);if(currentView==='confronto'||!currentList.includes(id))currentList=MODULES.map(x=>x.id);lessonBadge.textContent=m.n;lessonSub.textContent=m.subtitle;lessonWho.textContent=m.who==='platone'?'Platone':'Aristotele';lessonTitle.textContent=m.title;lessonProblem.textContent=m.problem;lessonText.innerHTML=m.body.map(p=>`<p>${p}</p>`).join('');lessonEssentials.innerHTML=m.essentials.map(x=>`<li>${x}</li>`).join('');lessonTerms.innerHTML=m.terms.map(t=>`<button class="termBtn" data-term="${t}">${t}</button>`).join('');termDefinition.classList.remove('show');termDefinition.innerHTML='';checkQ.textContent=m.check.q;checkAnswers.innerHTML=m.check.a.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('');completeLesson.textContent=done.has(id)?'Studiato ✓':'Segna come studiato';const pos=currentList.indexOf(id);prevLesson.disabled=pos<=0;nextLesson.disabled=pos<0||pos>=currentList.length-1;lessonLayer.classList.add('open');lessonLayer.setAttribute('aria-hidden','false');document.body.classList.add('lesson-open');lessonLayer.scrollTop=0;history.replaceState(null,'','#'+id)}
function closeLessonFn(){lessonLayer.classList.remove('open');lessonLayer.setAttribute('aria-hidden','true');document.body.classList.remove('lesson-open');history.replaceState(null,'',location.pathname+location.search)}
function moveLesson(delta){const i=currentList.indexOf(currentId);const next=currentList[i+delta];if(next)openLesson(next)}
function updateProgress(){progressBar.style.width=(done.size/MODULES.length*100)+'%';progressLabel.textContent=done.size+' di '+MODULES.length+' moduli completati'}
moduleGrid.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openLesson(b.dataset.id)});
document.querySelector('.switcher').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;currentView=b.dataset.view;render()});
lessonTerms.addEventListener('click',e=>{const b=e.target.closest('[data-term]');if(!b)return;lessonTerms.querySelectorAll('.termBtn').forEach(x=>x.classList.toggle('active',x===b));const term=b.dataset.term;const m=MODULES.find(x=>x.id===currentId);termDefinition.innerHTML=`<strong>${term}</strong>${GLOSSARY[term]||'Definizione in preparazione.'}<span class="context">In questa lezione: ${m.title}.</span>`;termDefinition.classList.add('show');termDefinition.scrollIntoView({behavior:'smooth',block:'nearest'})});
checkAnswers.addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b||checkAnswers.dataset.done)return;const m=MODULES.find(x=>x.id===currentId);checkAnswers.dataset.done='1';const i=Number(b.dataset.answer);if(i===m.check.correct){b.classList.add('good');say('Risposta corretta.')}else{b.classList.add('bad');checkAnswers.querySelector(`[data-answer="${m.check.correct}"]`).classList.add('good');say('Rileggi il problema iniziale e la spiegazione.')}});
completeLesson.addEventListener('click',()=>{done.add(currentId);localStorage.setItem('pa-studio-done',JSON.stringify([...done]));completeLesson.textContent='Studiato ✓';render();say('Modulo segnato come studiato.')});
copySummary.addEventListener('click',async()=>{const m=MODULES.find(x=>x.id===currentId);const text=m.title+'\n\nProblema: '+m.problem+'\n\n'+m.body.join('\n\n')+'\n\nSaperi irrinunciabili:\n- '+m.essentials.join('\n- ');try{await navigator.clipboard.writeText(text);say('Sunto copiato.')}catch{say('Copia non disponibile in questo browser.')}});
prevLesson.addEventListener('click',()=>moveLesson(-1));nextLesson.addEventListener('click',()=>moveLesson(1));closeLesson.addEventListener('click',closeLessonFn);closeLesson2.addEventListener('click',closeLessonFn);lessonLayer.addEventListener('click',e=>{if(e.target===lessonLayer)closeLessonFn()});addEventListener('keydown',e=>{if(!lessonLayer.classList.contains('open'))return;if(e.key==='Escape')closeLessonFn();if(e.key==='ArrowLeft')moveLesson(-1);if(e.key==='ArrowRight')moveLesson(1)});
saveNotes.addEventListener('click',()=>{localStorage.setItem('pa-studio-notes',notes.value);say('Appunti salvati su questo dispositivo.')});clearNotes.addEventListener('click',()=>{notes.value='';localStorage.removeItem('pa-studio-notes');say('Taccuino cancellato.')});fontBtn.addEventListener('click',()=>{document.body.classList.toggle('large');say(document.body.classList.contains('large')?'Testo ingrandito.':'Dimensione normale.')});focusBtn.addEventListener('click',()=>{document.body.classList.toggle('focus');say(document.body.classList.contains('focus')?'Modalità concentrazione attiva.':'Modalità concentrazione disattivata.')});
render();const hash=location.hash.slice(1);if(MODULES.some(m=>m.id===hash))openLesson(hash);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));
