const FULL=[...(window.FULL_PLATONE||[]),...(window.FULL_ARISTOTELE||[])];
const ORDER=FULL.map(x=>x.id);
const params=new URLSearchParams(location.search);const id=params.get('id')||'p1';const lesson=FULL.find(x=>x.id===id);
const page=document.querySelector('#page'),notFound=document.querySelector('#notFound'),article=document.querySelector('#article'),toc=document.querySelector('#toc'),toast=document.querySelector('#toast');let timer;
function say(t){clearTimeout(timer);toast.textContent=t;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function lessonUrl(target){return `./full-lesson.html?id=${encodeURIComponent(target)}`}
function renderSection(s,i){const sid=`section-${i+1}`;const paragraphs=(s.p||[]).map(p=>`<p>${p}</p>`).join('');const sub=(s.sub||[]).map(x=>`<h3>${x.h}</h3>${x.p.map(p=>`<p>${p}</p>`).join('')}`).join('');const list=s.list?`<ul>${s.list.map(x=>`<li>${x}</li>`).join('')}</ul>`:'';const box=s.box?`<div class="${s.box.type||'focusBox'}"><strong>${s.box.title}</strong><p>${s.box.text}</p></div>`:'';const table=s.table?`<table><thead><tr>${s.table.head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${s.table.rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'';return `<section id="${sid}"><h2>${s.h}</h2>${paragraphs}${sub}${list}${table}${box}</section>`}
if(!lesson){notFound.hidden=false}else{page.hidden=false;document.title=`${lesson.n} · ${lesson.title} · Lezione completa`;document.querySelector('#who').textContent=lesson.who==='platone'?'Platone · Lezione completa':'Aristotele · Lezione completa';document.querySelector('#code').textContent=lesson.n;document.querySelector('#title').textContent=lesson.title;document.querySelector('#subtitle').textContent=lesson.subtitle;document.querySelector('#problem').textContent=lesson.problem;document.querySelector('#topTitle').textContent=`${lesson.n} · ${lesson.title}`;document.querySelector('#topSubtitle').textContent=lesson.who==='platone'?'Platone':'Aristotele';article.innerHTML=lesson.sections.map(renderSection).join('');toc.innerHTML=lesson.sections.map((s,i)=>`<a href="#section-${i+1}">${i+1}. ${s.h}</a>`).join('');document.querySelector('#summary').innerHTML=lesson.summary.map(x=>`<li>${x}</li>`).join('');document.querySelector('#questions').innerHTML=lesson.questions.map(x=>`<li>${x}</li>`).join('');const pos=ORDER.indexOf(id),previous=document.querySelector('#previous'),next=document.querySelector('#next');if(pos>0)previous.href=lessonUrl(ORDER[pos-1]);else previous.hidden=true;if(pos<ORDER.length-1)next.href=lessonUrl(ORDER[pos+1]);else next.hidden=true;document.querySelector('#backLink').href=`./#${id}`;const read=new Set(JSON.parse(localStorage.getItem('pa-studio-full-read')||'[]'));const mark=document.querySelector('#markRead');if(read.has(id)){mark.classList.add('read');mark.textContent='Letta ✓'}mark.addEventListener('click',()=>{read.add(id);localStorage.setItem('pa-studio-full-read',JSON.stringify([...read]));const done=new Set(JSON.parse(localStorage.getItem('pa-studio-done')||'[]'));done.add(id);localStorage.setItem('pa-studio-done',JSON.stringify([...done]));mark.classList.add('read');mark.textContent='Letta ✓';say('Lezione completa segnata come letta.')})}
document.querySelector('#fontBtn').addEventListener('click',()=>{document.body.classList.toggle('large');say(document.body.classList.contains('large')?'Testo ingrandito.':'Dimensione normale.')});document.querySelector('#printBtn').addEventListener('click',()=>window.print());addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('#readingBar').style.width=(max>0?scrollY/max*100:0)+'%'},{passive:true});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));
