const EPISODES=window.FUMETTI_EPISODES||[];
const cards=document.querySelector('#cards'),count=document.querySelector('#count'),search=document.querySelector('#search'),reader=document.querySelector('#reader'),episodeCode=document.querySelector('#episodeCode'),episodeMeta=document.querySelector('#episodeMeta'),episodeTitle=document.querySelector('#episodeTitle'),episodeTagline=document.querySelector('#episodeTagline'),coreIdeas=document.querySelector('#coreIdeas'),historicalNote=document.querySelector('#historicalNote'),studyLink=document.querySelector('#studyLink'),deepLink=document.querySelector('#deepLink'),markRead=document.querySelector('#markRead'),panels=document.querySelector('#panels'),prev=document.querySelector('#prev'),next=document.querySelector('#next'),toast=document.querySelector('#toast'),methodDialog=document.querySelector('#methodDialog');
let author='tutti',query='',currentId=null,currentList=[],timer;
const read=new Set(JSON.parse(localStorage.getItem('pa-fumetti-read')||'[]'));
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function say(text){clearTimeout(timer);toast.textContent=text;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function filtered(){const q=query.trim().toLowerCase();return EPISODES.filter(ep=>(author==='tutti'||ep.author===author)&&(!q||JSON.stringify(ep).toLowerCase().includes(q)))}
function typeLabel(type){return type==='fact'?'Storico':type==='plausible'?'Plausibile':'Simbolico'}
function render(){const list=filtered();currentList=list.map(ep=>ep.id);count.textContent=`${list.length} episodi`;cards.innerHTML=list.map(ep=>`<button class="card ${read.has(ep.id)?'read':''}" data-id="${ep.id}"><span class="tick">✓</span><div class="meta"><span class="code">${esc(ep.code)}</span><span class="author">${esc(ep.author)}</span></div><h3>${esc(ep.title)}</h3><p>${esc(ep.tagline)}</p><div class="trail">${ep.ideas.map(i=>`<span>${esc(i)}</span>`).join('')}</div></button>`).join('')||'<p>Nessun episodio corrisponde alla ricerca.</p>'}
function openEpisode(id){const ep=EPISODES.find(x=>x.id===id);if(!ep)return;currentId=id;currentList=filtered().map(x=>x.id);if(!currentList.includes(id))currentList=EPISODES.map(x=>x.id);episodeCode.textContent=ep.code;episodeMeta.textContent=`${ep.author} · ${ep.panels.length} pannelli`;episodeTitle.textContent=ep.title;episodeTagline.textContent=ep.tagline;coreIdeas.innerHTML=ep.ideas.map(i=>`<li>${esc(i)}</li>`).join('');historicalNote.textContent=ep.historicalNote;studyLink.href=`../studio/#${ep.study}`;deepLink.href=`../approfondisco/#${ep.deep}`;panels.innerHTML=ep.panels.map((p,i)=>`<article class="panel"><div class="panelHeader"><h3>${i+1}. ${esc(p.title)}</h3><span class="panelTag ${esc(p.type)}">${typeLabel(p.type)}</span></div><div class="panelArt"><div class="sceneText">${esc(p.scene)}</div></div><div class="narration">${esc(p.narration)}</div><div class="speech"><strong>${esc(p.speechLabel)}</strong>${esc(p.speech)}</div><div class="thought">${esc(p.thought)}</div></article>`).join('');markRead.textContent=read.has(id)?'Letto ✓':'Segna come letto';const index=currentList.indexOf(id);prev.disabled=index<=0;next.disabled=index<0||index>=currentList.length-1;reader.classList.add('open');reader.setAttribute('aria-hidden','false');document.body.classList.add('reader-open');reader.scrollTop=0;history.replaceState(null,'',`#${id}`)}
function closeReader(){reader.classList.remove('open');reader.setAttribute('aria-hidden','true');document.body.classList.remove('reader-open');history.replaceState(null,'',location.pathname+location.search)}
function move(delta){const index=currentList.indexOf(currentId);const id=currentList[index+delta];if(id)openEpisode(id)}
document.querySelector('.filters').addEventListener('click',event=>{const button=event.target.closest('[data-author]');if(!button)return;author=button.dataset.author;document.querySelectorAll('[data-author]').forEach(x=>x.classList.toggle('active',x===button));render()});
search.addEventListener('input',()=>{query=search.value;render()});cards.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(button)openEpisode(button.dataset.id)});
document.querySelectorAll('[data-overview]').forEach(button=>button.addEventListener('click',()=>openEpisode(button.dataset.overview)));
document.querySelector('#readerClose').addEventListener('click',closeReader);reader.addEventListener('click',event=>{if(event.target===reader)closeReader()});prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));
markRead.addEventListener('click',()=>{if(!currentId)return;read.add(currentId);localStorage.setItem('pa-fumetti-read',JSON.stringify([...read]));markRead.textContent='Letto ✓';render();say('Episodio segnato come letto.')});
document.querySelector('#methodBtn').addEventListener('click',()=>methodDialog.showModal());document.querySelector('#methodClose').addEventListener('click',()=>methodDialog.close());
addEventListener('keydown',event=>{if(!reader.classList.contains('open'))return;if(event.key==='Escape')closeReader();if(event.key==='ArrowLeft')move(-1);if(event.key==='ArrowRight')move(1)});
render();const initial=location.hash.slice(1);if(EPISODES.some(ep=>ep.id===initial))openEpisode(initial);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));