const DOSSIERS=[...(window.APPROFONDISCO_PLATONE||[]),...(window.APPROFONDISCO_ARISTOTELE_1||[]),...(window.APPROFONDISCO_ARISTOTELE_2||[])];
const cards=document.querySelector('#cards'),count=document.querySelector('#count'),search=document.querySelector('#search'),reader=document.querySelector('#reader'),readerCode=document.querySelector('#readerCode'),readerAuthor=document.querySelector('#readerAuthor'),readerTitle=document.querySelector('#readerTitle'),readerQuestion=document.querySelector('#readerQuestion'),passages=document.querySelector('#passages'),context=document.querySelector('#context'),analysis=document.querySelector('#analysis'),readings=document.querySelector('#readings'),cautions=document.querySelector('#cautions'),links=document.querySelector('#links'),studyBack=document.querySelector('#studyBack'),markRead=document.querySelector('#markRead'),prev=document.querySelector('#prev'),next=document.querySelector('#next'),toast=document.querySelector('#toast'),methodDialog=document.querySelector('#methodDialog');
let author='tutti',query='',currentId=null,currentList=[],timer;
const examined=new Set(JSON.parse(localStorage.getItem('pa-approfondisco-examined')||'[]'));
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function say(t){clearTimeout(timer);toast.textContent=t;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2800)}
function filtered(){const q=query.trim().toLowerCase();return DOSSIERS.filter(d=>(author==='tutti'||d.author===author)&&(!q||JSON.stringify(d).toLowerCase().includes(q)))}
function render(){const list=filtered();currentList=list.map(d=>d.id);count.textContent=`${list.length} dossier`;cards.innerHTML=list.map(d=>`<button class="card ${examined.has(d.id)?'read':''}" data-id="${d.id}"><span class="tick">✓</span><div class="meta"><span class="code">${d.study}</span><span class="author">${d.author}</span></div><h3>${esc(d.title)}</h3><p>${esc(d.question)}</p><div class="refs">${d.passages.map(p=>`${esc(p.work)} ${esc(p.ref)}`).join(' · ')}</div></button>`).join('')||'<p>Nessun dossier corrisponde alla ricerca.</p>'}
function openDossier(id){const d=DOSSIERS.find(x=>x.id===id);if(!d)return;currentId=id;currentList=filtered().map(x=>x.id);if(!currentList.includes(id))currentList=DOSSIERS.map(x=>x.id);readerCode.textContent=d.study;readerAuthor.textContent=d.author;readerTitle.textContent=d.title;readerQuestion.textContent=d.question;passages.innerHTML=d.passages.map(p=>`<article class="passage"><div class="passageHead"><h3>${esc(p.work)}</h3><span class="reference">${esc(p.ref)}</span><span class="status">${esc(p.status)}</span></div><p>${esc(p.role)}</p></article>`).join('');context.innerHTML=d.context.map(p=>`<p>${esc(p)}</p>`).join('');analysis.innerHTML=d.analysis.map(p=>`<p>${esc(p)}</p>`).join('');readings.innerHTML=d.readings.map(r=>`<article class="reading"><h3>${esc(r.label)}</h3><p>${esc(r.text)}</p><span class="certainty">${esc(r.certainty)}</span></article>`).join('');cautions.innerHTML=d.cautions.map(c=>`<li>${esc(c)}</li>`).join('');links.innerHTML=d.links.map(l=>`<a href="${l.url}" target="_blank" rel="noopener"><span>${esc(l.label)}</span><small>${esc(l.kind)} ↗</small></a>`).join('');studyBack.href=`../studio/#${d.id}`;markRead.textContent=examined.has(id)?'Esaminato ✓':'Segna come esaminato';const i=currentList.indexOf(id);prev.disabled=i<=0;next.disabled=i<0||i>=currentList.length-1;reader.classList.add('open');reader.setAttribute('aria-hidden','false');document.body.classList.add('reader-open');reader.scrollTop=0;history.replaceState(null,'',`#${id}`)}
function closeReader(){reader.classList.remove('open');reader.setAttribute('aria-hidden','true');document.body.classList.remove('reader-open');history.replaceState(null,'',location.pathname+location.search)}
function move(delta){const i=currentList.indexOf(currentId);const id=currentList[i+delta];if(id)openDossier(id)}
document.querySelector('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-author]');if(!b)return;author=b.dataset.author;document.querySelectorAll('[data-author]').forEach(x=>x.classList.toggle('active',x===b));render()});
search.addEventListener('input',()=>{query=search.value;render()});cards.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openDossier(b.dataset.id)});
document.querySelector('#readerClose').addEventListener('click',closeReader);reader.addEventListener('click',e=>{if(e.target===reader)closeReader()});prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));
markRead.addEventListener('click',()=>{examined.add(currentId);localStorage.setItem('pa-approfondisco-examined',JSON.stringify([...examined]));markRead.textContent='Esaminato ✓';render();say('Dossier segnato come esaminato.')});
document.querySelector('#methodBtn').addEventListener('click',()=>methodDialog.showModal());document.querySelector('#methodClose').addEventListener('click',()=>methodDialog.close());
addEventListener('keydown',e=>{if(!reader.classList.contains('open'))return;if(e.key==='Escape')closeReader();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
render();const initial=location.hash.slice(1);if(DOSSIERS.some(d=>d.id===initial))openDossier(initial);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));