const viewport=document.querySelector('#sceneViewport'),stage=document.querySelector('#sceneStage'),dialog=document.querySelector('#cardDialog'),toast=document.querySelector('#toast');let scale=1,timer;
const cards={
 socrate:{eye:'Personaggio',title:'Socrate',text:'Non fonda una scuola e non lascia scritti. Nella ricostruzione platonica la filosofia diventa esame di sé, ricerca dialogica e cura dell’anima.',links:[['Studio · Atene e Socrate','../../studio/#p1'],['Biblioteca · Apologia','../../biblioteca/#apologia'],['Fumetto · Socrate','../../fumetti/#pl1']]},
 platone:{eye:'Personaggio',title:'Platone ancora giovane',text:'Il futuro fondatore dell’Accademia è qui presentato nel momento della formazione. Non conosciamo la scena concreta del primo incontro: l’immagine è una ricostruzione narrativa dichiarata.',links:[['Linea del tempo · Platone','../../linea-del-tempo/#plato-birth'],['Studio · Platone P1','../../studio/#p1']]},
 sofisti:{eye:'Contesto',title:'I sofisti',text:'Maestri itineranti di parola, educazione e vita pubblica. Non costituiscono un gruppo uniforme: Platone li usa spesso come interlocutori e avversari per chiarire la differenza fra persuasione e conoscenza.',links:[['Dizionario · Sofista','../../dizionario/#sofista'],['Biblioteca · Protagora','../../biblioteca/#protagora'],['Biblioteca · Gorgia','../../biblioteca/#gorgia']]},
 agora:{eye:'Luogo',title:'L’agorà',text:'Il sapere socratico nasce nella città e nella conversazione pubblica, non in un’aula separata. L’agorà indica il rapporto fra filosofia, opinione, legge e responsabilità civica.',links:[['Confronti · Politica','../../confronti/#politica'],['Laboratorio · Regola ingiusta','../../laboratorio/#legge-ingiusta']]},
 pietra:{eye:'Oggetto simbolico',title:'«So di non sapere»',text:'È una formula tradizionale, non una citazione letterale conservata nei testi. Riassume l’atteggiamento socratico: riconoscere il limite del proprio sapere come inizio della ricerca, non come rinuncia alla verità.',links:[['Dizionario · Aporia','../../dizionario/#aporia'],['Studio · Dialogo','../../studio/#p2']]}
};
function say(text){clearTimeout(timer);toast.textContent=text;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2500)}
function setScale(next){scale=Math.max(.45,Math.min(1.25,next));stage.style.transform=`scale(${scale})`;stage.style.marginBottom=`${1024*(scale-1)}px`;stage.style.marginRight=`${1536*(scale-1)}px`}
function fit(){setScale(Math.max(.45,Math.min(viewport.clientWidth/1536,(viewport.clientHeight||900)/1024,1)));viewport.scrollTo({left:0,top:0,behavior:'smooth'})}
function openCard(key){const c=cards[key];if(!c)return;document.querySelector('#cardEye').textContent=c.eye;document.querySelector('#cardTitle').textContent=c.title;document.querySelector('#cardText').textContent=c.text;document.querySelector('#cardLinks').innerHTML=c.links.map(([label,url])=>`<a href="${url}"><span>${label}</span><span>→</span></a>`).join('');dialog.showModal()}
document.querySelectorAll('[data-card]').forEach(b=>b.addEventListener('click',()=>openCard(b.dataset.card)));document.querySelectorAll('.dialogClose').forEach(b=>b.addEventListener('click',()=>dialog.close()));document.querySelector('#zoomIn').addEventListener('click',()=>setScale(scale+.1));document.querySelector('#zoomOut').addEventListener('click',()=>setScale(scale-.1));document.querySelector('#fitScene').addEventListener('click',fit);document.querySelector('#completeStop').addEventListener('click',()=>{const p=JSON.parse(localStorage.getItem('pa-visit-progress')||'{}');p.p1=true;localStorage.setItem('pa-visit-progress',JSON.stringify(p));say('Tappa completata. Il primo tratto del sentiero è illuminato.');setTimeout(()=>location.href='../',1000)});setTimeout(fit,80);addEventListener('resize',()=>{if(innerWidth<760)fit()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../../sw.js',{updateViaCache:'none'}));