"""Chiavi di lettura delle illustrazioni allegoriche, non documenti storici."""
VISUALS = {
 'problema': ('La soglia del conoscere', 'Una figura osserva un paesaggio attraverso un velo luminoso. Il velo allude alle condizioni del conoscere: non separa un universo falso da un secondo universo finalmente vero.'),
 'rappresentazione': ('Il mondo nella finestra', 'Lo sguardo incontra un paesaggio entro una cornice; la clessidra, le partizioni e le increspature dell’acqua richiamano tempo, spazio e causalità. La finestra è una metafora delle forme dell’esperienza, non un ostacolo fisico fra la mente e le cose.'),
 'corpo': ('Lo sforzo e lo specchio', 'Il gesto di sollevare un recipiente è osservabile nello specchio e vissuto come sforzo dal corpo. Sono due accessi al medesimo atto, non due sostanze o due azioni separate.'),
 'volonta': ('Un tendere senza approdo', 'Radici, animale, uomo e mare compongono un movimento che non trova quiete. Il ritmo comune evoca il tendere impersonale della Volontà: non raffigura un fluido fisico né attribuisce coscienza a tutta la natura.'),
 'individuazione': ('La stessa corda, due direzioni', 'Due figure contendono una risorsa tirando una corda che le unisce. La scena rende percepibile il paradosso di una medesima essenza che, nella molteplicità degli individui, entra in conflitto con se stessa.'),
 'desiderio': ('Raggiungere, possedere, ricominciare', 'La figura ricorre in tre momenti: tende verso la coppa, la possiede, poi avverte di nuovo il vuoto. La soddisfazione conclude un bisogno particolare, ma non spegne il desiderare.'),
 'pessimismo': ('Esposti allo stesso mondo', 'Un adulto, un bambino e un animale cercano riparo davanti all’immensità del mare. La loro vulnerabilità non è una colpa e il paesaggio non è un nemico cosciente: la scena interroga un mondo che non garantisce la felicità dei viventi.'),
 'arte': ('Una tregua nell’inquietudine', 'L’ascolto della musica interrompe l’urgenza del fare mentre la folla continua a muoversi. La quiete della contemplazione trasforma temporaneamente l’attenzione, senza arrestare il mondo o promettere una liberazione definitiva.'),
 'compassione': ('Il dolore dell’altro mi riguarda', 'Il mantello condiviso, lo sguardo e la mano offerta trasformano il riconoscimento in aiuto concreto. Due persone restano distinte, ma la sofferenza dell’una non è più estranea all’altra.'),
 'ascesi': ('Aprire le mani', 'Una figura viva e vigile depone i propri oggetti mentre intorno continua la ricerca del possesso. Le mani aperte evocano un diverso rapporto con il volere, non la distruzione del corpo; la semplice rinuncia a beni materiali non esaurisce la tesi filosofica.'),
 'conclusione': ('Un diverso rapporto con il volere', 'La corda allentata introduce tre scene: contemplare, aiutare, raccogliersi nella rinuncia. Sono risposte con funzioni differenti; il movimento del mondo continua e il problema riguarda il nostro rapporto con esso.'),
 'mondo-uomo': ('Senza un centro garantito', 'Il viandante è piccolo davanti al vulcano, al mare e al cielo; la mappa celeste spezzata evoca la crisi della centralità umana. Il problema comune non rende identiche la Natura leopardiana e la Volontà schopenhaueriana.'),
 'motore-uomo': ('Tre modi di interrogare il desiderio', 'Lo sforzo del corpo, la lettera custodita e lo sguardo oltre il limite aprono tre domande: che cosa ci muove, quali valori ci legano, quanto eccede ciò che otteniamo? L’accostamento conserva la differenza fra volere, passioni e desiderio illimitato di piacere.'),
 'sofferenza': ('Il dolore ha più di un volto', 'La tensione verso ciò che manca, l’esposizione alla natura e il vuoto lasciato da una perdita si affiancano. Le scene aiutano a distinguere la struttura del desiderio, la vulnerabilità dei viventi e il dolore dentro la storia e gli affetti.'),
 'salvezza': ('Memoria, distacco, solidarietà', 'Custodire un legame nella memoria, sottrarsi alla pressione del volere e costruire aiuto reciproco sono risposte differenti. Nessuna delle tre scene annulla la finitezza: il confronto chiarisce ciò che ciascuna rende possibile.'),
 'confronto-finale': ('Abitare il mondo, rispondere diversamente', 'Tre spazi evocano memoria e poesia, trasformazione del rapporto con il volere e solidarietà. Il quarto arco rimane incompiuto: il confronto con Verga è un lavoro futuro, da costruire attraverso i testi, non una risposta già stabilita.')
}
