window.BACON_DATA={
  modules:[
    {id:"mondo",number:"01",kicker:"Il mondo precedente",accent:"#b48748",title:"Un sapere da ereditare e discutere",question:"Il sapere antico era davvero soltanto autorità e immobilità?",amateur:{summary:"Bacone entra in un mondo intellettuale ancora segnato da Aristotele e dalla Scolastica, ma non in un deserto di osservazioni.",narrative:"Nelle università europee la filosofia naturale era organizzata attraverso testi, commenti, dispute e dimostrazioni. Aristotele aveva attribuito grande importanza all’esperienza, e il Medioevo conobbe pratiche empiriche, medicina, astronomia e studi della natura. Il bersaglio di Bacone non è dunque una caricatura di uomini che rifiutano di guardare il mondo: è un modo di ordinare il sapere che, secondo lui, parte troppo presto da principi generali e usa l’esperienza soprattutto per confermarli. Il problema non è possedere una tradizione, ma lasciarle decidere in anticipo che cosa la natura può dire.",beats:["Aristotele non è estraneo all’esperienza.","La Scolastica è una tradizione plurale, non un blocco immobile.","Bacone contesta il primato della disputa e dei principi già stabiliti.","La frattura riguarda il modo e lo scopo della ricerca."],example:"Se un manuale afferma che tutti i metalli reagiscono allo stesso modo, posso cercare soltanto esempi favorevoli oppure costruire prove capaci di smentire quella generalizzazione.",checkpoint:"Bacone non elimina il passato: vuole impedire che il passato stabilisca in anticipo il risultato dell’indagine."},student:{summary:"La polemica baconiana si dirige contro usi della logica sillogistica e contro sistemi che anticipano gli assiomi, ma la storia dell’empirismo ha radici antiche e medievali.",concepts:["Organon aristotelico","Sillogismo e scoperta","Filosofia naturale","Autorità e tradizione","Empirismo antico e medievale"],argument:"Un sillogismo può trasmettere correttamente una conclusione già contenuta nelle premesse; non garantisce, però, che le premesse siano state ricavate da una storia naturale sufficientemente ampia. Per Bacone, il difetto è genetico: si costruiscono sistemi coerenti sopra nozioni ottenute in modo frettoloso.",source:"Novum Organum, I, aforismi 11–24; per evitare la caricatura del Medioevo, Stanford Encyclopedia of Philosophy, Ancient and Medieval Empiricism.",warning:"Non dire che prima di Bacone nessuno osservava la natura o che Aristotele ignorava l’esperienza."}},
    {id:"frattura",number:"02",kicker:"La prima modernità",accent:"#7fa6a9",title:"Un mondo più grande dei libri",question:"Che cosa accade quando nuove esperienze eccedono le vecchie mappe?",amateur:{summary:"Navigazioni, stampa, strumenti e arti meccaniche rendono visibile una distanza crescente fra sapere ricevuto e mondo incontrato.",narrative:"Tra Cinquecento e Seicento l’Europa vede dilatarsi gli spazi geografici, circolare più rapidamente i testi e acquistare prestigio pratiche capaci di produrre effetti: navigazione, metallurgia, artigianato, medicina, costruzione di strumenti. Bacone legge questi mutamenti come un segnale. Gli uomini hanno ampliato il mondo attraverso invenzioni e cooperazione, mentre la filosofia naturale, a suo giudizio, ha prodotto soprattutto dispute. La celebre immagine delle colonne d’Ercole, posta sul frontespizio della Grande Instaurazione, invita a oltrepassare i confini del sapere ricevuto con una rotta regolata, non con avventure casuali.",beats:["Le scoperte mettono alla prova le mappe ereditate.","La stampa accelera la circolazione delle conoscenze.","Le arti meccaniche mostrano un sapere capace di effetti.","Servono strumenti intellettuali paragonabili alla bussola."],example:"La bussola non sostituisce il marinaio, ma rende possibile una navigazione che l’intuito individuale non saprebbe mantenere.",checkpoint:"La modernità baconiana nasce dall’incontro fra espansione dell’esperienza e necessità di disciplinarla."},student:{summary:"Il programma baconiano traduce l’esperienza politica, giuridica e tecnica in una riforma coordinata del sapere.",concepts:["Arti meccaniche","Storia naturale","Strumenti","Collaborazione","Progresso"],argument:"Il valore epistemico degli strumenti non consiste soltanto nel potenziare i sensi: essi organizzano l’esperienza e rendono confrontabili operazioni che altrimenti rimarrebbero episodi isolati.",source:"Instauratio Magna, Prefazione; Stanford Encyclopedia of Philosophy, sezioni 1 e 4.",warning:"Non trasformare il contesto in una causa automatica: le innovazioni rendono possibile il progetto di Bacone, ma non lo producono da sole."}},
    {id:"vita",number:"03",kicker:"Vita e opere",accent:"#c17a62",title:"Ambizione pubblica, caduta privata",question:"La ricerca del sapere e la ricerca del potere seguono la stessa traiettoria?",amateur:{summary:"Avvocato, parlamentare, consigliere e cancelliere, Bacone concepisce la riforma del sapere mentre attraversa il centro della politica inglese.",narrative:"Francis Bacon nasce a Londra nel 1561, studia a Cambridge e si forma nel diritto. Entra giovanissimo in Parlamento e costruisce una lunga carriera al servizio della corona, fino a diventare Lord Cancelliere. Nel 1621 viene accusato di corruzione, ammette di avere ricevuto doni e perde la carica. La caduta gli lascia più tempo per scrivere, ma non va trasformata in una favola morale né nell’origine unica della sua filosofia: il progetto di rinnovare il sapere era iniziato molti anni prima. Muore nel 1626. La tradizione racconta che si ammalò dopo un esperimento sulla conservazione della carne con la neve; il particolare è suggestivo, ma non deve diventare il simbolo totale di una vita complessa.",beats:["1561: nascita a Londra.","Formazione a Cambridge e Gray’s Inn.","Lunga carriera parlamentare e giuridica.","1620: Novum Organum.","1621: caduta politica; 1626: morte."],example:"Una biografia spiega occasioni, reti e priorità; non prova da sola la validità di un metodo filosofico.",checkpoint:"Il progetto baconiano precede la caduta politica e nasce dall’intreccio di filosofia, diritto, amministrazione e riforma."},student:{summary:"La figura del filosofo non è separabile dallo statista, ma i rapporti fra carriera, patronage, riforma giuridica e riforma del sapere richiedono prudenza interpretativa.",concepts:["Patronage","Riforma del diritto","Carriera parlamentare","Caduta del 1621","Scrittura filosofica"],argument:"L’esperienza amministrativa può avere favorito l’idea di una ricerca organizzata e divisa in compiti; ciò resta un’interpretazione storica, non una deduzione necessaria dalla biografia.",source:"Stanford Encyclopedia of Philosophy, Life in Philosophy, Politics and Law.",warning:"Non presentare la morte durante l’esperimento sulla neve come un fatto filosoficamente decisivo né ignorare la controversia della carriera pubblica."}},
    {id:"instauratio",number:"04",kicker:"La Grande Instaurazione",accent:"#d0a14d",title:"Ricominciare il lavoro della mente",question:"Che cosa significa rifondare l’intero sapere?",amateur:{summary:"La Grande Instaurazione è un progetto in sei parti, molto più ampio del solo metodo induttivo, rimasto in larga misura incompiuto.",narrative:"Bacone non propone una singola regola, ma un cantiere. Vuole classificare le scienze esistenti, fornire un nuovo strumento logico, raccogliere storie naturali, mostrare esempi del metodo, costruire assiomi provvisori e arrivare infine a una nuova filosofia. Il Novum Organum del 1620 rappresenta la seconda parte di questo piano. Il progetto resta incompleto, e proprio questa incompiutezza è istruttiva: la riforma non è l’opera miracolosa di un genio isolato, ma un’impresa che richiede generazioni, risorse, raccolta dei dati e collaborazione.",beats:["La riforma riguarda tutte le scienze.","Il Novum Organum è una parte del progetto.","La storia naturale precede gli assiomi.","Il lavoro è collettivo e intergenerazionale."],example:"Un nuovo laboratorio non nasce da una formula: servono archivi, protocolli, strumenti, persone e criteri di controllo.",checkpoint:"La Grande Instaurazione è un programma di ricerca, non un manuale concluso."},student:{summary:"L’Instauratio Magna articola classificazione, nuovo organon, storie naturali, scala dell’intelletto, anticipazioni provvisorie e filosofia compiuta.",concepts:["Sei parti","Novum Organum","Historia naturalis et experimentalis","Scala intellectus","Filosofia seconda"],argument:"L’incompiutezza non è un dettaglio editoriale: impedisce di identificare il programma dichiarato con una scienza già realizzata e invita a distinguere metodo, esempi e cosmologia baconiana.",source:"Instauratio Magna e Novum Organum; Stanford Encyclopedia of Philosophy, sezione 4.",warning:"Non ridurre l’Instauratio Magna al solo Novum Organum o a una ricetta in pochi passaggi."}},
    {id:"idoli",number:"05",kicker:"Pars destruens",accent:"#a77eaa",title:"La mente non è uno specchio limpido",question:"Perché l’intelligenza può diventare la prima produttrice dell’errore?",amateur:{summary:"Prima di interpretare la natura occorre riconoscere le distorsioni che appartengono alla specie, all’individuo, al linguaggio e ai sistemi ricevuti.",narrative:"Gli idoli non sono semplicemente bugie che qualcuno ci racconta. Sono tendenze capaci di deformare l’esperienza prima ancora che iniziamo a ragionare consapevolmente. Gli idoli della Tribù derivano dalla natura umana, che cerca più ordine e conferme di quanto i fatti autorizzino; quelli della Caverna nascono dalla storia individuale; quelli del Mercato si insinuano attraverso parole imprecise; quelli del Teatro provengono da sistemi filosofici messi in scena come mondi coerenti. Conoscerne il nome non basta: occorrono procedure, strumenti e prove che limitino il potere della mente di giudicare da sola.",beats:["Tribù: deformazioni comuni agli esseri umani.","Caverna: inclinazioni della persona.","Mercato: trappole del linguaggio condiviso.","Teatro: sistemi accolti come rappresentazioni complete."],example:"Se ricordo soprattutto le previsioni riuscite e dimentico quelle fallite, l’ordine che vedo potrebbe provenire dalla selezione della memoria.",checkpoint:"La critica degli idoli non distrugge la ragione: la rende responsabile dei propri limiti."},student:{summary:"La dottrina degli idola è interna alla teoria della vera induzione: la correzione dei sensi e dell’intelletto richiede esperimenti ordinati.",concepts:["Idola Tribus","Idola Specus","Idola Fori","Idola Theatri","Regolazione dell’intelletto"],argument:"Gli idoli non hanno tutti lo stesso statuto: Tribù e Caverna riguardano disposizioni umane e individuali; Mercato e Teatro introducono dimensioni sociali, linguistiche e dottrinali.",source:"Novum Organum, I, aforismi 39–68; Stanford Encyclopedia of Philosophy, sezione 4.2.",warning:"Il confronto con i bias contemporanei è didatticamente utile, ma non rende gli idoli una teoria psicologica moderna ante litteram."}},
    {id:"ape",number:"06",kicker:"Anticipare o interpretare",accent:"#d1a93d",title:"Formica, ragno, ape",question:"Basta raccogliere fatti oppure basta ragionare bene?",amateur:{summary:"La formica accumula, il ragno produce tutto da sé, l’ape raccoglie e trasforma: Bacone cerca una cooperazione disciplinata fra esperienza e intelletto.",narrative:"Due estremi falliscono. L’empirico simile alla formica ammassa osservazioni senza trasformarle in una struttura conoscitiva; il razionalista simile al ragno tesse il proprio sistema dalla sostanza della mente. L’ape, invece, raccoglie il materiale dai fiori e lo elabora. La metafora chiarisce che Bacone non propone una passività dei sensi: l’esperienza deve essere costruita e ordinata, mentre l’intelletto deve lavorare senza imporre troppo presto i propri schemi. Anticipare la natura significa saltare dai pochi casi agli assiomi generali; interpretarla significa salire gradualmente, lasciando che esclusioni e controlli modifichino le ipotesi.",beats:["La raccolta senza elaborazione non basta.","La deduzione autosufficiente non basta.","L’esperimento è esperienza organizzata.","Gli assiomi devono crescere per gradi."],example:"Un elenco di temperature non è ancora una spiegazione; una teoria elegante priva di confronto non è ancora conoscenza della natura.",checkpoint:"L’ape rappresenta una relazione trasformativa fra dati e ragione, non il trionfo di uno dei due."},student:{summary:"La distinzione fra anticipatio e interpretatio naturae riguarda la direzione e la gradualità dell’inferenza, non una contrapposizione rozza fra ragione ed esperienza.",concepts:["Anticipatio naturae","Interpretatio naturae","Empirici","Dogmatici","Esperimento ordinato"],argument:"Il metodo baconiano è artificiale nel senso forte: produce fenomeni, costruisce serie, confronta istanze e costringe l’intelletto a operare entro un ordine.",source:"Novum Organum, I, aforismi 19–28 e 95.",warning:"Non confondere l’ape con un semplice compromesso: il materiale dell’esperienza viene metodicamente trasformato."}},
    {id:"induzione",number:"07",kicker:"Pars construens",accent:"#72a09a",title:"Salire senza saltare",question:"Come si passa dai casi agli assiomi senza generalizzare troppo presto?",amateur:{summary:"La vera induzione non conta esempi favorevoli: cerca differenze, casi negativi e variazioni capaci di eliminare spiegazioni.",narrative:"Dire «ho visto molti cigni bianchi, dunque tutti i cigni sono bianchi» è un’induzione per semplice enumerazione. Bacone la considera fragile. La sua proposta procede attraverso una storia ordinata del fenomeno e soprattutto attraverso esclusioni. Un’ipotesi deve spiegare i casi in cui il fenomeno compare, quelli simili nei quali manca e quelli nei quali cresce o diminuisce. Il sapere sale dai particolari ad assiomi bassi e medi, poi verso proposizioni più generali; può inoltre tornare verso l’esperienza per produrre nuove prove. Non è una scala percorsa una sola volta, ma un movimento controllato.",beats:["Raccogliere casi vari e pertinenti.","Cercare assenze e controistanze.","Escludere le nature incompatibili.","Formulare assiomi intermedi.","Produrre nuovi esperimenti."],example:"Per capire il calore, la luce solare non basta: occorre confrontarla con la luce lunare, con il moto, con la combustione e con gradi differenti.",checkpoint:"La forza dell’induzione baconiana sta nell’eliminazione, non nel numero delle conferme."},student:{summary:"L’induzione eliminativa mira a separare le nature e a raggiungere conclusioni mediante esclusioni e rigetti, opponendosi all’inductio per enumerationem simplicem.",concepts:["Induzione eliminativa","Assiomi medi","Controistanza","Esclusione","Ritorno alle opere"],argument:"La procedura non coincide con una formalizzazione probabilistica moderna: cerca una necessità fondata sulla connessione fra natura indagata e forma.",source:"Novum Organum, I, aforismi 19 e 104–106; II, aforismi 10–20.",warning:"Non descrivere Bacone come se avesse già formulato l’attuale metodo ipotetico-deduttivo o la statistica sperimentale."}},
    {id:"tavole",number:"08",kicker:"Ordinare l’esperienza",accent:"#7d9fc1",title:"Le tre tavole",question:"Quali confronti rendono davvero informativa un’osservazione?",amateur:{summary:"Presenza, assenza in prossimità e gradi trasformano un insieme di casi in uno strumento di confronto.",narrative:"La tavola della presenza raccoglie casi nei quali compare la natura studiata. Quella dell’assenza in prossimità non elenca semplicemente ogni assenza possibile: cerca casi simili ai precedenti nei quali il fenomeno manca. La tavola dei gradi registra variazioni di intensità. Nel caso del calore, i raggi del Sole appartengono alla presenza, quelli della Luna offrono un’assenza vicina, mentre differenti livelli di agitazione o combustione mostrano gradi. Il valore delle tavole non è burocratico: consiste nel creare confronti che la memoria spontanea non costruirebbe.",beats:["Presenza: dove il fenomeno compare.","Assenza vicina: caso simile senza il fenomeno.","Gradi: come il fenomeno varia.","Confronto: che cosa può essere escluso."],example:"Se luce e calore coincidessero sempre, i raggi lunari dovrebbero riscaldare come quelli solari; la differenza obbliga a rivedere l’ipotesi.",checkpoint:"Una tabella è filosoficamente utile quando organizza differenze capaci di smentire."},student:{summary:"Le tabulae non costituiscono una mera raccolta, ma una dispositio della storia naturale finalizzata alla reiezione delle nature semplici incompatibili.",concepts:["Tabula praesentiae","Absentia in proximo","Tabula graduum","Natura data","Istanza"],argument:"La prossimità dell’assenza controlla le differenze fra casi comparabili; senza questa selezione, l’assenza sarebbe troppo generica per sostenere un’esclusione.",source:"Novum Organum, II, aforismi 11–13; Stanford Encyclopedia of Philosophy, sezione 4.2.",warning:"Non chiamare “esperimento controllato” ogni riga delle tavole: il confronto anticipa procedure successive, ma mantiene una struttura secentesca."}},
    {id:"vendemmia",number:"09",kicker:"Esclusione e prova",accent:"#a8885b",title:"La prima vendemmia non è il raccolto",question:"Quando un’ipotesi diventa abbastanza buona da meritare nuovi esperimenti?",amateur:{summary:"Dopo le esclusioni rimane una prima interpretazione: è provvisoria e deve guidare prove più penetranti.",narrative:"Confrontando le tavole, il ricercatore elimina le nature che compaiono quando il fenomeno manca, che mancano quando esso compare oppure che non variano insieme a esso. Ciò che resta permette una prima vendemmia: non la verità definitiva, ma un’ipotesi abbastanza articolata da indicare nuove prove. Le istanze prerogative sono casi particolarmente informativi; fra esse, le istanze della croce aiutano a decidere tra direzioni alternative quando il percorso si biforca. Il metodo acquista forza perché organizza anche la fase successiva alla prima ipotesi.",beats:["Escludere ciò che non segue il fenomeno.","Formulare una prima interpretazione.","Individuare prove più informative.","Rivedere o rafforzare l’ipotesi."],example:"Se due spiegazioni prevedono effetti diversi in una situazione decisiva, costruire quel caso è più utile che accumulare altri esempi ordinari.",checkpoint:"La prima vendemmia vale perché apre un nuovo ciclo di controllo."},student:{summary:"La vindemiatio prima segue le esclusioni; le ventisette classi di instantiae praerogativae orientano l’ascesa verso le forme e la progettazione sperimentale.",concepts:["Reiectio","Vindemiatio prima","Instantiae praerogativae","Instantia crucis","Esperimento lucifero"],argument:"L’istanza della croce non è automaticamente l’experimentum crucis moderno: appartiene a un sistema di prerogative più vasto e alla ricerca baconiana delle forme.",source:"Novum Organum, II, aforismi 16–20 e 36–52.",warning:"Non presentare la prima vendemmia come una conclusione certa o le istanze prerogative come una singola prova magica."}},
    {id:"forme",number:"10",kicker:"Che cosa si cerca",accent:"#8b82b3",title:"Le forme non sono formule moderne",question:"La “forma” baconiana coincide con una legge scientifica?",amateur:{summary:"Bacone cerca strutture operative profonde della natura, ma il suo lessico appartiene a una cosmologia diversa dalla nostra.",narrative:"Quando parla di forma, Bacone non intende semplicemente la forma esterna di un oggetto. Cerca ciò che rende una natura, come il calore, capace di prodursi nei diversi corpi. Nel Novum Organum propone provvisoriamente di interpretare il calore come una specie di movimento. La somiglianza con l’idea moderna di legge è reale soltanto in parte: la sua teoria comprende nozioni di materia tangibile e pneumatica, spiriti e schemi di movimento che non appartengono alla fisica attuale. Capire storicamente Bacone significa resistere alla tentazione di tradurlo tutto nel linguaggio contemporaneo.",beats:["La forma è legata alla produzione di una natura.","Conoscere permette di operare.","La cosmologia baconiana è storicamente situata.","Le somiglianze moderne non cancellano le differenze."],example:"Dire che Bacone “anticipa” una legge moderna può illuminare una continuità, ma può anche nascondere ciò che egli pensava davvero della materia.",checkpoint:"Le forme uniscono spiegazione e operazione, senza coincidere semplicemente con le leggi della fisica moderna."},student:{summary:"La ricerca delle forme appartiene alla metafisica baconiana e si lega agli schematismi e ai processi latenti della materia.",concepts:["Forma","Processus latens","Schematismus latens","Materia tangibile e pneumatica","Scientia activa"],argument:"L’operatività dipende dalla convertibilità fra conoscenza della forma e capacità di introdurre una natura in un corpo; questo quadro è più ricco e più estraneo al presente di una semplice teoria delle leggi.",source:"Novum Organum, II, aforismi 1–10; Stanford Encyclopedia of Philosophy, sezioni 4.4 e 5.",warning:"Non sostituire “forma” con “legge scientifica” senza dichiarare che si tratta di un’analogia limitata."}},
    {id:"potere",number:"11",kicker:"Sapere operativo",accent:"#c66e58",title:"Conoscere è poter fare",question:"Il potere della conoscenza è automaticamente un bene?",amateur:{summary:"Il sapere deve produrre opere capaci di alleviare la condizione umana; proprio questa potenza apre una domanda etica.",narrative:"Bacone lega strettamente conoscenza e potere: possiamo trasformare la natura soltanto obbedendo alle sue regolarità. Il fine non è il dominio arbitrario, perché un desiderio non modifica i processi naturali; è la capacità di ottenere effetti attraverso una comprensione disciplinata. La promessa riguarda salute, alimentazione, tecniche e riduzione delle sofferenze. Ma la storia successiva rende inevitabile una domanda che il progetto non risolve interamente: chi stabilisce quali effetti siano benefici, chi controlla gli strumenti e chi sopporta i rischi? La PWA non attribuisce a Bacone tutte le conseguenze della tecnica moderna; usa però la sua equazione per aprire un problema ancora vivo.",beats:["La natura si trasforma seguendone i processi.","Il sapere mira a opere utili.","L’utilità non è eticamente neutrale.","Potere e responsabilità devono essere pensati insieme."],example:"Una tecnica capace di aumentare i raccolti può ridurre la fame oppure concentrare dipendenze e controllo: l’efficacia non decide da sola il valore.",checkpoint:"La conoscenza operativa moltiplica le possibilità; non sceglie automaticamente i fini."},student:{summary:"La relazione fra scientia e potentia orienta la natural philosophy verso una scientia activa e verso il relief of man’s estate.",concepts:["Scientia potentia","Opere e frutti","Carità","Dominio tecnico","Responsabilità"],argument:"La critica novecentesca ha letto Bacone come emblema del dominio sulla natura; la storiografia recente ne ricostruisce anche il contesto religioso, politico e filantropico, evitando genealogie monocausali.",source:"Novum Organum, I, aforismi 1–3; Stanford Encyclopedia of Philosophy, sezioni 3, 4.4 e 9.",warning:"Non assolvere né condannare Bacone per l’intera modernità tecnica: distinguere testo, ricezione e sviluppi storici."}},
    {id:"atlantide",number:"12",kicker:"Istituzione ed eredità",accent:"#6ca8b1",title:"La Casa di Salomone",question:"Può la scienza avanzare come impresa di individui isolati?",amateur:{summary:"Nella Nuova Atlantide la ricerca diventa un’istituzione cooperativa, divisa in compiti e orientata a conoscenza e opere.",narrative:"L’isola di Bensalem ospita la Casa di Salomone. Alcuni membri raccolgono notizie e invenzioni, altri ordinano gli esperimenti, altri ancora progettano nuove prove o formulano assiomi. La scena non descrive un laboratorio moderno già pronto, ma rende immaginabile una ricerca stabile, finanziata e collettiva. Nel 1660 la Royal Society si richiamerà alla visione baconiana dell’indagine sperimentale come attività cooperativa per il bene pubblico. L’eredità, tuttavia, non coincide con l’esecuzione fedele di un metodo: la scienza successiva userà matematica, ipotesi e pratiche che Bacone aveva valutato diversamente.",beats:["La ricerca richiede divisione del lavoro.","Raccolta, esperimento e interpretazione sono collegati.","La pubblicazione è una decisione istituzionale.","L’eredità riguarda collaborazione, utilità e progresso."],example:"Un grande esperimento contemporaneo dipende da tecnici, archivi, strumenti, protocolli, finanziamenti e decisioni collettive, non soltanto dall’idea di un singolo.",checkpoint:"Bacone lascia soprattutto un programma di ricerca cooperativa, non la formula definitiva della scienza."},student:{summary:"Salomon’s House istituzionalizza la natural philosophy; la sua organizzazione apre problemi di cooperazione, segretezza, rapporto con lo Stato e decisione sui risultati.",concepts:["Bensalem","Salomon’s House","Divisione del lavoro","Royal Society","Eredità baconiana"],argument:"La Royal Society interpretò l’attività sperimentale collettiva come realizzazione della visione baconiana, ma la ricezione non prova una discendenza metodologica lineare.",source:"New Atlantis; Cambridge Whipple Library, Francis Bacon and the Royal Society; Stanford Encyclopedia of Philosophy, sezioni 6 e 9.",warning:"Non presentare la Casa di Salomone come una democrazia scientifica moderna né la Royal Society come una semplice copia."}}
  ],
  discovery:[
    {title:"Il messaggio",text:"Nel gruppo della classe compare una notizia: «Uno studio universitario dimostra che ascoltare musica mentre si studia raddoppia la memoria». È esattamente ciò che speravi fosse vero. Che cosa fai per prima cosa?",choices:[{label:"La inoltro: viene da uno “studio”",idol:"Teatro",feedback:"Hai concesso autorità a una formula senza controllare istituzione, metodo o testo. Un sistema di parole ha preso il posto dell’indagine."},{label:"Cerco subito testimonianze favorevoli",idol:"Tribù",feedback:"Hai cercato conferme e trascurato la possibilità di casi contrari: la mente ama trovare più ordine di quanto i dati autorizzino."},{label:"Controllo fonte, campione e confronto",idol:null,feedback:"Hai rallentato il giudizio e trasformato l’affermazione in domande verificabili. È un buon inizio, non ancora una conclusione."},{label:"È vero per me, quindi è vero",idol:"Caverna",feedback:"Hai generalizzato la tua esperienza individuale. La caverna personale ha colorato l’intero fenomeno."}]},
    {title:"La parola ambigua",text:"Scopri che lo studio parla di “prestazione migliore”, ma non definisce chiaramente che cosa significhi. Come procedi?",choices:[{label:"Prestazione migliore significa memoria migliore",idol:"Mercato",feedback:"Hai lasciato che due espressioni diverse sembrassero equivalenti. Le parole hanno guidato il ragionamento."},{label:"Cerco come è stata misurata",idol:null,feedback:"Hai chiesto una definizione operativa: quale prova, quale durata, quale confronto? Il linguaggio torna sotto controllo."},{label:"Mi basta il titolo",idol:"Teatro",feedback:"Il titolo è diventato una scena completa dietro cui il metodo è scomparso."},{label:"Scelgo il significato più utile alla mia tesi",idol:"Tribù",feedback:"La mente ha piegato l’ambiguità verso ciò che desiderava trovare."}]},
    {title:"Il caso contrario",text:"Fra i risultati compare un gruppo che con la musica ha ottenuto punteggi peggiori. Che valore gli attribuisci?",choices:[{label:"È un’eccezione trascurabile",idol:"Tribù",feedback:"Forse lo è, forse no. Scartarlo perché disturba la tesi è proprio il comportamento che un metodo deve impedire."},{label:"Lo uso per negare tutto",idol:"Caverna",feedback:"Anche una confutazione affrettata può nascere da una preferenza personale. Un caso contrario va interpretato nel disegno complessivo."},{label:"Confronto condizioni e differenze",idol:null,feedback:"Hai trasformato il caso contrario in informazione: tipo di musica, compito, età, abitudini e grandezza dell’effetto."},{label:"Cambio discorso",idol:"Mercato",feedback:"Spostare le parole evita il problema, ma non lo risolve."}]}
  ],
  tableCases:[
    {id:"sole",label:"Raggi del Sole",table:"presence",why:"Nel caso baconiano sono associati al calore."},{id:"fiamma",label:"Fiamma viva",table:"presence",why:"Il fenomeno del calore è presente in modo evidente."},{id:"acqua",label:"Acqua in ebollizione",table:"presence",why:"Il calore è presente anche senza luce propria."},{id:"luna",label:"Raggi della Luna",table:"absence",why:"Somigliano ai raggi solari per luminosità, ma non riscaldano allo stesso modo."},{id:"lucefredda",label:"Luce senza calore percepibile",table:"absence",why:"È un caso vicino che separa luce e calore."},{id:"moto",label:"Corpo sfregato rapidamente",table:"degrees",why:"All’aumentare del moto prodotto dallo sfregamento cresce il calore."},{id:"stagioni",label:"Raggi solari in stagioni diverse",table:"degrees",why:"Consentono un confronto di intensità e condizioni."},{id:"metallo",label:"Metallo da tiepido a incandescente",table:"degrees",why:"Mostra una variazione continua del fenomeno."}
  ],
  idolCases:[
    {text:"Ricordi le tre previsioni riuscite e dimentichi le sette fallite.",answer:"Tribù",why:"La mente seleziona le conferme e impone una regolarità."},
    {text:"La tua formazione artistica ti porta a spiegare ogni problema attraverso immagini.",answer:"Caverna",why:"Una disposizione individuale colora l’intero campo dell’esperienza."},
    {text:"Due gruppi litigano sulla parola “naturale” senza definirla.",answer:"Mercato",why:"La parola vaga genera una disputa che sembra riguardare le cose."},
    {text:"Una teoria elegante viene difesa perché il suo sistema appare completo.",answer:"Teatro",why:"La coerenza della rappresentazione prende il posto della verifica."},
    {text:"Un algoritmo mostra soprattutto notizie simili a quelle già approvate.",answer:"Caverna",why:"È un’applicazione contemporanea: la personalizzazione rinforza una prospettiva particolare. Non è un’identificazione storica letterale."},
    {text:"“Lo dicono gli esperti” chiude ogni domanda su dati e metodo.",answer:"Teatro",why:"L’autorità viene trasformata in scena autosufficiente invece di orientare verso prove controllabili."}
  ],
  sources:[
    {type:"Fonte primaria",title:"Il ministro e interprete",quote:"L’uomo, ministro e interprete della natura, opera e comprende soltanto quanto ha osservato.",ref:"Novum Organum, I, 1",note:"Il potere non nasce dal comando arbitrario: dipende dalla comprensione dell’ordine naturale."},
    {type:"Fonte primaria",title:"Due vie",quote:"Una via vola dai sensi agli assiomi più generali; l’altra sale gradualmente e per gradi.",ref:"Novum Organum, I, 19",note:"È il contrasto fra anticipazione e interpretazione della natura."},
    {type:"Fonte primaria",title:"La mente deformante",quote:"L’intelletto umano è simile a uno specchio che mescola la propria natura con quella delle cose.",ref:"Novum Organum, I, 41",note:"La traduzione è didattica; il passo introduce la funzione epistemica degli idoli."},
    {type:"Fonte primaria",title:"Formica, ragno, ape",quote:"L’ape raccoglie il materiale e poi lo trasforma con una facoltà propria.",ref:"Novum Organum, I, 95",note:"Esperienza e ragione cooperano, ma entrambe devono essere disciplinate."},
    {type:"Fonte primaria",title:"Il fine della fondazione",quote:"Conoscere le cause e ampliare i confini del potere umano verso le cose possibili.",ref:"New Atlantis, Salomon’s House",note:"La ricerca viene immaginata come impresa istituzionale, cooperativa e operativa."},
    {type:"Problema storiografico",title:"Bacone e la scienza moderna",quote:"L’influenza è decisiva, ma non lineare: programma, ricezione e pratiche successive non coincidono.",ref:"Stanford Encyclopedia of Philosophy, Legacy",note:"La formula “padre del metodo scientifico” nasconde differenze importanti e va usata con cautela."}
  ],
  comics:[
    {year:"1573",symbol:"C",title:"Cambridge",text:"Un curriculum ancora medievale incontra umanesimo, retorica e problemi pratici.",detail:"Bacone arriva al Trinity College a dodici anni. La tradizione racconta una precoce insofferenza per Aristotele, ma la formazione ricevuta resta parte essenziale del suo vocabolario."},
    {year:"1576",symbol:"✦",title:"Verso la Francia",text:"Diplomazia, diritto civile e osservazione delle istituzioni europee.",detail:"Al seguito dell’ambasciatore Amias Paulet, il giovane Bacon viaggia e studia. La dimensione pubblica non sarà un’aggiunta tardiva alla sua filosofia."},
    {year:"1581",symbol:"§",title:"In Parlamento",text:"Comincia una carriera che durerà fino al 1621.",detail:"Diritto, riforma e amministrazione alimentano l’idea che il sapere debba essere ordinato, utile e sostenuto dalle istituzioni."},
    {year:"1597",symbol:"E",title:"Gli Essays",text:"Una scrittura breve osserva ambizione, amicizia, studio e potere.",detail:"Le numerose edizioni degli Essays rendono Bacon un autore pubblico ben prima del Novum Organum."},
    {year:"1605",symbol:"A",title:"Advancement of Learning",text:"Il sapere viene censito per mostrarne conquiste e mancanze.",detail:"Classificare le scienze non significa chiuderle: serve a individuare i campi ancora da coltivare."},
    {year:"1620",symbol:"N",title:"Novum Organum",text:"Un nuovo strumento per impedire alla mente di correre troppo.",detail:"L’opera presenta idoli, critica del sillogismo, induzione eliminativa, tavole e istanze prerogative. È soltanto la seconda parte della Grande Instaurazione."},
    {year:"1621",symbol:"↓",title:"La caduta",text:"Accusato di corruzione, perde il cancellierato e la vita politica.",detail:"Bacon ammette di aver ricevuto doni. La caduta non crea il progetto filosofico, già maturo, ma modifica gli ultimi anni della sua attività."},
    {year:"1627",symbol:"⛰",title:"La Nuova Atlantide",text:"Dopo la morte appare l’isola nella quale la ricerca diventa istituzione.",detail:"L’opera incompiuta immagina Bensalem e la Casa di Salomone: raccolta, esperimento, interpretazione, segretezza e utilità pubblica convivono in una visione potente e problematica."}
  ],
  maps:[
    {id:"errore",number:"01",title:"Dall’idolo al controllo",intro:"Il metodo inizia impedendo alla mente di trasformare una preferenza in una legge della natura.",nodes:[{tag:"Impulso",label:"Aspettativa",short:"Voglio che sia vero",amateur:"Il desiderio orienta l’attenzione prima del giudizio.",student:"L’intelletto tende a supporre maggiore ordine e regolarità."},{tag:"Diagnosi",label:"Idolo",short:"Nomino la distorsione",amateur:"Riconoscere il tipo di errore permette di non scambiarlo per evidenza.",student:"La dottrina degli idola descrive ostacoli antropologici, individuali, linguistici e dottrinali."},{tag:"Disciplina",label:"Esperimento",short:"Costruisco un controllo",amateur:"Cerco una prova che possa contraddirmi.",student:"L’esperimento media fra senso e cosa e regola il lavoro dell’intelletto."},{tag:"Esito",label:"Revisione",short:"Cambio l’ipotesi",amateur:"La correzione non è una sconfitta: è conoscenza che avanza.",student:"La reiezione delle nature incompatibili prepara assiomi più adeguati."}]},
    {id:"metodo",number:"02",title:"La scala dell’induzione",intro:"Non un salto dal caso alla legge, ma un’ascesa che ritorna continuamente alle opere.",nodes:[{tag:"Base",label:"Storia naturale",short:"Casi e operazioni",amateur:"Raccolta ampia e progettata.",student:"Materia ordinata per l’interpretatio naturae."},{tag:"Ordine",label:"Tavole",short:"Presenza, assenza, gradi",amateur:"I confronti diventano visibili.",student:"Dispositio delle istanze pertinenti."},{tag:"Filtro",label:"Esclusione",short:"Elimino incompatibilità",amateur:"I casi contrari lavorano davvero.",student:"Reiectio delle nature non convertibili."},{tag:"Ipotesi",label:"Prima vendemmia",short:"Una risposta provvisoria",amateur:"Abbastanza buona da guidare nuove prove.",student:"Interpretazione iniziale dopo la prima esclusione."},{tag:"Ritorno",label:"Istanze",short:"Prove più penetranti",amateur:"Metto l’ipotesi in condizioni difficili.",student:"Prerogative instances e nuova ascesa."}]},
    {id:"sapere",number:"03",title:"Sapere, potere, responsabilità",intro:"La conoscenza operativa produce effetti; perciò rende inevitabile la domanda sui fini.",nodes:[{tag:"Conoscere",label:"Regolarità",short:"Comprendere i processi",amateur:"Non comandiamo alla natura con desideri.",student:"Potentia e scientia coincidono nell’operazione regolata."},{tag:"Operare",label:"Tecnica",short:"Produrre effetti",amateur:"Il sapere diventa capacità di fare.",student:"Scientia activa e invenzione di opere."},{tag:"Valutare",label:"Beneficio",short:"Alleviare la condizione",amateur:"La promessa riguarda la vita umana.",student:"Relief of man’s estate e carità."},{tag:"Rispondere",label:"Responsabilità",short:"Scegliere fini e rischi",amateur:"Non tutto ciò che possiamo fare deve essere fatto.",student:"Estensione contemporanea dichiarata, non dottrina testuale baconiana."}]},
    {id:"istituzione",number:"04",title:"La Casa di Salomone",intro:"Il sapere cresce quando ruoli differenti costruiscono una memoria comune e nuove prove.",nodes:[{tag:"Raccogliere",label:"Mercanti di luce",short:"Notizie e invenzioni",amateur:"Il sapere circola oltre i confini.",student:"Acquisizione internazionale di libri, modelli ed esperimenti."},{tag:"Ordinare",label:"Compilatori",short:"Titoli e tavole",amateur:"I dati diventano confrontabili.",student:"Riduzione delle esperienze a strutture utili agli assiomi."},{tag:"Progettare",label:"Lampade",short:"Nuovi esperimenti",amateur:"Le domande guidano nuove prove.",student:"Direzione di esperimenti più penetranti."},{tag:"Interpretare",label:"Interpreti",short:"Osservazioni e assiomi",amateur:"Il gruppo trasforma i risultati in conoscenza.",student:"Elevazione delle scoperte ad aphorismi e assiomi."}]}
  ],
  glossary:[
    ["Anticipazione della natura","Salto frettoloso da pochi casi a principi generali usati poi per giudicare tutto il resto."],["Assioma medio","Proposizione di generalità intermedia, raggiunta gradualmente e capace di guidare nuove esperienze."],["Caverna","Idolo legato all’indole, all’educazione e alla storia particolare dell’individuo."],["Esperimento","Intervento progettato che organizza l’esperienza per rispondere a una domanda determinata."],["Forma","Struttura causale e operativa cercata da Bacone; non coincide semplicemente con una legge moderna."],["Grande Instaurazione","Programma in sei parti per rinnovare l’intero sapere umano."],["Idolo","Distorsione stabile che ostacola l’interpretazione della natura."],["Induzione eliminativa","Procedimento che avanza mediante confronti, esclusioni e rigetti, non con la sola enumerazione."],["Interpretazione della natura","Ascesa regolata dai particolari ad assiomi via via più generali."],["Istanza della croce","Caso che orienta la scelta quando l’indagine si divide fra spiegazioni alternative."],["Istanza prerogativa","Caso particolarmente informativo che orienta l’indagine o la sperimentazione."],["Mercato","Idolo prodotto dall’uso sociale di parole confuse o mal definite."],["Novum Organum","Opera del 1620 che presenta il nuovo strumento logico e metodologico baconiano."],["Prima vendemmia","Prima interpretazione positiva formulata dopo le esclusioni; resta provvisoria."],["Salomon’s House","Istituzione scientifica immaginaria della Nuova Atlantide, fondata sulla divisione cooperativa del lavoro."],["Scientia activa","Conoscenza orientata alla produzione di opere ed effetti."],["Tavola dei gradi","Raccolta dei casi nei quali la natura studiata aumenta o diminuisce."],["Tavola della presenza","Raccolta organizzata dei casi in cui la natura studiata compare."],["Tavola dell’assenza in prossimità","Casi simili a quelli della presenza nei quali la natura studiata manca."],["Teatro","Idolo derivante da sistemi filosofici rappresentati come mondi completi e non sottoposti a prova."],["Tribù","Idolo radicato nelle tendenze comuni dell’intelletto umano."],["Vindemiatio prima","Espressione latina per la prima vendemmia."],["Storia naturale","Raccolta progettata di fatti, operazioni ed esperimenti, base della filosofia naturale."],["Reiezione","Esclusione delle nature incompatibili con la presenza, l’assenza o i gradi del fenomeno."]
  ],
  timeline:[["1561","Nasce a York House, Londra."],["1573–1575","Studia al Trinity College di Cambridge."],["1576–1579","Soggiorna in Francia al seguito dell’ambasciatore inglese."],["1581","Entra per la prima volta in Parlamento."],["1597","Pubblica la prima edizione degli Essays."],["1605","The Advancement of Learning."],["1607","Diventa solicitor-general."],["1618","È nominato Lord Cancelliere e barone di Verulamio."],["1620","Pubblica Instauratio Magna e Novum Organum."],["1621","Caduta politica dopo l’accusa di corruzione."],["1626–1627","Muore nel 1626; New Atlantis esce postuma nel 1627."],["1660","Fondazione della Royal Society, che si richiama alla visione sperimentale e cooperativa baconiana."]],
  library:[
    {year:"1597–1625",title:"Essays",role:"Morale e politica",desc:"Osservazioni su studio, ambizione, amicizia, verità e vita civile, ampliate in più edizioni."},
    {year:"1605",title:"The Advancement of Learning",role:"Mappa del sapere",desc:"Censisce i campi della conoscenza, ne denuncia le lacune e ne propone l’avanzamento."},
    {year:"1609",title:"De sapientia veterum",role:"Mito e interpretazione",desc:"Legge miti antichi come depositi allegorici di sapienza."},
    {year:"1620",title:"Instauratio Magna",role:"Il progetto",desc:"Presenta il vasto programma di rifondazione del sapere."},
    {year:"1620",title:"Novum Organum",role:"Il metodo",desc:"Idoli, critica della logica ricevuta, induzione, tavole e istanze prerogative."},
    {year:"1622",title:"Historia naturalis et experimentalis",role:"Storie naturali",desc:"Esempio del lavoro preparatorio necessario alla nuova filosofia."},
    {year:"1623",title:"De augmentis scientiarum",role:"Classificazione",desc:"Versione latina ampliata dell’Advancement of Learning."},
    {year:"1626",title:"Sylva Sylvarum",role:"Esperimenti e osservazioni",desc:"Raccolta pubblicata postuma da William Rawley."},
    {year:"1627",title:"New Atlantis",role:"Utopia scientifica",desc:"Bensalem e la Casa di Salomone immaginano la ricerca come istituzione cooperativa."}
  ],
  comparisons:[
    {name:"Aristotele",before:"L’esperienza contribuisce alla conoscenza; la dimostrazione scientifica organizza cause e principi.",bacon:"Contesta il salto precoce ai principi e l’uso della logica come strumento di scoperta.",after:"Non è esperienza contro ragione: cambia l’ordine metodico fra particolari, assiomi e opere."},
    {name:"Scolastica",before:"Pluralità di tradizioni universitarie che commentano, disputano e sviluppano l’eredità aristotelica.",bacon:"Attacca sistemi e dispute quando diventano autosufficienti rispetto alla storia naturale.",after:"La critica va storicizzata: il Medioevo non fu privo di empirismo né di innovazione."},
    {name:"Galileo",before:"La nuova scienza interroga la natura con esperimenti e matematizzazione.",bacon:"Privilegia storie naturali ampie e induzione eliminativa; valuta diversamente il ruolo della matematica.",after:"Entrambi rompono equilibri ricevuti, ma non condividono un unico metodo."},
    {name:"Cartesio",before:"Anche Cartesio cerca una fondazione nuova e critica il sapere scolastico.",bacon:"Parte dall’esperienza regolata e diffida della mente lasciata a se stessa.",after:"La contrapposizione empirismo/razionalismo orienta, ma semplifica due progetti più complessi."}
  ],
  quiz:[
    {q:"Qual è il difetto principale dell’anticipazione della natura?",options:["Raccoglie troppi casi","Salta troppo presto a principi generali","Usa soltanto strumenti","Rifiuta ogni ragionamento"],answer:1,explain:"L’anticipazione vola da pochi particolari agli assiomi più generali e poi li usa per giudicare i casi.",module:"ape"},
    {q:"Perché gli idoli fanno parte del metodo e non soltanto della psicologia morale?",options:["Perché indicano peccati individuali","Perché spiegano come punire gli errori","Perché ostacolano la costruzione della conoscenza","Perché eliminano la necessità degli esperimenti"],answer:2,explain:"Gli idoli deformano sensi, concetti, parole e sistemi; il metodo deve limitarne l’azione.",module:"idoli"},
    {q:"Quale coppia descrive correttamente Tribù e Caverna?",options:["Linguaggio e sistemi","Specie umana e individuo","Politica e religione","Esperimento e matematica"],answer:1,explain:"La Tribù riguarda tendenze comuni dell’umanità; la Caverna la prospettiva individuale.",module:"idoli"},
    {q:"Che cosa rende utile l’assenza “in prossimità”?",options:["È una qualunque assenza","È un caso simile nel quale il fenomeno manca","Conferma sempre l’ipotesi","Sostituisce la tavola dei gradi"],answer:1,explain:"La somiglianza controllata rende informativa la differenza.",module:"tavole"},
    {q:"La prima vendemmia è…",options:["La verità finale","Una prima ipotesi dopo le esclusioni","Una lista di autorità","La raccolta casuale dei dati"],answer:1,explain:"È un’interpretazione provvisoria che deve orientare nuove prove.",module:"vendemmia"},
    {q:"Che cosa simboleggia l’ape?",options:["La sola memoria","La deduzione pura","La trasformazione metodica del materiale dell’esperienza","Il rifiuto dell’intelletto"],answer:2,explain:"L’ape raccoglie e trasforma: esperienza e intelletto cooperano sotto disciplina.",module:"ape"},
    {q:"Perché non è esatto chiamare la forma una semplice legge moderna?",options:["Perché Bacone rifiuta ogni causa","Perché appartiene anche alla sua specifica teoria della materia e dell’operazione","Perché è soltanto una figura geometrica","Perché non riguarda la natura"],answer:1,explain:"La forma si lega a processi, schematismi e a una cosmologia secentesca.",module:"forme"},
    {q:"Quale affermazione descrive meglio il rapporto fra Bacone e la Scolastica?",options:["Prima di Bacone nessuno osservava","Bacone distrugge un unico sistema immobile","Bacone critica usi dell’autorità e del sillogismo, ma la tradizione precedente era plurale","Bacone accetta integralmente il metodo universitario"],answer:2,explain:"Una ricostruzione rigorosa evita la caricatura di Aristotele e del Medioevo.",module:"mondo"},
    {q:"Qual è una funzione delle istanze prerogative?",options:["Impedire ogni nuova ipotesi","Orientare indagine ed esperimenti dopo i primi risultati","Sostituire tutte le tavole","Confermare l’autorità degli antichi"],answer:1,explain:"Sono casi particolarmente informativi per avanzare dalla prima vendemmia verso interpretazioni migliori.",module:"vendemmia"},
    {q:"La Casa di Salomone mostra soprattutto…",options:["Un genio isolato","Una ricerca divisa in compiti e cooperativa","Il rifiuto delle applicazioni","Una scuola medievale immutabile"],answer:1,explain:"Raccolta, compilazione, esperimento e interpretazione sono organizzati come lavoro istituzionale.",module:"atlantide"},
    {q:"Che cosa autorizza l’equazione fra sapere e potere?",options:["Qualunque uso tecnicamente possibile","La trasformazione mediante comprensione dei processi naturali","Il dominio senza limiti","L’abbandono delle domande etiche"],answer:1,explain:"Per Bacone si comanda alla natura obbedendole; la scelta dei fini rimane un problema.",module:"potere"},
    {q:"Qual è il giudizio storico più prudente sull’eredità di Bacone?",options:["Inventò da solo il metodo scientifico attuale","Non influenzò la scienza","Fu decisivo per collaborazione, utilità ed empirismo, ma la scienza successiva non copiò un’unica ricetta","La Royal Society applicò alla lettera ogni sua regola"],answer:2,explain:"L’influenza fu profonda, ma non lineare né sufficiente a spiegare l’intera scienza moderna.",module:"atlantide"}
  ],
  academicSources:[
    {title:"Francis Bacon",institution:"Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/francis-bacon/",use:"Biografia, idoli, induzione, forme, scienza operativa, istituzioni ed eredità."},
    {title:"Ancient and Medieval Empiricism",institution:"Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/archives/spr2019/entries/empiricism-ancient-medieval/",use:"Correzione della caricatura di Aristotele e della tradizione medievale."},
    {title:"The Novum Organum, edizione storica",institution:"Oxford Text Archive · Bodleian Libraries, University of Oxford",url:"https://ota.bodleian.ox.ac.uk/repository/xmlui/handle/20.500.12024/A28309",use:"Testo primario e storia editoriale."},
    {title:"Of the Advancement and Proficience of Learning",institution:"Oxford Text Archive · Bodleian Libraries, University of Oxford",url:"https://ota.bodleian.ox.ac.uk/repository/xmlui/bitstream/handle/20.500.12024/A72146/A72146.html",use:"Classificazione e avanzamento del sapere."},
    {title:"The New Atlantis",institution:"Internet History Sourcebooks Project · Fordham University",url:"https://sourcebooks.web.fordham.edu/mod/1627bacon-atlantis.asp",use:"Testo della Nuova Atlantide e organizzazione della Casa di Salomone."},
    {title:"Francis Bacon and the Royal Society",institution:"Whipple Library · University of Cambridge",url:"https://www.whipplelib.hps.cam.ac.uk/special/exhibitions-and-displays/exhibitions-archive/universal-harmony/bacon",use:"Ricezione baconiana della scienza sperimentale collettiva."}
  ]
};
