window.CARTESIO_DATA={
  hotspots:{
    doubt:{title:"Il dubbio è uno strumento",text:"Cartesio non dubita per restare nell’incertezza. Tratta provvisoriamente come falso ciò che offre anche una sola ragione di dubbio, così da verificare se qualcosa resista alla demolizione."},
    cogito:{title:"L’atto che resiste",text:"Se vengo ingannato, devo esistere mentre sono ingannato. Il cogito non è ancora una teoria completa dell’io: è la certezza performativa che il pensare, ogni volta che accade, non può essere separato dall’esistenza del pensante."},
    method:{title:"L’ordine prima dell’accumulo",text:"Evidenza, analisi, sintesi ed enumerazione disciplinano il percorso della mente. Il metodo non promette onniscienza: chiede di non oltrepassare ciò che è chiaro e di ricostruire il complesso a partire dal semplice."}
  },
  discovery:[
    {title:"I sensi sotto esame",prompt:"Una torre lontana appare rotonda; da vicino mostra una base quadrata. Che cosa puoi concludere?",choices:[
      {label:"I sensi sono sempre falsi",title:"Hai generalizzato troppo",text:"Cartesio osserva che i sensi talvolta ingannano. Questo basta a sospendere la fiducia assoluta, non a provare che ogni percezione sia falsa."},
      {label:"Una credenza sensibile può essere dubitabile",title:"Hai aperto la prima crepa",text:"Il dubbio cerca una ragione sufficiente per non usare quella credenza come fondamento indubitabile."}
    ]},
    {title:"La stanza e il sogno",prompt:"Se nel sogno puoi credere di essere seduto accanto al fuoco, quale certezza viene colpita?",choices:[
      {label:"L’esistenza presente del mondo esterno",title:"Il dubbio si allarga",text:"L’argomento non dimostra che stai sognando: mostra che l’esperienza attuale non offre ancora un criterio assoluto di veglia."},
      {label:"Soltanto i ricordi lontani",title:"Il bersaglio è più radicale",text:"Cartesio mette in questione anche la scena apparentemente più vicina e quotidiana."}
    ]},
    {title:"Nemmeno la matematica?",prompt:"Due più tre sembra resistere al sogno. Perché introdurre un genio maligno?",choices:[
      {label:"Per raccontare un essere realmente esistente",title:"Hai trasformato un’ipotesi in una credenza",text:"Il genio maligno è un artificio meditativo: porta al limite la possibilità dell’inganno."},
      {label:"Per sospendere anche le evidenze razionali",title:"Il dubbio diventa iperbolico",text:"L’ipotesi non confuta la matematica; impedisce di usarla come fondamento prima che la capacità di conoscere sia stata garantita."}
    ]},
    {title:"L’inganno che fallisce",prompt:"Supponi che ogni contenuto del tuo pensiero sia falso. Che cosa non può essere falso mentre lo pensi?",choices:[
      {label:"Che esiste un mondo materiale","title":"Il ponte non è ancora ricostruito",text:"Nella Seconda Meditazione il mondo esterno resta sospeso."},
      {label:"Che esisto come essere che pensa",title:"Hai trovato il punto d’Archimede",text:"Per ingannarmi o dubitare devo essere. La certezza vale ogni volta che il pensiero è effettivamente compiuto."}
    ]},
    {title:"Che cosa sono?",prompt:"Dal cogito puoi già concludere di avere un corpo umano?",choices:[
      {label:"Sì, perché sento il corpo",title:"Hai riammesso ciò che era sospeso",text:"Il sentire è certo come modo del pensiero; non dimostra ancora che il corpo esterno esista come appare."},
      {label:"No: so anzitutto di essere una cosa che pensa",title:"Hai rispettato l’ordine",text:"Dubitare, comprendere, volere, immaginare e sentire appartengono alla cogitatio. La res extensa verrà recuperata più tardi."}
    ]},
    {title:"La posta in gioco",prompt:"Qual è il vero esito del dubbio cartesiano?",choices:[
      {label:"Restare scettici su tutto",title:"Il mezzo è diventato fine",text:"Cartesio distingue il proprio progetto dagli scettici: la demolizione serve a trovare un terreno resistente."},
      {label:"Trovare un primo fondamento e ricostruire",title:"Hai visto l’architettura",text:"Il cogito apre la costruzione; non basta però, da solo, a garantire Dio, il corpo, gli altri e la scienza."}
    ]}
  ],
  modules:[
    {id:"crisi",number:"01",accent:"#c49b4d",kicker:"Il mondo precedente",title:"Un sapere senza fondamenta comuni",question:"Perché la nuova scienza rende urgente una rifondazione del sapere?",amateur:{summary:"Cartesio cresce fra insegnamento scolastico, scoperte matematiche e nuova fisica. Il problema non è cancellare il passato, ma trovare un ordine capace di produrre certezza.",narrative:"La cultura appresa a La Flèche offre un sistema vasto, ma le dispute mostrano che l’autorità e il sillogismo non garantiscono accordo. Intanto astronomia, meccanica e geometria cambiano l’immagine della natura. Cartesio cerca un metodo unitario: non vuole aggiungere una teoria alla biblioteca, bensì stabilire come riconoscere e concatenare conoscenze sicure.",beats:["La scolastica fornisce concetti e discipline, non una certezza condivisa.","La matematica appare capace di ordine e dimostrazione.","La nuova fisica domanda spiegazioni meccaniche.","Il problema diventa architettonico: su quale fondamento costruire?"],example:"Un edificio può contenere stanze preziose e tuttavia avere fondamenta fragili. Cartesio non giudica ogni stanza falsa: decide di controllare il terreno.",checkpoint:"La rottura cartesiana nasce dalla ricerca di un criterio, non da un semplice rifiuto dei libri."},student:{summary:"Il progetto cartesiano sostituisce l’ordine scolastico delle scienze con l’ideale di una mathesis universalis e di una fisica meccanicistica.",concepts:["Scolastica","Rivoluzione scientifica","Mathesis universalis","Meccanicismo","Fondazione"],argument:"Se discipline diverse impiegano la medesima ragione, occorre esplicitare operazioni comuni — intuizione, deduzione e ordine — invece di accettare metodi separati soltanto per tradizione.",source:"Discorso sul metodo, parti I–II; SEP, Descartes’ Method §§1–3; SEP, René Descartes §§1–2.",warning:"Non descrivere la scolastica come un blocco irrazionale: Cartesio riceve da essa problemi e lessico che trasforma."},check:{question:"Qual è la domanda decisiva della prima tappa?",options:["Quanti libri possedeva Cartesio?","Come fondare e ordinare conoscenze certe?","Come eliminare ogni esperienza?"],correct:1,feedback:"La crisi riguarda il criterio e l’ordine del sapere.",recovery:"Distingui il contenuto delle discipline dal fondamento che dovrebbe renderle certe."}},
    {id:"vita",number:"02",accent:"#8c6f78",kicker:"Fratture biografiche",title:"La Flèche, il mondo e la prudenza",question:"Quanto della biografia illumina il progetto senza trasformarsi in leggenda?",amateur:{summary:"Formazione gesuitica, incontro con Beeckman, viaggi, sogni del 1619, lungo soggiorno nei Paesi Bassi e timore dopo Galileo scandiscono la ricerca di Cartesio.",narrative:"Nato nel 1596, Cartesio studia al collegio di La Flèche e si laurea in diritto a Poitiers. Nel 1618 incontra Isaac Beeckman, decisivo per l’interesse verso una scienza matematica della natura. I sogni del novembre 1619 sono noti attraverso una tradizione biografica che richiede cautela. Dal 1628 vive soprattutto nei Paesi Bassi. Dopo la condanna di Galileo nel 1633 rinuncia a pubblicare Il Mondo; nel 1649 accetta l’invito di Cristina di Svezia e muore a Stoccolma nel 1650.",beats:["1596: nascita a La Haye en Touraine.","1607 circa: ingresso a La Flèche.","1618: incontro con Beeckman.","1619: episodio dei sogni, mediato dalle fonti.","1628–1649: Paesi Bassi e opere maggiori."],example:"Un episodio biografico può spiegare una scelta editoriale, come nel caso di Galileo; non dimostra la verità del dualismo.",checkpoint:"Fatti, testimonianze posteriori e interpretazioni vanno mantenuti distinti."},student:{summary:"La cronologia accademica corregge il racconto eroico di una vita interamente pianificata come applicazione del metodo.",concepts:["La Flèche","Beeckman","Scientia mirabilis","Le Monde","Condanna di Galileo"],argument:"La biografia documenta condizioni, reti e prudenza editoriale. Il rapporto causale fra vita e sistema resta interpretativo e non autorizza formule totalizzanti.",source:"SEP, Descartes’ Life and Works §§1–5; SEP, René Descartes §1.",warning:"I tre sogni non sono un verbale diretto: la ricostruzione dipende soprattutto da Baillet e da materiali oggi perduti."},check:{question:"Come va presentato l’episodio del 1619?",options:["Come una rivelazione documentata parola per parola","Come tradizione biografica significativa ma mediata","Come invenzione certamente falsa"],correct:1,feedback:"La cautela distingue l’importanza dell’episodio dal grado della documentazione.",recovery:"Chiediti sempre chi testimonia un fatto e a quale distanza."}},
    {id:"metodo",number:"03",accent:"#c28647",kicker:"Il metodo",title:"Evidenza, analisi, sintesi, enumerazione",question:"Come impedire alla mente di confondere rapidità e chiarezza?",amateur:{summary:"Le quattro regole regolano accoglienza, scomposizione, ricostruzione e controllo. Non sono uno slogan, ma una sequenza di responsabilità.",narrative:"La prima regola sospende l’assenso finché qualcosa non appare chiaro e distinto; la seconda divide il problema; la terza ordina il passaggio dal semplice al complesso; la quarta verifica che nulla sia stato omesso. La matematica offre un modello di concatenazione, ma il metodo cartesiano non elimina osservazione ed esperienza dalle scienze.",beats:["Evidenza: non precipitare il giudizio.","Analisi: dividere la difficoltà.","Sintesi: procedere dal semplice al complesso.","Enumerazione: ricontrollare l’intera catena."],example:"Per capire perché una PWA non funziona, non cambi tutto insieme: isoli rete, cache, codice e risorse; poi ricostruisci e verifichi.",checkpoint:"Il metodo è disciplina dell’assenso e dell’ordine."},student:{summary:"Le quattro regole del Discorso condensano una metodologia più ampia sviluppata nelle Regulae, fondata su intuizione, deduzione, ordine e proporzione.",concepts:["Intuitus","Deductio","Analisi","Sintesi","Enumerazione"],argument:"La certezza non deriva dalla lunghezza di un ragionamento, ma dalla trasparenza dei passaggi e dalla continuità con principi colti chiaramente. Nella fisica, tuttavia, gli esperimenti aiutano a discriminare effetti compatibili con principi generali.",source:"Discorso, parte II; Regulae III, V, XII; SEP, Descartes’ Method; IEP, Descartes: Scientific Method.",warning:"Non trasformare Cartesio in un puro deduttivista che ignora ogni esperimento: gli studi accademici mostrano un ruolo empirico nella scelta fra spiegazioni possibili."},check:{question:"Quale regola controlla omissioni e completezza?",options:["Analisi","Enumerazione","Evidenza"],correct:1,feedback:"L’enumerazione rivede l’intera catena.",recovery:"Associa ogni regola a un verbo: accogliere, dividere, ordinare, controllare."}},
    {id:"morale",number:"04",accent:"#8f7a57",kicker:"Vivere mentre si dubita",title:"La morale provvisoria",question:"Come agire se la ricerca teorica sospende le vecchie certezze?",amateur:{summary:"Cartesio separa la radicalità della meditazione dalla necessità quotidiana di scegliere. Le massime provvisorie impediscono che il dubbio paralizzi l’azione.",narrative:"Mentre ricostruisce le proprie opinioni, Cartesio decide di rispettare leggi e costumi moderati, essere fermo nelle decisioni, modificare i desideri più che l’ordine del mondo e dedicarsi alla ricerca della verità. Provvisorio non significa irrilevante: indica una guida pratica che non pretende ancora la stessa fondazione della metafisica.",beats:["L’azione non può attendere una dimostrazione completa.","Moderazione protegge la convivenza.","Fermezza evita l’immobilità.","Autogoverno concentra l’agire su ciò che dipende da noi."],example:"Un viaggiatore perduto nel bosco deve scegliere una direzione e mantenerla: cambiare strada a ogni passo garantisce di non uscire.",checkpoint:"Il dubbio metodico riguarda la fondazione teorica, non autorizza irresolutezza permanente."},student:{summary:"La morale par provision connette epistemologia, prudenza e ascendenza stoica senza costituire l’ultima parola dell’etica cartesiana.",concepts:["Morale provvisoria","Risoluzione","Moderazione","Autocontrollo","Stoicismo"],argument:"La ricerca richiede condizioni pratiche stabili; perciò l’assenso teorico può essere sospeso più radicalmente della decisione morale, dove spesso bisogna agire senza evidenza completa.",source:"Discorso, parte III; SEP, Descartes’ Ethics §§2–3.",warning:"Non ridurre la prima massima a obbedienza cieca: il testo privilegia opinioni moderate e persone giudicate assennate."},check:{question:"Perché Cartesio formula una morale provvisoria?",options:["Per rinunciare alla verità","Per poter agire durante la rifondazione teorica","Per dimostrare il cogito"],correct:1,feedback:"La vita pratica non può essere sospesa come un giudizio metafisico.",recovery:"Distingui il tempo della decisione pratica dal tempo della dimostrazione."}},
    {id:"dubbio",number:"05",accent:"#6f7896",kicker:"Demolizione",title:"Sensi, sogno e genio maligno",question:"Quale credenza resiste se ogni fonte di certezza viene radicalizzata?",amateur:{summary:"Il dubbio procede per gradi: fallibilità dei sensi, indistinguibilità del sogno e ipotesi estrema di un ingannatore capace di colpire anche la matematica.",narrative:"Cartesio non accumula bizzarrie. Ogni passaggio colpisce un livello più profondo: prima alcune credenze sensibili, poi l’intera scena corporea, infine le operazioni che sembravano indipendenti dai sensi. Il genio maligno non è una dottrina religiosa né la conclusione del percorso: è la massima pressione immaginabile sul candidato fondamento.",beats:["I sensi talvolta ingannano.","Il sogno mette in dubbio la scena presente.","Le nature semplici sembrano resistere.","Il genio maligno sospende anche le evidenze razionali."],example:"Un collaudo di sicurezza non afferma che l’incendio avverrà: costruisce lo scenario peggiore per verificare ciò che resta operativo.",checkpoint:"Il dubbio è metodico e iperbolico, ma orientato alla costruzione."},student:{summary:"La Prima Meditazione usa dubbi scalari per ritirare l’assenso; l’interpretazione del loro esatto bersaglio resta discussa.",concepts:["Dubbio metodico","Argomento del sogno","Dio ingannatore","Genio maligno","Sospensione dell’assenso"],argument:"È sufficiente una ragione di dubbio per escludere una credenza dal fondamento assoluto. Il metodo tratta provvisoriamente il dubitabile come falso senza dimostrarne la falsità.",source:"Meditazioni I, AT VII 17–23; SEP, Descartes’ Epistemology §§2–4.",warning:"Non concludere che Cartesio creda realmente in un genio maligno o che sogno e veglia siano identici."},check:{question:"Che cosa fa il genio maligno nel metodo?",options:["Dimostra che la matematica è falsa","Spinge il dubbio fino alle evidenze razionali","Sostituisce Dio nel sistema finale"],correct:1,feedback:"È un’ipotesi di pressione epistemica, non una tesi ontologica finale.",recovery:"Distingui il contenuto di un’ipotesi dalla funzione che svolge."}},
    {id:"cogito",number:"06",accent:"#d0a451",kicker:"Punto d’Archimede",title:"Cogito: la certezza nell’atto",question:"Il cogito è un sillogismo oppure un’esperienza intellettuale immediata?",amateur:{summary:"Mentre dubito, penso; mentre penso, non posso negare di esistere. Il primo punto fermo è l’atto stesso del pensiero.",narrative:"L’ingannatore può falsare ogni contenuto, ma non può far sì che non esista colui che viene ingannato nel momento dell’inganno. Nelle Meditazioni la formula decisiva è: io sono, io esisto, ogni volta che la penso. Il cogito non dimostra ancora il corpo o il mondo; chiarisce che il pensiero comprende dubitare, comprendere, volere, immaginare e sentire come esperienze coscienti.",beats:["Il dubbio è un modo del pensiero.","Pensare richiede l’esistenza attuale del pensante.","La certezza è colta nell’atto.","Il soggetto è anzitutto res cogitans."],example:"Provare a pensare «io non esisto» conferma l’esistenza dell’atto che formula la negazione.",checkpoint:"Il cogito è primo nell’ordine della conoscenza, non necessariamente primo nell’ordine di tutto ciò che esiste."},student:{summary:"La tradizione interpreta il cogito come intuizione performativa, non come deduzione dipendente dalla premessa generale «tutto ciò che pensa esiste».",concepts:["Cogito","Res cogitans","Intuizione","Performatività","Ordine delle ragioni"],argument:"Il tentativo presente di negare la propria esistenza si autoconfuta perché compie l’atto che la rende certa. La portata temporale e metafisica della conclusione deve però essere delimitata.",source:"Meditazioni II, AT VII 25–29; Discorso, parte IV; SEP, Descartes’ Epistemology §5.",warning:"«Penso, dunque sono» non autorizza da solo un io biografico completo, immortale o separato dal corpo."},check:{question:"Che cosa è già certo nel cogito?",options:["L’esistenza del corpo","L’esistenza attuale del pensante mentre pensa","L’esistenza degli altri"],correct:1,feedback:"Il corpo e il mondo devono ancora essere ricostruiti.",recovery:"Segui l’ordine: prima l’atto, poi ciò che si potrà giustificare oltre l’atto."}},
    {id:"idee",number:"07",accent:"#ad7b61",kicker:"Criterio ed errore",title:"Idee, chiarezza e distinzione",question:"Come passare dalla certezza del cogito a un criterio generale?",amateur:{summary:"Cartesio esamina le idee e distingue ciò che sembra provenire dall’esterno, ciò che costruiamo e ciò che appartiene alla struttura della mente. L’errore nasce quando la volontà giudica oltre ciò che l’intelletto vede chiaramente.",narrative:"L’idea, in quanto modo del pensiero, esiste certamente; resta da stabilire se rappresenti qualcosa fuori di noi. Cartesio distingue idee avventizie, fattizie e innate, ma la classificazione riguarda l’origine presunta e la funzione. Una percezione è chiara quando è presente e manifesta, distinta quando separa ciò che le appartiene da ciò che non le appartiene.",beats:["Le idee sono modi del pensiero.","Il contenuto rappresentativo pone il problema della causa.","Chiarezza non equivale a vivacità sensibile.","La volontà può oltrepassare l’intelletto e produrre errore."],example:"Una foto nitida non rende vera una notizia: la chiarezza cartesiana è intellettuale e richiede distinzione del contenuto.",checkpoint:"L’errore non è una facoltà positiva creata da Dio, ma un uso precipitato del giudizio."},student:{summary:"La teoria distingue realtà formale dell’idea come modo e realtà oggettiva del suo contenuto rappresentativo.",concepts:["Idea innata","Idea avventizia","Idea fattizia","Chiarezza e distinzione","Intelletto e volontà"],argument:"L’intelletto finito presenta contenuti; la volontà, più ampia, concede o nega l’assenso. L’errore compare quando l’assenso non è limitato alla percezione chiara e distinta.",source:"Meditazioni III–IV; Principi I.45–46; SEP, Descartes’ Theory of Ideas.",warning:"La tripartizione non è un inventario psicologico rigido: Cartesio problematizza proprio l’apparenza che un’idea venga dall’esterno."},check:{question:"Quando nasce l’errore?",options:["Quando la volontà giudica oltre ciò che l’intelletto comprende","Quando possediamo idee innate","Quando sospendiamo l’assenso"],correct:0,feedback:"La precipitazione del giudizio oltre la comprensione produce l’errore.",recovery:"Distingui ciò che l’intelletto presenta da ciò a cui la volontà assente."}},
    {id:"dio",number:"08",accent:"#b19355",kicker:"Garanzia e circolo",title:"Dio, veracità e problema cartesiano",question:"La dimostrazione di Dio fonda il criterio oppure lo presuppone?",amateur:{summary:"Cartesio usa l’idea di infinito e l’argomento ontologico per dimostrare un Dio perfetto e non ingannatore. Proprio qui nasce l’accusa di circolarità.",narrative:"Un essere finito, sostiene Cartesio, non sembra causa sufficiente dell’idea di perfezione infinita; inoltre l’esistenza viene collegata all’essenza dell’essere sommamente perfetto. Se Dio non inganna, ciò che percepiamo chiaramente e distintamente può essere garantito oltre il momento dell’intuizione. Arnauld obietta: le prove usano idee chiare e distinte prima che Dio ne assicuri l’affidabilità.",beats:["Il cogito non basta a recuperare il mondo.","L’idea di infinito sostiene una prova causale.","La Quinta Meditazione propone l’argomento ontologico.","La veracità divina fonda la memoria delle evidenze.","L’accusa di circolo resta una questione interpretativa."],example:"Se un certificato garantisce il controllore, ma il controllore è l’unico a garantire il certificato, devi chiarire quale affidabilità possiedi prima del circolo.",checkpoint:"La funzione di Dio è strutturale; la sua riuscita non va presentata come incontestata."},student:{summary:"Le risposte al circolo distinguono spesso evidenza presente e affidabilità generale di ciò che è ricordato come chiaramente percepito.",concepts:["Prova causale","Idea di infinito","Argomento ontologico","Veracità divina","Circolo cartesiano"],argument:"L’idea di Dio possiede una realtà oggettiva che, secondo il principio causale, richiede una causa formalmente adeguata. La garanzia divina estende la certezza; resta controverso se la prova possa procedere senza presupporla.",source:"Meditazioni III–V; Obiezioni IV; SEP, Descartes’ Epistemology §6; SEP, Descartes’ Ontological Argument.",warning:"Non presentare il circolo come un errore liquidato né come una confutazione automaticamente decisiva: esistono letture accademiche concorrenti."},check:{question:"Qual è l’accusa del circolo cartesiano?",options:["Dio viene dimostrato con i sensi","Le idee chiare provano Dio e Dio garantisce le idee chiare","Il cogito dipende dalla fisica"],correct:1,feedback:"Il problema riguarda l’ordine della giustificazione.",recovery:"Individua i due versi della garanzia: evidenza verso Dio, Dio verso evidenza."}},
    {id:"sostanze",number:"09",accent:"#6f8b92",kicker:"Nuova natura",title:"Res cogitans e res extensa",question:"Perché separare pensiero ed estensione aiuta la fisica e complica l’uomo?",amateur:{summary:"La mente è definita dal pensiero, il corpo dall’estensione. La separazione rende la natura descrivibile geometricamente, ma apre il problema dell’unione.",narrative:"La materia cartesiana non possiede fini, forme sostanziali o qualità mentali: è estensione divisibile regolata dal movimento. La mente è inestesa e pensante. Questa distinzione sostiene una fisica meccanica e una spiegazione automatica di molti comportamenti animali. Tuttavia Cartesio non considera l’essere umano una mente che osserva da lontano una macchina: fame, dolore e passioni attestano un’unione stretta.",beats:["Pensiero è l’attributo principale della mente.","Estensione è l’attributo principale del corpo.","La fisica esclude finalità e qualità mentali dalla materia.","La distinzione reale non cancella l’esperienza dell’unione."],example:"Una mappa geometrica descrive posizione e movimento, ma non contiene il dolore di chi attraversa quel territorio.",checkpoint:"Il dualismo fonda una nuova fisica e insieme produce una nuova difficoltà antropologica."},student:{summary:"La real distinction dipende dalla concepibilità chiara e distinta di mente e corpo come sostanze create differenti.",concepts:["Sostanza","Attributo","Res cogitans","Res extensa","Meccanicismo"],argument:"Ciò che è chiaramente concepibile separatamente può, per la potenza divina, esistere separatamente. L’argomento è forte entro il quadro cartesiano, ma dipende dalla garanzia delle idee chiare e distinte.",source:"Meditazioni VI; Principi I.51–65; IEP, Descartes: Mind-Body Distinction.",warning:"Non attribuire a Cartesio la moderna distinzione lockiana fra qualità primarie e secondarie senza precisazioni; il suo lessico e il suo sistema sono diversi."},check:{question:"Che cosa definisce la res extensa?",options:["Il pensiero","L’estensione divisibile","La libertà"],correct:1,feedback:"La materia è concepita geometricamente come estensione.",recovery:"Associa res cogitans a pensiero e res extensa a estensione."}},
    {id:"unione",number:"10",accent:"#9a6f76",kicker:"Mente e corpo",title:"Elisabetta e la difficoltà dell’interazione",question:"Come può ciò che non è esteso muovere un corpo esteso?",amateur:{summary:"Elisabetta di Boemia formula con precisione la difficoltà: ogni causalità fisica sembra richiedere contatto, ma la mente non ha superficie. Cartesio risponde richiamando la nozione vissuta di unione.",narrative:"Nella corrispondenza del 1643 Elisabetta non svolge il ruolo di semplice allieva: costringe Cartesio a chiarire ciò che le Meditazioni lasciano problematico. Egli distingue nozioni primitive di mente, corpo e unione. La ghiandola pineale è il luogo corporeo privilegiato nella fisiologia delle passioni, non una spiegazione magica capace da sola di risolvere l’eterogeneità delle sostanze.",beats:["Elisabetta chiede una spiegazione causale.","Cartesio distingue pensiero, estensione e unione.","L’esperienza quotidiana attesta l’unione sostanziale.","La pineale localizza una funzione corporea, non elimina il problema metafisico."],example:"Indicare il punto in cui due sistemi si incontrano non spiega ancora come possano scambiarsi causalità se sono definiti incompatibili.",checkpoint:"Il problema mente-corpo nasce dentro il sistema e viene riconosciuto dai contemporanei."},student:{summary:"La storiografia discute se l’unione cartesiana debba essere letta meccanicamente, come terza nozione primitiva o attraverso categorie scolastiche residue.",concepts:["Unione sostanziale","Nozione primitiva","Interazione","Ghiandola pineale","Elisabetta di Boemia"],argument:"La distinzione reale sembra rendere inintelligibile l’interazione; Cartesio nega che la diversità delle nature la renda impossibile e rinvia alla nozione dell’unione conosciuta nella vita ordinaria.",source:"Lettere a Elisabetta, maggio–giugno 1643; Meditazioni VI; SEP, Elisabeth of Bohemia §4; IEP, Mind-Body Distinction §§4–5.",warning:"La formula «fantasma nella macchina» è di Ryle e appartiene al XX secolo; non riassume neutralmente la posizione di Cartesio."},check:{question:"Che cosa mostra la domanda di Elisabetta?",options:["Che Cartesio ignorava l’esistenza del corpo","Che la distinzione delle sostanze rende difficile spiegare la causalità reciproca","Che la pineale è immateriale"],correct:1,feedback:"Il problema nasce dall’eterogeneità fra pensiero inesteso ed estensione.",recovery:"Distingui localizzare una funzione dal rendere intelligibile la causalità."}},
    {id:"passioni",number:"11",accent:"#b47b58",kicker:"Uomo concreto",title:"Passioni, libertà e generosità",question:"Il razionalista Cartesio vuole eliminare le emozioni?",amateur:{summary:"Le passioni sono eventi dell’unione di anima e corpo: orientano l’azione e possono essere educate, non cancellate. La generosità nasce dal retto uso della libertà.",narrative:"Nelle Passioni dell’anima Cartesio descrive meraviglia, amore, odio, desiderio, gioia e tristezza come passioni fondamentali. Il corpo ha un ruolo decisivo e molte risposte avvengono senza deliberazione razionale. La saggezza non consiste nel non sentire, ma nel comprendere i meccanismi, modificare abitudini e usare bene la volontà.",beats:["Le passioni dipendono dall’unione.","Hanno una funzione di orientamento.","Possono essere eccessive o mal dirette.","La volontà può formare abitudini.","La generosità riconosce la responsabilità del libero uso di sé."],example:"La paura prepara il corpo prima che un ragionamento sia concluso; educarla significa regolare risposta e giudizio, non negare il segnale.",checkpoint:"Cartesio non è il teorico di una mente pura indifferente al corpo."},student:{summary:"L’etica matura collega sommo bene, virtù, libertà e regolazione delle passioni nel quadro dell’unione mente-corpo.",concepts:["Passione","Spiriti animali","Libero arbitrio","Virtù","Generosità"],argument:"Le passioni sono percezioni riferite all’anima e causate da movimenti corporei; la volontà non le sopprime direttamente, ma può opporre giudizi e abitudini che ne trasformano il corso.",source:"Le passioni dell’anima §§27–50, 153; SEP, Descartes’ Ethics; SEP, Descartes on the Emotions.",warning:"La caricatura di un Cartesio nemico delle emozioni ignora il ruolo centrale del corpo nelle Passioni e nella Sesta Meditazione."},check:{question:"Qual è il compito etico verso le passioni?",options:["Cancellarle","Comprenderle e regolarle mediante giudizi e abitudini","Affidarsi sempre al primo impulso"],correct:1,feedback:"Le passioni sono utili ma richiedono governo.",recovery:"Distingui soppressione, comprensione e regolazione."}},
    {id:"eredita",number:"12",accent:"#7d7a9b",kicker:"Conseguenze",title:"Il nuovo inizio e i problemi lasciati aperti",question:"Cartesio ha risolto lo scetticismo o gli ha dato una forma nuova?",amateur:{summary:"Il soggetto diventa punto iniziale della certezza, la natura viene matematizzata e il dualismo ridisegna l’uomo. I successori lavorano tanto con Cartesio quanto contro di lui.",narrative:"Spinoza sostituisce le due sostanze create con un’unica sostanza; Leibniz ripensa sostanza e armonia; Locke critica le idee innate; Berkeley elimina la materia; Hume radicalizza la critica del soggetto e della causalità; Kant accetta la svolta sul soggetto ma ridefinisce le condizioni dell’esperienza. Non esiste una linea retta: ogni autore seleziona, trasforma e contesta.",beats:["Il metodo diventa modello di razionalità.","Il cogito inaugura una filosofia della soggettività.","Il meccanicismo trasforma la scienza della natura.","Il dualismo apre il problema mente-corpo.","La garanzia divina e il circolo restano contestati."],example:"Una risposta filosofica è grande anche quando rende impossibile tornare alle vecchie domande nello stesso modo.",checkpoint:"L’eredità cartesiana è una rete di trasformazioni, non una scuola uniforme."},student:{summary:"La formula «padre della filosofia moderna» è utile solo se non cancella precedenti, alternative e rotture interne alla ricezione.",concepts:["Razionalismo","Soggettività","Occasionalismo","Monismo","Idealismo trascendentale"],argument:"Cartesio ridefinisce l’ordine della giustificazione a partire dal soggetto; le aporie su Dio, mondo e corpo diventano programmi di ricerca per razionalisti, empiristi e Kant.",source:"SEP, René Descartes §§3–8; SEP, Continental Rationalism; IEP, René Descartes §7.",warning:"Non affermare che Cartesio causi automaticamente idealismo e scetticismo: l’influenza è mediata da critiche e nuove costruzioni."},check:{question:"Come va compresa l’eredità cartesiana?",options:["Come ripetizione fedele del sistema","Come trasformazione e critica di problemi nuovi","Come rifiuto universale del cogito"],correct:1,feedback:"I successori accolgono, modificano o rifiutano parti diverse.",recovery:"Sostituisci la genealogia lineare con operazioni: assumere, trasformare, contestare."}}
  ],
  doubtCases:[
    {symbol:"◐",title:"La torre lontana",scene:"Da lontano una torre appare rotonda, da vicino quadrata.",question:"Quale classificazione è più precisa?",options:["Indubitabile","Dubitabile: i sensi talvolta ingannano","Certamente falsa"],correct:1,explanation:"Il caso basta a sospendere l’assolutezza della testimonianza sensibile, non a dichiarare falsa ogni percezione."},
    {symbol:"☾",title:"Il fuoco sognato",scene:"Nel sogno credi di scaldarti accanto a un fuoco.",question:"Che cosa viene colpito?",options:["La scena corporea presente","Ogni verità logica","Soltanto la memoria"],correct:0,explanation:"L’argomento del sogno mette in dubbio che l’esperienza presente provenga davvero da oggetti esterni."},
    {symbol:"2+3",title:"Il calcolo",scene:"Anche nel sogno due più tre sembra fare cinque.",question:"Che cosa serve per sospendere anche questa evidenza?",options:["Un secondo sogno","L’ipotesi del genio maligno","Un errore dei sensi"],correct:1,explanation:"Il genio maligno radicalizza l’inganno fino alle operazioni razionali; non prova che il calcolo sia falso."},
    {symbol:"?",title:"Sono ingannato",scene:"Supponi che ogni contenuto del pensiero sia prodotto da un ingannatore.",question:"Che cosa resiste?",options:["Il mio corpo","Il mondo","L’esistenza del pensante mentre è ingannato"],correct:2,explanation:"L’inganno richiede che esista qualcuno che viene ingannato: emerge il cogito."},
    {symbol:"◉",title:"Sento dolore",scene:"Mentre tutto è sospeso, avverti dolore.",question:"Che cosa è immediatamente certo?",options:["Che il corpo esterno è esattamente come appare","Che esiste il sentire come modo del pensiero","Che il dolore è falso"],correct:1,explanation:"È certo l’atto cosciente del sentire; l’esistenza e la natura del corpo devono ancora essere dimostrate."},
    {symbol:"⌂",title:"La ricostruzione",scene:"Dal cogito vuoi tornare al mondo.",question:"Il cogito da solo basta?",options:["Sì, contiene già tutto","No, occorrono ulteriori argomenti","No, quindi Cartesio rinuncia"],correct:1,explanation:"Il cogito è il primo fondamento, non l’intero edificio. Seguono teoria delle idee, Dio e mondo materiale."}
  ],
  methodSequence:[
    {id:"evidence",label:"Evidenza",short:"Accogli soltanto ciò che è chiaro e distinto.",application:"Definisci il problema senza presupporre già la risposta."},
    {id:"analysis",label:"Analisi",short:"Dividi la difficoltà in parti trattabili.",application:"Separa fonti, concetti, inferenze e dati."},
    {id:"synthesis",label:"Sintesi",short:"Procedi dal semplice al complesso.",application:"Ricostruisci la soluzione concatenando i passaggi."},
    {id:"review",label:"Enumerazione",short:"Controlla completezza e omissioni.",application:"Rivedi casi contrari, passaggi e risultati."}
  ],
  sources:[
    {kind:"Fonte primaria",title:"Discorso sul metodo",text:"Le parti II e III espongono le quattro regole e la morale provvisoria; la parte IV presenta il cogito in una forma diversa dalle Meditazioni.",ref:"Discours de la méthode, 1637, parti II–IV"},
    {kind:"Fonte primaria",title:"Meditazioni I–II",text:"Il lettore attraversa sensi, sogno e genio maligno fino alla certezza dell’io esistente e al celebre esame della cera.",ref:"Meditationes de prima philosophia, 1641, I–II"},
    {kind:"Fonte primaria",title:"Meditazioni III–V",text:"Idee, prove di Dio, errore e argomento ontologico costruiscono la garanzia metafisica della conoscenza.",ref:"Meditationes, III–V"},
    {kind:"Fonte primaria",title:"Meditazione VI",text:"La distinzione reale fra mente e corpo convive con l’affermazione della loro unione stretta nell’essere umano.",ref:"Meditationes, VI"},
    {kind:"Fonte primaria",title:"Le lettere a Elisabetta",text:"La principessa interroga l’interazione causale e costringe Cartesio a esplicitare la nozione primitiva dell’unione.",ref:"Corrispondenza del 1643–1645"},
    {kind:"Fonte primaria",title:"Le passioni dell’anima",text:"Il corpo e le passioni hanno un ruolo strutturale; la generosità orienta il buon uso della libertà.",ref:"Les Passions de l’âme, 1649"},
    {kind:"Interpretazione",title:"Il metodo e l’esperimento",text:"La ricerca accademica corregge l’immagine di un Cartesio puramente deduttivo: l’esperimento discrimina spiegazioni fisiche compatibili con i principi.",ref:"SEP, Descartes’ Method; IEP, Scientific Method"},
    {kind:"Obiezione",title:"Il circolo cartesiano",text:"Arnauld contesta l’uso delle idee chiare e distinte nelle prove di Dio prima della garanzia divina. Le risposte distinguono evidenza presente e memoria.",ref:"Quarte Obiezioni; SEP, Descartes’ Epistemology §6"},
    {kind:"Problema aperto",title:"L’unione mente-corpo",text:"Localizzare funzioni nella pineale non esaurisce la questione di come sostanze eterogenee possano interagire. La storiografia propone letture concorrenti.",ref:"IEP, Mind-Body Distinction §§4–5"}
  ],
  comics:[
    {year:"1596–1616",icon:"▥",title:"Formazione",text:"Nasce a La Haye, studia al collegio gesuita di La Flèche e consegue il diritto a Poitiers.",status:"Documentato"},
    {year:"1618",icon:"⌁",title:"Beeckman",text:"A Breda l’incontro con Isaac Beeckman rilancia il progetto di una scienza matematica della natura.",status:"Documentato"},
    {year:"1619",icon:"✦",title:"I sogni",text:"La tradizione biografica collega tre sogni al progetto di una scienza mirabile e universale.",status:"Testimonianza posteriore da trattare con cautela"},
    {year:"1628–1629",icon:"⌂",title:"I Paesi Bassi",text:"Si stabilisce nei Paesi Bassi, dove svilupperà gran parte del proprio sistema.",status:"Documentato"},
    {year:"1633–1637",icon:"◒",title:"Galileo e il Discorso",text:"Dopo la condanna di Galileo sospende Il Mondo; nel 1637 pubblica in francese il Discorso e tre saggi.",status:"Documentato"},
    {year:"1641–1644",icon:"◇",title:"Meditazioni e Principi",text:"Pubblica le Meditazioni con Obiezioni e Risposte, poi l’esposizione sistematica dei Principi.",status:"Documentato"},
    {year:"1643–1649",icon:"↔",title:"Elisabetta",text:"La corrispondenza su mente, corpo, passioni e libertà modifica e approfondisce l’agenda cartesiana.",status:"Documentato"},
    {year:"1649–1650",icon:"❄",title:"Stoccolma",text:"Accetta l’invito di Cristina di Svezia e muore a Stoccolma l’11 febbraio 1650.",status:"Documentato; le cause esatte sono discusse"}
  ],
  maps:[
    {id:"doubt",title:"Dal dubbio al cogito",intro:"La demolizione procede per livelli e trova resistenza nell’atto.",nodes:[{title:"Sensi",text:"Talvolta ingannano: credenze sensibili non assolute."},{title:"Sogno",text:"La scena corporea presente può essere sospesa."},{title:"Genio maligno",text:"Anche le evidenze razionali sono sottoposte a pressione."},{title:"Cogito",text:"L’inganno conferma l’esistenza attuale del pensante."}]},
    {id:"method",title:"Il metodo",intro:"Quattro responsabilità per costruire senza salti.",nodes:[{title:"Evidenza",text:"Non precipitare l’assenso."},{title:"Analisi",text:"Dividere la difficoltà."},{title:"Sintesi",text:"Ordinare dal semplice al complesso."},{title:"Enumerazione",text:"Controllare omissioni e catena."}]},
    {id:"ideas",title:"Idee e verità",intro:"Dal modo del pensiero alla garanzia del contenuto.",nodes:[{title:"Idee",text:"Innate, avventizie, fattizie: classificazione problematica."},{title:"Chiarezza",text:"Presenza manifesta alla mente."},{title:"Distinzione",text:"Separazione precisa da ciò che non appartiene."},{title:"Dio",text:"Garanzia della regola; nasce il problema del circolo."}]},
    {id:"substances",title:"Le sostanze",intro:"La nuova fisica dipende da una separazione metafisica.",nodes:[{title:"Res cogitans",text:"Pensante, inestesa, indivisibile."},{title:"Res extensa",text:"Estesa, divisibile, meccanicamente determinata."},{title:"Distinzione reale",text:"Concepibilità separata e potenza divina."},{title:"Unione",text:"L’essere umano sperimenta un intreccio stretto."}]},
    {id:"union",title:"Mente, corpo, unione",intro:"Tre nozioni primitive, non una semplice freccia causale.",nodes:[{title:"Pensiero",text:"Compreso dall’intelletto."},{title:"Estensione",text:"Compresa da matematica e immaginazione."},{title:"Unione",text:"Conosciuta nella vita e nelle passioni."},{title:"Problema",text:"Elisabetta chiede come sia possibile l’interazione."}]},
    {id:"legacy",title:"Sistema ed eredità",intro:"Ogni soluzione apre una nuova linea di critica.",nodes:[{title:"Cogito",text:"Centralità epistemica del soggetto."},{title:"Dio",text:"Garanzia contestata della conoscenza."},{title:"Meccanicismo",text:"Natura matematizzata."},{title:"Successori",text:"Monismo, armonia, empirismo e critica trascendentale."}]}
  ],
  glossary:[
    ["Analisi","Divisione di una difficoltà nelle parti necessarie alla soluzione."],["Argomento del sogno","Ipotesi che sospende la certezza dell’esperienza corporea presente."],["Avventizia","Idea che sembra provenire da cose esterne; la provenienza deve essere dimostrata."],["Chiarezza","Presenza manifesta di un contenuto alla mente attenta."],["Circolo cartesiano","Accusa secondo cui le prove di Dio usano il criterio che Dio dovrebbe garantire."],["Cogitatio","Pensiero in senso ampio: dubitare, comprendere, volere, immaginare, sentire."],["Cogito","Certezza dell’esistenza del pensante colta nell’atto del pensiero."],["Deduzione","Passaggio necessario da elementi conosciuti ad altri connessi."],["Distinzione","Precisione con cui un’idea esclude ciò che non le appartiene."],["Dubbio iperbolico","Radicalizzazione artificiale del dubbio fino alle evidenze razionali."],["Dubbio metodico","Sospensione finalizzata a trovare un fondamento, non scetticismo definitivo."],["Enumerazione","Revisione completa dei passaggi per evitare omissioni."],["Evidenza","Ciò che si presenta con chiarezza e distinzione senza precipitazione."],["Fattizia","Idea composta o costruita dalla mente."],["Genio maligno","Ipotesi meditativa di un ingannatore potentissimo."],["Generosità","Virtù fondata sulla coscienza del libero uso della volontà."],["Idea innata","Contenuto o disposizione che non deriva semplicemente dai sensi."],["Intuitus","Atto intellettuale semplice con cui la mente coglie un contenuto evidente."],["Mathesis universalis","Ideale di una scienza generale dell’ordine e della misura."],["Meccanicismo","Spiegazione dei corpi mediante estensione, figura e movimento."],["Morale provvisoria","Massime pratiche adottate mentre la ricerca teorica è in corso."],["Nozione primitiva","Concetto originario: pensiero, estensione e unione richiedono accessi differenti."],["Passione","Percezione o emozione dell’anima legata ai movimenti corporei."],["Res cogitans","Sostanza creata il cui attributo principale è il pensiero."],["Res extensa","Sostanza corporea il cui attributo principale è l’estensione."],["Sostanza","Ciò che esiste con il concorso di Dio senza dipendere da un’altra sostanza creata."],["Sintesi","Ricostruzione ordinata dal semplice al complesso."],["Volontà","Facoltà di affermare o negare; produce errore quando oltrepassa l’intelletto."]
  ],
  timeline:[
    ["1596","Nasce il 31 marzo a La Haye en Touraine."],["1607 circa","Entra nel collegio gesuita di La Flèche."],["1616","Consegue laurea e licenza in diritto a Poitiers."],["1618","A Breda incontra Isaac Beeckman."],["1619","Episodio dei sogni e progetto della scientia mirabilis, noto da fonti posteriori."],["1628–1629","Si stabilisce nei Paesi Bassi."],["1633","La condanna di Galileo lo induce a non pubblicare Il Mondo."],["1637","Pubblica il Discorso sul metodo con Diottrica, Meteore e Geometria."],["1641","Pubblica le Meditazioni metafisiche con Obiezioni e Risposte."],["1643","Inizia la corrispondenza filosofica con Elisabetta di Boemia."],["1644","Pubblica i Principi della filosofia."],["1649","Pubblica Le passioni dell’anima e si trasferisce in Svezia."],["1650","Muore a Stoccolma l’11 febbraio."],["1663","Opere cartesiane vengono inserite nell’Indice romano dei libri proibiti."]
  ],
  library:[
    ["Regulae ad directionem ingenii","composte circa 1619–1628; postume 1701","Progetto incompiuto su intuizione, deduzione, ordine e mathesis universalis."],["Le Monde e L’Homme","composti 1629–1633; postumi","Fisica cosmologica e fisiologia meccanicistica non pubblicate dopo Galileo."],["Discours de la méthode","1637","Autobiografia intellettuale, quattro regole, morale provvisoria e cogito."],["Essais: Dioptrique, Météores, Géométrie","1637","Applicazioni scientifiche pubblicate con il Discorso."],["Meditationes de prima philosophia","1641; edizione ampliata 1642","Dubbio, cogito, Dio, errore, materia e distinzione mente-corpo."],["Principia philosophiae","1644","Esposizione sistematica di metafisica e filosofia naturale."],["Les Passions de l’âme","1649","Fisiologia delle passioni, unione mente-corpo, libertà e generosità."],["Correspondance avec Élisabeth","1643–1649","Interazione, unione, passioni, virtù, libertà e politica."]
  ],
  comparisons:[
    {thinker:"Bacone",problem:"Come riformare il sapere?",move:"Esperienza organizzata, induzione, critica degli idoli.",limit:"Cartesio privilegia ordine razionale e deduzione, pur usando esperimenti."},
    {thinker:"Spinoza",problem:"Quante sostanze?",move:"Un’unica sostanza: Dio o Natura.",limit:"Rifiuta il dualismo delle sostanze create."},
    {thinker:"Leibniz",problem:"Come coordinare anima e corpo?",move:"Monadi e armonia prestabilita.",limit:"Nega interazione causale diretta fra sostanze."},
    {thinker:"Locke",problem:"Da dove vengono le idee?",move:"Esperienza e riflessione; critica delle idee innate.",limit:"Respinge l’innatismo cartesiano in senso forte."},
    {thinker:"Berkeley",problem:"Che cos’è il corpo?",move:"Elimina la sostanza materiale indipendente dalla mente.",limit:"Trasforma radicalmente il rapporto fra idee e realtà."},
    {thinker:"Hume",problem:"Che cosa troviamo nell’io?",move:"Fascio di percezioni, non sostanza intuita.",limit:"Radicalizza la critica empirista al soggetto e alla causalità."},
    {thinker:"Kant",problem:"Come sono possibili esperienza e scienza?",move:"Il soggetto fornisce forme e categorie dell’esperienza.",limit:"Rifiuta di conoscere anima, mondo e Dio come sostanze mediante ragione teoretica."}
  ],
  quiz:[
    {q:"Qual è la funzione del dubbio metodico?",options:["Dimostrare che tutto è falso","Escludere dal fondamento ciò che non è indubitabile","Sostituire la scienza con lo scetticismo"],correct:1,why:["Il dubitabile viene trattato provvisoriamente come falso, non confutato.","Esatto: il dubbio collauda i candidati al fondamento.","Il fine è costruttivo."],module:"dubbio"},
    {q:"Perché il genio maligno viene introdotto?",options:["Per sospendere anche le evidenze razionali","Per spiegare il male morale","Per dimostrare l’esistenza del diavolo"],correct:0,why:["Esatto: radicalizza l’ipotesi d’inganno.","Non è una teodicea.","È un artificio meditativo, non una prova teologica."],module:"dubbio"},
    {q:"Che cosa rende certo il cogito?",options:["Una lunga deduzione","L’autoconferma dell’atto di pensare","La percezione del corpo"],correct:1,why:["La lettura sillogistica è respinta dal testo.","Esatto: negarlo significa compierlo.","Il corpo è ancora sospeso."],module:"cogito"},
    {q:"Qual è l’ordine delle quattro regole?",options:["Analisi, evidenza, enumerazione, sintesi","Evidenza, analisi, sintesi, enumerazione","Sintesi, dubbio, analisi, esperienza"],correct:1,why:["L’assenso viene prima della divisione.","Esatto: accogliere, dividere, ordinare, controllare.","Dubbio ed esperienza non sono le quattro regole."],module:"metodo"},
    {q:"Quando nasce l’errore secondo la Quarta Meditazione?",options:["Quando la volontà giudica oltre l’intelletto","Quando l’intelletto è finito","Quando sospendiamo l’assenso"],correct:0,why:["Esatto: la volontà oltrepassa ciò che è compreso.","La finitezza non è di per sé errore.","La sospensione evita il giudizio precipitoso."],module:"idee"},
    {q:"Qual è il problema del circolo cartesiano?",options:["Il cogito usa i sensi","Dio garantisce idee usate per dimostrare Dio","La materia dimostra la mente"],correct:1,why:["Il cogito non dipende dai sensi.","Esatto: è l’obiezione sulla reciproca garanzia.","Non è la struttura delle prove."],module:"dio"},
    {q:"Che cosa definisce la res cogitans?",options:["Estensione","Pensiero","Movimento"],correct:1,why:["L’estensione definisce il corpo.","Esatto: cogitatio è l’attributo principale.","Il movimento è modo della materia."],module:"sostanze"},
    {q:"Perché il dualismo favorisce la fisica meccanicistica?",options:["Elimina ogni matematica","Separa dalla materia finalità e proprietà mentali","Dimostra che gli animali non esistono"],correct:1,why:["La matematica diventa centrale.","Esatto: il corpo è estensione e movimento.","Cartesio propone spiegazioni automatiche, non inesistenza."],module:"sostanze"},
    {q:"Che cosa obietta Elisabetta?",options:["Che la mente non pensa","Che è oscuro come una mente inestesa muova un corpo","Che il corpo non possiede organi"],correct:1,why:["Il pensiero definisce la mente.","Esatto: chiede intelligibilità causale.","La sua obiezione non è anatomica."],module:"unione"},
    {q:"Quale affermazione sulle passioni è corretta?",options:["Cartesio vuole eliminarle","Sono eventi dell’unione e possono essere regolate","Sono idee chiare e distinte di Dio"],correct:1,why:["La soppressione è una caricatura.","Esatto: hanno funzione corporea e pratica.","Non hanno quella funzione metafisica."],module:"passioni"},
    {q:"Perché la morale è detta provvisoria?",options:["Perché guida l’azione mentre la teoria viene rifondata","Perché non conta nella vita","Perché dura un solo giorno"],correct:0,why:["Esatto: l’azione non può essere sospesa.","È necessaria proprio per vivere.","Provvisoria non indica una durata letterale."],module:"morale"},
    {q:"Come va descritta l’eredità di Cartesio?",options:["Come ripetizione uniforme","Come rete di appropriazioni, trasformazioni e critiche","Come irrilevante dopo il 1650"],correct:1,why:["Spinoza, Leibniz ed empiristi non ripetono il sistema.","Esatto: ogni autore riorganizza problemi cartesiani.","Il problema mente-corpo resta attuale."],module:"eredita"}
  ],
  academicSources:[
    {institution:"Stanford University",title:"René Descartes — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/descartes/",supports:"Quadro generale: opere, metafisica, natura, mente-corpo, passioni e ricezione."},
    {institution:"Stanford University",title:"Descartes’ Life and Works",url:"https://plato.stanford.edu/entries/descartes-works/",supports:"Cronologia documentata, La Flèche, Beeckman, Galileo, opere e ultimi anni."},
    {institution:"Stanford University",title:"Descartes’ Method",url:"https://plato.stanford.edu/entries/descartes-method/",supports:"Regulae, quattro regole, analisi, sintesi e ruolo dell’esperimento."},
    {institution:"Stanford University",title:"Descartes’ Epistemology",url:"https://plato.stanford.edu/entries/descartes-epistemology/",supports:"Dubbio, cogito, chiarezza e distinzione, Dio, circolo e mondo esterno."},
    {institution:"Stanford University",title:"Descartes’ Theory of Ideas",url:"https://plato.stanford.edu/entries/descartes-ideas/",supports:"Natura delle idee, realtà formale e oggettiva, origine e rappresentazione."},
    {institution:"Stanford University",title:"Elisabeth, Princess of Bohemia",url:"https://plato.stanford.edu/entries/elisabeth-bohemia/",supports:"Corrispondenza, interazione mente-corpo, passioni, libertà e autonomia filosofica di Elisabetta."},
    {institution:"University of Tennessee at Martin",title:"René Descartes — Internet Encyclopedia of Philosophy",url:"https://iep.utm.edu/rene-descartes/",supports:"Biografia, metodo del dubbio, metafisica, fisica, mente-corpo ed eredità."},
    {institution:"University of Tennessee at Martin",title:"Descartes: Scientific Method",url:"https://iep.utm.edu/descartes-scientific-method/",supports:"Metodo scientifico, matematica, dubbio e rapporto fra ragione ed esperienza."},
    {institution:"University of Tennessee at Martin",title:"Descartes: Mind-Body Distinction",url:"https://iep.utm.edu/descartes-mind-body-distinction-dualism/",supports:"Distinzione reale, motivazione scientifica, interazione e letture dell’unione."},
    {institution:"Wright State University",title:"Descartes’ Meditations — Trilingual Edition",url:"https://corescholar.libraries.wright.edu/philosophy/8/",supports:"Edizione accademica inglese, latina e francese delle Meditazioni."},
    {institution:"Boston University",title:"Meditations on First Philosophy — Complete Text",url:"https://people.bu.edu/wwildman/courses/wphil/readings/wphil_rdg21_meditations_entire.htm",supports:"Testo integrale delle sei Meditazioni per il controllo dei passaggi primari."},
    {institution:"Università Bocconi",title:"René Descartes — MATEpristem",url:"https://matematica.unibocconi.eu/matematici/rene-descartes",supports:"Profilo matematico, geometria analitica e rapporto fra matematica e filosofia."}
  ]
};

