const EVENTS=window.TIMELINE_EVENTS||[],PERIODS=window.TIMELINE_PERIODS||[];
const MAX_YEAR=435,MIN_YEAR=315,BASE_WIDTH=2600;
const eventsLayer=document.querySelector('#eventsLayer'),axis=document.querySelector('#axis'),viewport=document.querySelector('#viewport'),world=document.querySelector('#timelineWorld'),listView=document.querySelector('#listView'),parallelView=document.querySelector('#parallelView'),search=document.querySelector('#search'),laneFilters=document.querySelector('#laneFilters'),typeFilters=document.querySelector('#typeFilters'),periodButtons=document.querySelector('#periodButtons'),status=document.querySelector('#status'),reader=document.querySelector('#reader'),readerDate=document.querySelector('#readerDate'),readerLane=document.querySelector('#readerLane'),readerType=document.querySelector('#readerType'),readerCertainty=document.querySelector('#readerCertainty'),readerTitle=document.querySelector('#readerTitle'),readerSummary=document.querySelector('#readerSummary'),readerMeaning=document.querySelector('#readerMeaning'),readerEvidence=document.querySelector('#readerEvidence'),readerWorks=document.querySelector('#readerWorks'),worksSection=document.querySelector('#worksSection'),readerSources=document.querySelector('#readerSources'),readerLinks=document.querySelector('#readerLinks'),prev=document.querySelector('#prev'),next=document.querySelector('#next'),toast=document.querySelector('#toast'),methodDialog=document.querySelector('#methodDialog');
let lane='tutti',type='tutti',query='',view='parallel',scale=1,currentId=null,currentList=[],timer;
const types=[...new Set(EVENTS.map(e=>e.type))].sort((a,b)=>a.localeCompare(b,'it'));
const laneNames={context:'Contesto storico',plato:'Platone',aristotle:'Aristotele'};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function say(t){clearTimeout(timer);toast.textContent=t;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2400)}
function pos(year){return((MAX_YEAR-year)/(MAX_YEAR-MIN_YEAR))*100}
function filtered(){const q=norm(query.trim());return EVENTS.filter(e=>(lane==='tutti'||e.lane===lane)&&(type==='tutti'||e.type===type)&&(!q||norm(JSON.stringify(e)).includes(q))).sort((a,b)=>b.year-a.year)}
function renderAxis(){let html='';for(let y=430;y>=320;y-=10)html+=`<span class="tickYear" style="left:${pos(y)}%">${y} a.C.</span>`;axis.innerHTML=html}
function eventTop(e){const laneTop={context:95,plato:315,aristotle:535}[e.lane];const above=e.row%2===0;return{top:above?laneTop+8:laneTop+125,above}}
function renderParallel(){const list=filtered();currentList=list.map(e=>e.id);eventsLayer.innerHTML=EVENTS.map(e=>{const visible=list.some(x=>x.id===e.id),p=eventTop(e);return`<button class="event ${e.lane} ${p.above?'above':'below'} ${visible?'':'dim'}" style="left:calc(80px + (100% - 120px) * ${pos(e.year)/100});top:${p.top}px" data-id="${e.id}"><div class="eventDate"><span>${esc(e.date)}</span><span class="certaintyDot" title="${esc(e.certainty)}"></span></div><h3>${esc(e.title)}</h3><small>${esc(e.type)}</small></button>`}).join('');status.textContent=`${list.length} eventi visibili`}
function renderList(){const list=filtered();currentList=list.map(e=>e.id);listView.innerHTML=list.map(e=>`<button class="listItem" data-id="${e.id}"><span class="date">${esc(e.date)}</span><span class="laneTag ${e.lane}">${laneNames[e.lane]}</span><div><h3>${esc(e.title)}</h3><small>${esc(e.type)} · ${esc(e.certainty)}</small></div><span class="arrow">→</span></button>`).join('')||'<p>Nessun evento corrisponde ai filtri.'}
function render(){renderParallel();renderList()}
function setScale(next){scale=Math.max(.65,Math.min(1.65,next));world.style.width=`${BASE_WIDTH*scale}px`;document.querySelector('#zoomReset').textContent=`${Math.round(scale*100)}%`}
function jumpYear(year){const x=(pos(year)/100)*(world.offsetWidth-120);viewport.scrollTo({left:Math.max(0,x-viewport.clientWidth/2),behavior:'smooth'});periodButtons.querySelectorAll('button').forEach(b=>b.classList.toggle('active',Number(b.dataset.year)===year))}
function openEvent(id){const e=EVENTS.find(x=>x.id===id);if(!e)return;currentId=id;const list=filtered();currentList=(list.length?list:EVENTS.slice().sort((a,b)=>b.year-a.year)).map(x=>x.id);readerDate.textContent=e.date;readerLane.textContent=laneNames[e.lane];readerType.textContent=e.type;readerCertainty.textContent=e.certainty;readerTitle.textContent=e.title;readerSummary.textContent=e.summary;readerMeaning.textContent=e.meaning;readerEvidence.textContent=e.evidence;readerWorks.innerHTML=(e.works||[]).map(x=>`<span>${esc(x)}</span>`).join('');worksSection.hidden=!(e.works||[]).length;readerSources.innerHTML=(e.sources||[]).map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener"><span>${esc(label)}</span><span>↗</span></a>`).join('');readerLinks.innerHTML=(e.links||[]).map(([label,url])=>`<a href="${url}"><span>${esc(label)}</span><span>→</span></a>`).join('')||'<p>Nessun rimando interno specifico.</p>';const i=currentList.indexOf(id);prev.disabled=i<=0;next.disabled=i<0||i>=currentList.length-1;reader.classList.add('open');reader.setAttribute('aria-hidden','false');document.body.classList.add('reader-open');reader.scrollTop=0;history.replaceState(null,'',`#${id}`)}
function closeReader(){reader.classList.remove('open');reader.setAttribute('aria-hidden','true');document.body.classList.remove('reader-open');history.replaceState(null,'',location.pathname+location.search)}
function move(delta){const i=currentList.indexOf(currentId),id=currentList[i+delta];if(id)openEvent(id)}
renderAxis();typeFilters.innerHTML=`<button class="active" data-type="tutti">Tutti i tipi</button>${types.map(t=>`<button data-type="${esc(t)}">${esc(t)}</button>`).join('')}`;periodButtons.innerHTML=PERIODS.map(p=>`<button data-year="${p.year}">${p.label} a.C.</button>`).join('');setScale(1);render();
laneFilters.addEventListener('click',ev=>{const b=ev.target.closest('[data-lane]');if(!b)return;lane=b.dataset.lane;laneFilters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()});typeFilters.addEventListener('click',ev=>{const b=ev.target.closest('[data-type]');if(!b)return;type=b.dataset.type;typeFilters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()});search.addEventListener('input',()=>{query=search.value;render()});document.querySelector('.viewSwitch').addEventListener('click',ev=>{const b=ev.target.closest('[data-view]');if(!b)return;view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));parallelView.hidden=view!=='parallel';listView.hidden=view!=='list'});periodButtons.addEventListener('click',ev=>{const b=ev.target.closest('[data-year]');if(b)jumpYear(Number(b.dataset.year))});document.querySelector('#fitBtn').addEventListener('click',()=>{setScale(Math.max(.65,(viewport.clientWidth-20)/BASE_WIDTH));viewport.scrollTo({left:0,behavior:'smooth'})});document.querySelector('#zoomIn').addEventListener('click',()=>setScale(scale+.15));document.querySelector('#zoomOut').addEventListener('click',()=>setScale(scale-.15));document.querySelector('#zoomReset').addEventListener('click',()=>setScale(1));eventsLayer.addEventListener('click',ev=>{const b=ev.target.closest('[data-id]');if(b)openEvent(b.dataset.id)});listView.addEventListener('click',ev=>{const b=ev.target.closest('[data-id]');if(b)openEvent(b.dataset.id)});document.querySelector('#readerClose').addEventListener('click',closeReader);reader.addEventListener('click',ev=>{if(ev.target===reader)closeReader()});prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));document.querySelector('#methodBtn').addEventListener('click',()=>methodDialog.showModal());document.querySelector('#methodClose').addEventListener('click',()=>methodDialog.close());addEventListener('keydown',ev=>{if(!reader.classList.contains('open'))return;if(ev.key==='Escape')closeReader();if(ev.key==='ArrowLeft')move(-1);if(ev.key==='ArrowRight')move(1)});const initial=location.hash.slice(1);if(EVENTS.some(e=>e.id===initial))openEvent(initial);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));
