const BASE=window.STUDIO_GLOSSARY||{},EXTRAS=window.DICTIONARY_EXTRAS||{},GREEK=window.DICTIONARY_GREEK||{},GROUPS=window.DICTIONARY_GROUPS||{},THEMES=window.DICTIONARY_THEMES||{},DETAILS=window.DICTIONARY_DETAILS||{};
const normalize=text=>String(text||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const slug=text=>normalize(text).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function classify(term){for(const [group,terms] of Object.entries(GROUPS))if(terms.includes(term))return group;return 'Contesto'}
function themeOf(term){for(const [theme,terms] of Object.entries(THEMES))if(terms.includes(term))return theme;return 'Concetti generali'}
const ENTRIES=Object.entries({...BASE,...EXTRAS}).map(([term,simple])=>{const detail=DETAILS[term]||{},greek=GREEK[term]||['',''];return{term,simple,greek:greek[0],translit:greek[1],author:classify(term),theme:themeOf(term),deep:detail.deep||'',example:detail.example||'',compare:detail.compare||'',refs:detail.refs||[],study:detail.study||'',deepLink:detail.deepLink||'',id:slug(term)}}).sort((a,b)=>a.term.localeCompare(b.term,'it',{sensitivity:'base'}));
const terms=document.querySelector('#terms'),empty=document.querySelector('#empty'),search=document.querySelector('#search'),authorFilters=document.querySelector('#authorFilters'),themeFilters=document.querySelector('#themeFilters'),alphabet=document.querySelector('#alphabet'),catalogTitle=document.querySelector('#catalogTitle'),totalCount=document.querySelector('#totalCount'),visibleCount=document.querySelector('#visibleCount'),savedCount=document.querySelector('#savedCount'),savedBtn=document.querySelector('#savedBtn'),clearBtn=document.querySelector('#clearBtn'),randomBtn=document.querySelector('#randomBtn');
const reader=document.querySelector('#reader'),readerTerm=document.querySelector('#readerTerm'),readerMeta=document.querySelector('#readerMeta'),readerTheme=document.querySelector('#readerTheme'),readerTitle=document.querySelector('#readerTitle'),readerGreek=document.querySelector('#readerGreek'),readerSimple=document.querySelector('#readerSimple'),readerDeep=document.querySelector('#readerDeep'),readerExample=document.querySelector('#readerExample'),readerCompare=document.querySelector('#readerCompare'),readerRefs=document.querySelector('#readerRefs'),studyLink=document.querySelector('#studyLink'),deepLink=document.querySelector('#deepLink'),saveTerm=document.querySelector('#saveTerm'),prev=document.querySelector('#prev'),next=document.querySelector('#next'),toast=document.querySelector('#toast');
let author='tutti',theme='tutti',letter='',query='',onlySaved=false,currentId=null,currentList=[],timer;
const saved=new Set(JSON.parse(localStorage.getItem('pa-dictionary-saved')||'[]'));
function say(text){clearTimeout(timer);toast.textContent=text;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function searchable(entry){return normalize([entry.term,entry.simple,entry.greek,entry.translit,entry.author,entry.theme,entry.deep,entry.example,entry.compare,entry.refs.join(' ')].join(' '))}
function filtered(){const q=normalize(query.trim());return ENTRIES.filter(entry=>(author==='tutti'||entry.author===author)&&(theme==='tutti'||entry.theme===theme)&&(!letter||normalize(entry.term).startsWith(normalize(letter)))&&(!onlySaved||saved.has(entry.id))&&(!q||searchable(entry).includes(q)))}
function updateStats(list){totalCount.textContent=`${ENTRIES.length} voci`;visibleCount.textContent=`${list.length} visibili`;savedCount.textContent=`${saved.size} salvate`}
function renderThemes(){const names=Object.keys(THEMES).sort((a,b)=>a.localeCompare(b,'it'));themeFilters.innerHTML=`<button class="active" data-theme="tutti">Tutti</button>${names.map(name=>`<button data-theme="${name}">${name}</button>`).join('')}`}
function renderAlphabet(){const available=new Set(ENTRIES.map(entry=>normalize(entry.term).charAt(0).toUpperCase()));const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');alphabet.innerHTML=`<button data-letter="" class="active">Tutte</button>${letters.map(l=>`<button data-letter="${l}" ${available.has(l)?'':'disabled'}>${l}</button>`).join('')}`}
function render(){const list=filtered();currentList=list.map(entry=>entry.id);terms.innerHTML=list.map(entry=>`<button class="termCard ${saved.has(entry.id)?'saved':''}" data-id="${entry.id}"><span class="star">★</span><div class="termMeta"><span class="badge ${entry.author.toLowerCase()}">${entry.author}</span><span class="badge">${entry.theme}</span></div><h3>${entry.term}</h3>${entry.greek?`<p class="greekSmall">${entry.greek}</p>`:''}<p class="simple">${entry.simple}</p></button>`).join('');empty.hidden=list.length>0;catalogTitle.textContent=letter?`Lettera ${letter}`:onlySaved?'Voci salvate':theme!=='tutti'?theme:author!=='tutti'?author:'Tutto il lessico';updateStats(list)}
function sectionFor(element){return element.closest('section')}
function openEntry(id){const entry=ENTRIES.find(item=>item.id===id);if(!entry)return;currentId=id;currentList=filtered().map(item=>item.id);if(!currentList.includes(id))currentList=ENTRIES.map(item=>item.id);readerTerm.textContent=entry.term;readerMeta.textContent=`${entry.author} · ${entry.theme}`;readerTheme.textContent=entry.theme;readerTitle.textContent=entry.term;readerGreek.textContent=entry.greek?`${entry.greek} · ${entry.translit}`:'';readerGreek.hidden=!entry.greek;readerSimple.textContent=entry.simple;readerDeep.innerHTML=entry.deep?`<p>${entry.deep}</p>`:`<p>${entry.simple}</p><p>Questa voce è presentata in forma essenziale. Le lezioni collegate ne mostrano l’uso nel sistema filosofico.</p>`;readerExample.textContent=entry.example;sectionFor(readerExample).hidden=!entry.example;readerCompare.textContent=entry.compare;sectionFor(readerCompare).hidden=!entry.compare;readerRefs.innerHTML=entry.refs.map(ref=>`<li>${ref}</li>`).join('');sectionFor(readerRefs).hidden=!entry.refs.length;studyLink.href=entry.study?`../studio/#${entry.study}`:'../studio/';deepLink.href=entry.deepLink?`../approfondisco/#${entry.deepLink}`:'../approfondisco/';saveTerm.textContent=saved.has(id)?'★ Salvata':'☆ Salva';saveTerm.classList.toggle('active',saved.has(id));const index=currentList.indexOf(id);prev.disabled=index<=0;next.disabled=index<0||index>=currentList.length-1;reader.classList.add('open');reader.setAttribute('aria-hidden','false');document.body.classList.add('reader-open');reader.scrollTop=0;history.replaceState(null,'',`#${id}`)}
function closeReader(){reader.classList.remove('open');reader.setAttribute('aria-hidden','true');document.body.classList.remove('reader-open');history.replaceState(null,'',location.pathname+location.search)}
function move(delta){const index=currentList.indexOf(currentId),id=currentList[index+delta];if(id)openEntry(id)}
function reset(){author='tutti';theme='tutti';letter='';query='';onlySaved=false;search.value='';savedBtn.classList.remove('active');savedBtn.textContent='☆ Solo salvate';document.querySelectorAll('[data-author]').forEach(button=>button.classList.toggle('active',button.dataset.author==='tutti'));document.querySelectorAll('[data-theme]').forEach(button=>button.classList.toggle('active',button.dataset.theme==='tutti'));document.querySelectorAll('[data-letter]').forEach(button=>button.classList.toggle('active',button.dataset.letter===''));render()}
renderThemes();renderAlphabet();
authorFilters.addEventListener('click',event=>{const button=event.target.closest('[data-author]');if(!button)return;author=button.dataset.author;authorFilters.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));render()});
themeFilters.addEventListener('click',event=>{const button=event.target.closest('[data-theme]');if(!button)return;theme=button.dataset.theme;themeFilters.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));render()});
alphabet.addEventListener('click',event=>{const button=event.target.closest('[data-letter]');if(!button||button.disabled)return;letter=button.dataset.letter;alphabet.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));render()});
search.addEventListener('input',()=>{query=search.value;render()});savedBtn.addEventListener('click',()=>{onlySaved=!onlySaved;savedBtn.classList.toggle('active',onlySaved);savedBtn.textContent=onlySaved?'★ Solo salvate':'☆ Solo salvate';render()});clearBtn.addEventListener('click',reset);terms.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(button)openEntry(button.dataset.id)});
randomBtn.addEventListener('click',()=>{const list=filtered().length?filtered():ENTRIES;openEntry(list[Math.floor(Math.random()*list.length)].id)});document.querySelector('#readerClose').addEventListener('click',closeReader);reader.addEventListener('click',event=>{if(event.target===reader)closeReader()});prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));saveTerm.addEventListener('click',()=>{if(!currentId)return;if(saved.has(currentId))saved.delete(currentId);else saved.add(currentId);localStorage.setItem('pa-dictionary-saved',JSON.stringify([...saved]));saveTerm.textContent=saved.has(currentId)?'★ Salvata':'☆ Salva';saveTerm.classList.toggle('active',saved.has(currentId));render();say(saved.has(currentId)?'Voce salvata.':'Voce rimossa dai salvataggi.')});document.querySelector('#copyBtn').addEventListener('click',async()=>{const entry=ENTRIES.find(item=>item.id===currentId);if(!entry)return;const text=`${entry.term}${entry.greek?` (${entry.greek}, ${entry.translit})`:''}\n\n${entry.simple}${entry.deep?`\n\n${entry.deep}`:''}${entry.compare?`\n\nConfronto: ${entry.compare}`:''}`;try{await navigator.clipboard.writeText(text);say('Voce copiata.')}catch{say('Copia non disponibile in questo browser.')}});addEventListener('keydown',event=>{if(!reader.classList.contains('open'))return;if(event.key==='Escape')closeReader();if(event.key==='ArrowLeft')move(-1);if(event.key==='ArrowRight')move(1)});
render();const initial=location.hash.slice(1);if(ENTRIES.some(entry=>entry.id===initial))openEntry(initial);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));