window.DICTIONARY_EXTRAS={
"Aporia":"Una difficoltà in cui il ragionamento non trova una via d’uscita immediata; nei dialoghi socratici dissolve la falsa sicurezza.",
"Anamnesi":"Reminiscenza: per Platone conoscere significa in qualche modo ricordare realtà intelligibili già conosciute dall’anima.",
"Arché":"Principio, origine o punto da cui dipende una dimostrazione, un processo o una realtà.",
"Dianoia":"Pensiero discorsivo. Nella linea platonica è il livello delle scienze matematiche, ancora fondato su ipotesi.",
"Eikasia":"Immaginazione o congettura fondata su immagini, ombre e riflessi; è il livello più basso della linea divisa.",
"Pistis":"Credenza rivolta agli oggetti sensibili; superiore all’immaginazione, ma ancora interna alla doxa.",
"Proairesis":"Scelta deliberata dei mezzi che dipendono da noi, distinta dal semplice desiderio e dall’opinione.",
"Praxis":"Azione il cui fine appartiene all’agire stesso, come vivere o agire giustamente.",
"Theoria":"Contemplazione o attività conoscitiva svolta per se stessa.",
"Akrasia":"Debolezza della volontà: conoscere ciò che sarebbe meglio e agire diversamente sotto la pressione del desiderio.",
"Entimema":"Il ragionamento proprio della retorica, fondato spesso su premesse probabili o implicite.",
"Universale":"Ciò che può essere predicato di molti casi e viene colto come carattere comune.",
"Particolare":"L’individuo o il caso concreto, distinto dall’universale ma necessario alla conoscenza e all’azione.",
"Telos":"Fine o compimento verso cui un’attività, uno sviluppo o una vita sono ordinati.",
"Techné":"Arte o sapere produttivo fondato su regole e ragioni, non semplice abilità occasionale."
};
window.DICTIONARY_GREEK={
"polis":["πόλις","pólis"],"sofisti":["σοφισταί","sophistaí"],"elenchos":["ἔλεγχος","élenchos"],"giustizia":["δικαιοσύνη","dikaiosýnē"],"dialogo":["διάλογος","diálogos"],"mythos":["μῦθος","mŷthos"],"dialettica":["διαλεκτική","dialektikḗ"],"Idea":["ἰδέα","idéa"],"forma":["εἶδος / μορφή","eîdos / morphḗ"],"methexis":["μέθεξις","méthexis"],"Bene":["ἀγαθόν","agathón"],"doxa":["δόξα","dóxa"],"episteme":["ἐπιστήμη","epistḗmē"],"noesis":["νόησις","nóēsis"],"paideia":["παιδεία","paideía"],"psyché":["ψυχή","psychḗ"],"eros":["ἔρως","érōs"],"areté":["ἀρετή","aretḗ"],"armonia":["ἁρμονία","harmonía"],"kallipolis":["καλλίπολις","kallípolis"],"re-filosofo":["φιλόσοφος ἄρχων","philósophos árchōn"],"nomos":["νόμος","nómos"],"costituzione":["πολιτεία","politeía"],"mimesis":["μίμησις","mímēsis"],"pharmakon":["φάρμακον","phármakon"],"poiesis":["ποίησις","poíēsis"],"scrittura":["γραφή","graphḗ"],"Accademia":["Ἀκαδήμεια","Akadḗmeia"],"Liceo":["Λύκειον","Lýkeion"],"peripatetici":["περιπατητικοί","peripatētikoí"],"endoxa":["ἔνδοξα","éndoxa"],"induzione":["ἐπαγωγή","epagōgḗ"],"dimostrazione":["ἀπόδειξις","apódeixis"],"scienze teoretiche":["θεωρητικαὶ ἐπιστῆμαι","theōrētikaì epistêmai"],"Organon":["ὄργανον","órganon"],"proposizione":["πρότασις","prótasis"],"sillogismo":["συλλογισμός","syllogismós"],"termine medio":["μέσος ὅρος","mésos hóros"],"sostanza":["οὐσία","ousía"],"materia":["ὕλη","hýlē"],"ilemorfismo":["ὕλη + μορφή","hýlē + morphḗ"],"causa materiale":["ὕλη","hýlē"],"causa formale":["εἶδος","eîdos"],"causa efficiente":["ἀρχὴ κινήσεως","archḕ kinḗseōs"],"causa finale":["οὗ ἕνεκα","hoû héneka"],"dynamis":["δύναμις","dýnamis"],"energeia":["ἐνέργεια","enérgeia"],"entelechia":["ἐντελέχεια","entelécheia"],"movimento":["κίνησις","kínēsis"],"physis":["φύσις","phýsis"],"teleologia":["τέλος","télos"],"primo motore":["πρῶτον κινοῦν ἀκίνητον","prôton kinoûn akínēton"],"atto puro":["ἐνέργεια","enérgeia"],"anima nutritiva":["θρεπτικόν","threptikón"],"anima sensitiva":["αἰσθητικόν","aisthētikón"],"anima razionale":["νοητικόν","noētikón"],"intelletto":["νοῦς","noûs"],"eudaimonia":["εὐδαιμονία","eudaimonía"],"hexis":["ἕξις","héxis"],"giusto mezzo":["μεσότης","mesótēs"],"phronesis":["φρόνησις","phrónēsis"],"zoon politikon":["ζῷον πολιτικόν","zôon politikón"],"politeia":["πολιτεία","politeía"],"retorica":["ῥητορική","rhētorikḗ"],"catarsi":["κάθαρσις","kátharsis"],
"Aporia":["ἀπορία","aporía"],"Anamnesi":["ἀνάμνησις","anámnēsis"],"Arché":["ἀρχή","archḗ"],"Dianoia":["διάνοια","diánoia"],"Eikasia":["εἰκασία","eikasía"],"Pistis":["πίστις","pístis"],"Proairesis":["προαίρεσις","proaíresis"],"Praxis":["πρᾶξις","prâxis"],"Theoria":["θεωρία","theōría"],"Akrasia":["ἀκρασία","akrasía"],"Entimema":["ἐνθύμημα","enthýmēma"],"Universale":["καθόλου","kathólou"],"Particolare":["καθ’ ἕκαστον","kath’ hékaston"],"Telos":["τέλος","télos"],"Techné":["τέχνη","téchnē"]
};
window.DICTIONARY_GROUPS={
"Platone":["sofisti","elenchos","dialogo","Idea","methexis","Bene","doxa","noesis","paideia","eros","kallipolis","re-filosofo","pharmakon","scrittura","Aporia","Anamnesi","Eikasia","Pistis"],
"Aristotele":["Stagira","Liceo","peripatetici","endoxa","induzione","dimostrazione","scienze teoretiche","Organon","proposizione","sillogismo","termine medio","sostanza","materia","ilemorfismo","causa materiale","causa formale","causa efficiente","causa finale","dynamis","energeia","entelechia","movimento","physis","teleologia","primo motore","atto puro","anima nutritiva","anima sensitiva","anima razionale","intelletto","eudaimonia","hexis","giusto mezzo","phronesis","zoon politikon","politeia","retorica","catarsi","Proairesis","Praxis","Theoria","Akrasia","Entimema","Telos"],
"Entrambi":["polis","giustizia","mythos","dialettica","forma","episteme","psyché","areté","armonia","nomos","costituzione","mimesis","poiesis","Universale","Particolare","Arché","Dianoia","Techné"],
"Contesto":["Accademia"]
};
window.DICTIONARY_THEMES={
"Metodo":["sofisti","elenchos","dialogo","dialettica","Aporia","Arché","endoxa","induzione","Techné"],
"Conoscenza":["doxa","episteme","noesis","Dianoia","Eikasia","Pistis","Anamnesi","intelletto","Universale","Particolare"],
"Metafisica":["Idea","forma","methexis","Bene","sostanza","materia","ilemorfismo","causa materiale","causa formale","causa efficiente","causa finale","dynamis","energeia","entelechia","atto puro","Telos"],
"Anima ed etica":["psyché","eros","areté","armonia","anima nutritiva","anima sensitiva","anima razionale","eudaimonia","hexis","giusto mezzo","phronesis","Akrasia","Proairesis"],
"Politica":["polis","giustizia","kallipolis","re-filosofo","nomos","costituzione","zoon politikon","politeia"],
"Arte e linguaggio":["mythos","mimesis","pharmakon","poiesis","scrittura","retorica","catarsi","Entimema"],
"Logica e scienza":["dimostrazione","scienze teoretiche","Organon","proposizione","sillogismo","termine medio"],
"Natura e cosmo":["movimento","physis","teleologia","primo motore"],
"Scuole e contesto":["Stagira","Accademia","Liceo","peripatetici"],
"Azione e contemplazione":["Praxis","Theoria"]
};
window.DICTIONARY_DETAILS={
"Aporia":{"deep":"Nei dialoghi socratici l’aporia non è un fallimento sterile: mostra che l’interlocutore non possiede ancora la definizione che credeva di avere. Aristotele raccoglie spesso le aporie iniziali per definire il programma della ricerca.","example":"Una definizione di virtù viene confutata, ma non è ancora disponibile una soluzione migliore.","compare":"Per Platone educa al riconoscimento del non-sapere; per Aristotele organizza le difficoltà che una teoria deve risolvere.","refs":["Platone, dialoghi socratici","Aristotele, Metafisica III"],"study":"p2","deepLink":"a2"},
"Anamnesi":{"deep":"Nel Menone e nel Fedone la capacità di riconoscere uguaglianza, bellezza o principi matematici viene collegata a una conoscenza anteriore all’esperienza presente.","example":"Due oggetti quasi uguali vengono giudicati imperfetti rispetto all’Uguale in sé.","compare":"Aristotele rifiuta la reminiscenza e fa iniziare la conoscenza da percezione, memoria ed esperienza.","refs":["Platone, Menone 81a–86c","Platone, Fedone 72e–77a"],"study":"p4","deepLink":"p4"},
"psyché":{"deep":"Per Platone l’anima è immortale e articolata in funzioni razionale, animosa e desiderante. Per Aristotele è la forma e l’atto primo di un corpo vivente.","example":"La vista è per l’occhio ciò che l’anima è per il corpo vivente: il principio della sua attività propria.","compare":"Platone insiste sulla separabilità; Aristotele sull’unità del vivente, pur lasciando aperto il problema dell’intelletto.","refs":["Platone, Fedone e Repubblica IV","Aristotele, De anima II 1"],"study":"p5","deepLink":"a8"},
"areté":{"deep":"Areté non indica soltanto bontà morale, ma l’eccellenza grazie alla quale una cosa o una persona svolge bene la propria funzione.","example":"Il coraggio è l’eccellenza con cui si affrontano correttamente paura e pericolo.","compare":"Platone collega la virtù all’armonia dell’anima; Aristotele all’abitudine, alla scelta e alla saggezza pratica.","refs":["Platone, Repubblica IV","Aristotele, Etica Nicomachea II"],"study":"p5","deepLink":"a9"},
"Bene":{"deep":"Nella Repubblica l’Idea del Bene rende conoscibili le altre Forme ed è paragonata al sole. Aristotele cerca il bene umano nell’attività felice secondo virtù.","example":"Una tecnica è giudicata buona in rapporto al fine che realizza; la vita intera richiede un fine non subordinato.","compare":"Platone assegna al Bene una funzione metafisica suprema; Aristotele lo studia attraverso fini e attività.","refs":["Platone, Repubblica VI 506d–509c","Aristotele, Etica Nicomachea I"],"study":"p3","deepLink":"a9"},
"catarsi":{"deep":"La Poetica nomina la catarsi senza spiegarla diffusamente nel testo conservato. Le letture parlano di purificazione, regolazione, chiarificazione o sollievo delle emozioni.","example":"Lo spettatore prova pietà e paura davanti alla vicenda tragica senza trovarsi nel pericolo reale.","compare":"Platone teme che la poesia alimenti passioni disordinate; Aristotele attribuisce alla tragedia una funzione strutturata.","refs":["Aristotele, Poetica 6, 1449b24–28"],"study":"a10","deepLink":"a10"},
"dialettica":{"deep":"Per Platone può risalire dalle ipotesi ai principi e riconoscere le relazioni tra le Forme. Per Aristotele ragiona da premesse accreditate e vaglia problemi e principi.","example":"Una tesi viene confrontata con conseguenze, obiezioni e alternative.","compare":"Platone la pone al vertice della conoscenza; Aristotele la distingue dalla dimostrazione scientifica.","refs":["Platone, Repubblica VI–VII","Aristotele, Topici I"],"study":"p2","deepLink":"a2"},
"Dianoia":{"deep":"Nella linea platonica è il pensiero matematico che procede da ipotesi. Nella Poetica aristotelica indica il pensiero espresso nelle decisioni e nei discorsi dei personaggi.","example":"Una dimostrazione geometrica sviluppa passaggi razionali senza ancora interrogare il fondamento ultimo delle ipotesi.","compare":"Il termine cambia funzione nei due sistemi e non va tradotto sempre nello stesso modo.","refs":["Platone, Repubblica VI 509d–511e","Aristotele, Poetica 6"],"study":"p4","deepLink":"a10"},
"doxa":{"deep":"Nella Repubblica la doxa riguarda il sensibile e comprende immaginazione e credenza. Non significa che ogni opinione sia falsa, ma che non possiede la stabilità dell’episteme.","example":"Si può indicare correttamente una strada senza saper spiegare perché sia quella giusta.","compare":"Aristotele usa opinioni accreditate come punto di partenza dialettico, non solo come livello inferiore.","refs":["Platone, Menone 97a–98a","Platone, Repubblica V–VI"],"study":"p4","deepLink":"p4"},
"dynamis":{"deep":"La potenza è una capacità reale fondata nell’ente, non qualunque possibilità immaginabile. È sempre definita in rapporto a un atto.","example":"Un seme può diventare la pianta della propria specie, non qualunque cosa.","compare":"Il concetto permette di spiegare il divenire senza un passaggio dal nulla assoluto.","refs":["Aristotele, Metafisica IX"],"study":"a6","deepLink":"a6"},
"energeia":{"deep":"Energeia indica l’esercizio effettivo di una capacità o una realtà pienamente attuale. È uno dei termini chiave della metafisica aristotelica.","example":"Vedere è l’attività attuale della facoltà visiva.","compare":"Nell’etica la felicità è attività, non semplice possesso di una virtù.","refs":["Aristotele, Metafisica IX","Aristotele, Etica Nicomachea I 7"],"study":"a6","deepLink":"a9"},
"endoxa":{"deep":"Gli endoxa non sono verità da accettare passivamente: sono il materiale iniziale che la dialettica confronta e chiarisce.","example":"La ricerca sulla felicità parte dalle convinzioni diffuse e verifica quali possano essere sostenute.","compare":"Il metodo evita sia il relativismo sia una deduzione che ignori l’esperienza comune.","refs":["Aristotele, Topici I 1"],"study":"a2","deepLink":"a2"},
"episteme":{"deep":"Per Platone è conoscenza stabile dell’intelligibile. Per Aristotele è conoscenza dimostrativa del necessario attraverso le cause.","example":"Sapere non solo che una proprietà geometrica vale, ma comprenderne la dimostrazione.","compare":"Platone lega la stabilità del sapere alle Forme; Aristotele alla struttura causale della dimostrazione.","refs":["Platone, Repubblica V–VI","Aristotele, Analitici secondi I"],"study":"p4","deepLink":"a3"},
"eros":{"deep":"Nel Simposio Eros è intermedio tra povertà e risorsa: non possiede il bene, ma lo cerca. L’ascesa erotica muove dalla bellezza sensibile verso forme più universali.","example":"L’amore per una persona può aprire alla domanda su ciò che rende belle molte persone e azioni.","compare":"Aristotele tratta più estesamente la philia, fondata su reciprocità e vita condivisa.","refs":["Platone, Simposio 201d–212a","Platone, Fedro"],"study":"p5","deepLink":"p5"},
"eudaimonia":{"deep":"È attività dell’anima secondo virtù lungo una vita compiuta. Non è una sensazione momentanea e richiede anche relazioni e condizioni esterne.","example":"Una vita non è riuscita soltanto perché contiene momenti piacevoli.","compare":"Platone collega la felicità all’ordine dell’anima; Aristotele la definisce come attività eccellente.","refs":["Aristotele, Etica Nicomachea I 7–10"],"study":"a9","deepLink":"a9"},
"forma":{"deep":"Per Platone la Forma è stabile e separata dai particolari. Per Aristotele è immanente alla sostanza e organizza la materia.","example":"La forma di una pianta non è il contorno, ma il principio delle sue funzioni e del suo sviluppo.","compare":"La diversa collocazione della forma separa profondamente i due sistemi.","refs":["Platone, Fedone","Aristotele, Metafisica VII"],"study":"p3","deepLink":"a4"},
"giustizia":{"deep":"In Platone è l’ordine in cui ogni parte dell’anima e della città svolge la propria funzione. Aristotele distingue giustizia distributiva, correttiva e generale.","example":"Distribuire beni e cariche richiede un criterio proporzionato, non una semplice uguaglianza numerica.","compare":"Platone pensa un ordine organico; Aristotele analizza anche rapporti concreti di uguaglianza e correzione.","refs":["Platone, Repubblica IV","Aristotele, Etica Nicomachea V"],"study":"p6","deepLink":"a9"},
"giusto mezzo":{"deep":"Non è una media matematica né mediocrità. È ciò che la ragione pratica determina considerando oggetto, momento, motivo e modo dell’azione.","example":"Il coraggio sta tra viltà e temerarietà, ma dipende dal pericolo reale.","compare":"La misura è relativa alla situazione ma non arbitraria.","refs":["Aristotele, Etica Nicomachea II 6"],"study":"a9","deepLink":"a9"},
"Idea":{"deep":"Le Idee non sono pensieri soggettivi, ma criteri e oggetti intelligibili che spiegano come molti particolari possano essere detti belli, giusti o uguali.","example":"Molte azioni vengono giudicate giuste in riferimento a ciò che la giustizia è.","compare":"Aristotele critica la separazione delle Idee e colloca forma ed essenza nelle sostanze concrete.","refs":["Platone, Fedone","Platone, Repubblica V–VI","Platone, Parmenide"],"study":"p3","deepLink":"p3"},
"ilemorfismo":{"deep":"Il termine è moderno, ma descrive l’unità aristotelica di materia e forma. La forma esiste concretamente nella materia del composto.","example":"Un vivente non è un corpo più un’anima ospite, ma un corpo organizzato dalla forma vitale.","compare":"È l’alternativa aristotelica alla separazione platonica delle Forme.","refs":["Aristotele, Metafisica VII–VIII","Aristotele, De anima II 1"],"study":"a4","deepLink":"a8"},
"intelletto":{"deep":"Per Platone il nous si orienta alle Forme attraverso la dialettica. Aristotele distingue intelletto potenziale e agente in un passo molto discusso.","example":"Comprendere un principio non equivale a ripetere una serie di percezioni.","compare":"Platone sottolinea l’ascesa verso l’intelligibile; Aristotele il passaggio dall’esperienza alla forma universale.","refs":["Platone, Repubblica VI","Aristotele, De anima III 4–5"],"study":"p4","deepLink":"a8"},
"materia":{"deep":"La materia è ciò che, rispetto a una forma, possiede la potenza di essere organizzato in un certo modo. Non è puro caos indipendente da ogni determinazione.","example":"Il bronzo è materia della statua; gli organi sono materia del vivente.","compare":"La materia da sola non spiega l’unità e l’essenza dell’ente.","refs":["Aristotele, Metafisica VII–VIII"],"study":"a4","deepLink":"a4"},
"methexis":{"deep":"Partecipazione, imitazione e presenza sono modi con cui Platone pensa la dipendenza dei particolari dalle Idee. Il Parmenide mostra le difficoltà del rapporto.","example":"Una cosa è bella perché partecipa del Bello, senza essere il Bello in sé.","compare":"Aristotele giudica la partecipazione una metafora insufficiente se non si chiarisce la causalità concreta.","refs":["Platone, Fedone 100c–101d","Platone, Parmenide 130a–135d"],"study":"p3","deepLink":"p3"},
"mimesis":{"deep":"Platone teme che l’imitazione riproduca apparenze e modelli emotivi senza conoscenza. Aristotele la considera naturale e capace di rappresentare strutture universali dell’azione.","example":"La tragedia non copia una cronaca precisa, ma costruisce una vicenda possibile e significativa.","compare":"È uno dei contrasti più netti fra i due filosofi.","refs":["Platone, Repubblica X","Aristotele, Poetica 1–6"],"study":"p7","deepLink":"a10"},
"mythos":{"deep":"In Platone il mito rende immaginabili destino dell’anima, cosmo o educazione. Nella Poetica aristotelica mythos indica soprattutto l’intreccio delle azioni.","example":"La caverna è racconto filosofico; nella tragedia il mythos è la struttura degli eventi.","compare":"Lo stesso termine passa da narrazione simbolica a concetto tecnico della poetica.","refs":["Platone, Repubblica VII","Aristotele, Poetica 6–10"],"study":"p2","deepLink":"a10"},
"noesis":{"deep":"La noesis usa la dialettica per oltrepassare le ipotesi e orientarsi verso i principi, culminando nell’Idea del Bene.","example":"Non si limita a usare un’ipotesi matematica, ma ne interroga il fondamento.","compare":"Aristotele usa nous e noesis senza la stessa struttura della linea platonica.","refs":["Platone, Repubblica VI 509d–511e"],"study":"p4","deepLink":"p4"},
"paideia":{"deep":"L’educazione non inserisce conoscenze in una mente vuota: converte l’anima verso ciò che è degno di essere conosciuto e desiderato.","example":"Musica, ginnastica, matematica e dialettica formano insieme carattere e intelligenza.","compare":"Anche Aristotele assegna alla legge il compito di formare abitudini, ma studia costituzioni più concrete.","refs":["Platone, Repubblica II–III e VII"],"study":"p4","deepLink":"p6"},
"pharmakon":{"deep":"Nel Fedro la scrittura è aiuto alla memoria ma anche possibile causa di oblio e apparenza di sapienza. L’ambivalenza non equivale a un rifiuto semplice.","example":"Un testo conserva informazioni, ma non può rispondere al dubbio del lettore.","compare":"Anche una PWA può diventare rimedio o sostituto del pensiero, a seconda dell’uso.","refs":["Platone, Fedro 274c–277a"],"study":"p7","deepLink":"p7"},
"phronesis":{"deep":"Conosce principi generali e particolari concreti. Non è astuzia neutrale, perché richiede un fine formato dalla virtù morale.","example":"Una regola generale non basta a decidere come dire una verità difficile in una situazione concreta.","compare":"Platone unifica più fortemente sapere del bene e governo; Aristotele distingue la saggezza pratica dalla scienza.","refs":["Aristotele, Etica Nicomachea VI 5–13"],"study":"a9","deepLink":"a9"},
"polis":{"deep":"La polis non è soltanto un luogo fisico: comprende cittadini, leggi, educazione, istituzioni e una certa idea del bene comune.","example":"Atene è assemblea, tribunali, culti e memoria condivisa, non solo mura e territorio.","compare":"Platone costruisce la città giusta come immagine dell’anima; Aristotele la considera compimento naturale della socialità umana.","refs":["Platone, Repubblica","Aristotele, Politica I 2"],"study":"p1","deepLink":"a10"},
"sillogismo":{"deep":"Il sillogismo collega termini attraverso un termine medio. La validità dipende dalla forma, non dalla verità effettiva delle premesse.","example":"Tutti gli uomini sono mortali; Socrate è uomo; dunque Socrate è mortale.","compare":"La dimostrazione scientifica è un sillogismo con premesse vere e causali.","refs":["Aristotele, Analitici primi I 1"],"study":"a3","deepLink":"a3"},
"sostanza":{"deep":"Nelle Categorie la sostanza prima è l’individuo concreto. Nella Metafisica la ricerca considera materia, forma e composto, attribuendo alla forma priorità esplicativa.","example":"Questo uomo è sostanza; essere pallido è una proprietà che gli appartiene.","compare":"La sostanza aristotelica sostituisce la duplicazione platonica con l’analisi dell’ente concreto.","refs":["Aristotele, Categorie 5","Aristotele, Metafisica VII–VIII"],"study":"a4","deepLink":"a4"},
"zoon politikon":{"deep":"Non significa soltanto che l’uomo è socievole. L’essere umano possiede logos, discute il giusto e partecipa a istituzioni comuni.","example":"La comunità politica non si limita a proteggere la vita, ma delibera su come vivere bene insieme.","compare":"Platone pensa la città come ordine educativo; Aristotele come compimento naturale e pluralistico della socialità.","refs":["Aristotele, Politica I 2, 1253a1–18"],"study":"a10","deepLink":"a10"}
};