const NODES=window.ATLAS_NODES||[],EDGES=window.ATLAS_EDGES||[],ROUTES=window.ATLAS_ROUTES||[];
const nodeMap=new Map(NODES.map(node=>[node.id,node]));
const nodesBox=document.querySelector('#nodes'),edgesSvg=document.querySelector('#edges'),viewport=document.querySelector('#viewport'),sizer=document.querySelector('#sizer'),world=document.querySelector('#world'),search=document.querySelector('#search'),authorFilters=document.querySelector('#authorFilters'),themeFilters=document.querySelector('#themeFilters'),routeButtons=document.querySelector('#routeButtons'),routeDescription=document.querySelector('#routeDescription'),clearRoute=document.querySelector('#clearRoute'),mapStatus=document.querySelector('#mapStatus'),emptyDetail=document.querySelector('#emptyDetail'),nodeDetail=document.querySelector('#nodeDetail'),detailAuthor=document.querySelector('#detailAuthor'),detailTheme=document.querySelector('#detailTheme'),detailGreek=document.querySelector('#detailGreek'),detailTitle=document.querySelector('#detailTitle'),detailSummary=document.querySelector('#detailSummary'),detailQuestion=document.querySelector('#detailQuestion'),detailRole=document.querySelector('#detailRole'),relations=document.querySelector('#relations'),detailLinks=document.querySelector('#detailLinks'),toast=document.querySelector('#toast'),helpDialog=document.querySelector('#helpDialog');
let scale=.72,author='tutti',theme='tutti',query='',selectedId=null,routeId=null,timer;
const themes=[...new Set(NODES.map(node=>node.theme))].sort((a,b)=>a.localeCompare(b,'it'));
function say(text){clearTimeout(timer);toast.textContent=text;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function normalize(text=''){return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function filteredIds(){const q=normalize(query.trim());return new Set(NODES.filter(node=>(author==='tutti'||node.author===author)&&(theme==='tutti'||node.theme===theme)&&(!q||normalize([node.label,node.greek,node.summary,node.question,node.role,node.theme,node.author].join(' ')).includes(q))).map(node=>node.id))}
function updateScale(next){scale=Math.max(.4,Math.min(1.25,next));world.style.transform=`scale(${scale})`;sizer.style.width=`${1500*scale}px`;sizer.style.height=`${1150*scale}px`}
function fitMap(){const next=Math.min((viewport.clientWidth-24)/1500,(viewport.clientHeight-24)/1150,1);updateScale(Math.max(.4,next));viewport.scrollTo({left:0,top:0,behavior:'smooth'})}
function centerNode(id){const node=nodeMap.get(id);if(!node)return;const left=node.x*scale-viewport.clientWidth/2,top=node.y*scale-viewport.clientHeight/2;viewport.scrollTo({left:Math.max(0,left),top:Math.max(0,top),behavior:'smooth'})}
function renderNodes(){nodesBox.innerHTML=NODES.map(node=>`<button class="node ${node.author}" style="left:${node.x}px;top:${node.y}px" data-id="${node.id}" aria-label="${node.label}"><strong>${node.label}</strong><small>${node.theme}</small></button>`).join('')}
function renderEdges(){const lines=[],labels=[];EDGES.forEach((edge,index)=>{const from=nodeMap.get(edge.from),to=nodeMap.get(edge.to);if(!from||!to)return;lines.push(`<line id="edge-${index}" data-from="${edge.from}" data-to="${edge.to}" class="${edge.type==='contrast'?'contrastEdge':''}" x1="${from.x}" y1="${from.y}" x2="${to.x}" y2="${to.y}"></line>`);labels.push(`<text id="label-${index}" data-from="${edge.from}" data-to="${edge.to}" class="edgeLabel" x="${(from.x+to.x)/2}" y="${(from.y+to.y)/2-7}" text-anchor="middle">${edge.label}</text>`)});edgesSvg.insertAdjacentHTML('beforeend',lines.join('')+labels.join(''))}
function renderThemeFilters(){themeFilters.innerHTML=`<button class="active" data-theme="tutti">Tutti i temi</button>${themes.map(item=>`<button data-theme="${item}">${item}</button>`).join('')}`}
function renderRoutes(){routeButtons.innerHTML=ROUTES.map(route=>`<button data-route="${route.id}">${route.title}</button>`).join('')}
function applyView(){const visible=filteredIds(),route=ROUTES.find(item=>item.id===routeId),routeSet=new Set(route?.nodes||[]),selectedEdges=new Set();if(selectedId){EDGES.forEach((edge,index)=>{if(edge.from===selectedId||edge.to===selectedId)selectedEdges.add(index)})}
 document.querySelectorAll('.node').forEach(button=>{const id=button.dataset.id,isVisible=visible.has(id),isRoute=!routeId||routeSet.has(id);button.hidden=!isVisible;button.classList.toggle('dim',routeId&&!isRoute);button.classList.toggle('routeNode',routeId&&routeSet.has(id));button.classList.toggle('selected',id===selectedId);if(selectedId&&!routeId&&id!==selectedId){const connected=EDGES.some(edge=>(edge.from===selectedId&&edge.to===id)||(edge.to===selectedId&&edge.from===id));button.classList.toggle('routeNode',connected)}else if(!routeId)button.classList.toggle('routeNode',false)});
 let visibleEdges=0;EDGES.forEach((edge,index)=>{const line=document.querySelector(`#edge-${index}`),label=document.querySelector(`#label-${index}`);if(!line)return;const edgeVisible=visible.has(edge.from)&&visible.has(edge.to),routeActive=routeId&&routeSet.has(edge.from)&&routeSet.has(edge.to),selectedActive=selectedEdges.has(index);line.style.display=edgeVisible?'':'none';label.style.display=edgeVisible?'':'none';line.classList.toggle('dim',routeId&&!routeActive);line.classList.toggle('active',Boolean(routeActive||selectedActive));label.classList.toggle('active',Boolean(routeActive||selectedActive));if(edgeVisible)visibleEdges++});
 mapStatus.textContent=`${visible.size} concetti · ${visibleEdges} relazioni`;if(selectedId&&!visible.has(selectedId))clearDetail(false)}
function showDetail(id,center=true){const node=nodeMap.get(id);if(!node)return;selectedId=id;emptyDetail.hidden=true;nodeDetail.hidden=false;detailAuthor.textContent=node.author;detailTheme.textContent=node.theme;detailGreek.textContent=node.greek||'';detailGreek.hidden=!node.greek;detailTitle.textContent=node.label;detailSummary.textContent=node.summary;detailQuestion.textContent=node.question;detailRole.textContent=node.role;const direct=EDGES.flatMap(edge=>{if(edge.from===id)return[{id:edge.to,label:edge.label,direction:'→'}];if(edge.to===id)return[{id:edge.from,label:edge.label,direction:'←'}];return[]});relations.innerHTML=direct.map(item=>{const target=nodeMap.get(item.id);return`<button data-related="${item.id}"><span>${item.direction} ${target.label}</span><small>${item.label}</small></button>`}).join('')||'<p>Nessuna relazione diretta.</p>';const links=[];if(node.dict)links.push(`<a href="../dizionario/#${node.dict}">Dizionario · ${node.label}<span>→</span></a>`);(node.study||[]).forEach(item=>links.push(`<a href="../studio/#${item}">Studio · ${item.toUpperCase()}<span>→</span></a>`));(node.deep||[]).forEach(item=>links.push(`<a href="../approfondisco/#${item}">Approfondisco · ${item.toUpperCase()}<span>→</span></a>`));detailLinks.innerHTML=links.join('');history.replaceState(null,'',`#${id}`);applyView();if(center)centerNode(id)}
function clearDetail(resetHash=true){selectedId=null;emptyDetail.hidden=false;nodeDetail.hidden=true;if(resetHash)history.replaceState(null,'',location.pathname+location.search);applyView()}
function startRoute(id){const route=ROUTES.find(item=>item.id===id);if(!route)return;routeId=id;selectedId=null;routeButtons.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.route===id));routeDescription.textContent=route.description;clearRoute.classList.add('active');applyView();const first=nodeMap.get(route.nodes[0]);if(first)centerNode(first.id);say(`Itinerario: ${route.title}`)}
function resetRoute(){routeId=null;routeButtons.querySelectorAll('button').forEach(button=>button.classList.remove('active'));routeDescription.textContent='Scegli un itinerario: la mappa evidenzierà soltanto i concetti e i passaggi essenziali.';clearRoute.classList.remove('active');applyView();fitMap()}
renderNodes();renderEdges();renderThemeFilters();renderRoutes();updateScale(scale);applyView();
nodesBox.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(button)showDetail(button.dataset.id)});relations.addEventListener('click',event=>{const button=event.target.closest('[data-related]');if(button)showDetail(button.dataset.related)});authorFilters.addEventListener('click',event=>{const button=event.target.closest('[data-author]');if(!button)return;author=button.dataset.author;authorFilters.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));applyView()});themeFilters.addEventListener('click',event=>{const button=event.target.closest('[data-theme]');if(!button)return;theme=button.dataset.theme;themeFilters.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));applyView()});search.addEventListener('input',()=>{query=search.value;applyView()});routeButtons.addEventListener('click',event=>{const button=event.target.closest('[data-route]');if(button)startRoute(button.dataset.route)});clearRoute.addEventListener('click',resetRoute);document.querySelector('#zoomIn').addEventListener('click',()=>updateScale(scale+.1));document.querySelector('#zoomOut').addEventListener('click',()=>updateScale(scale-.1));document.querySelector('#fitMap').addEventListener('click',fitMap);document.querySelector('#helpBtn').addEventListener('click',()=>helpDialog.showModal());document.querySelector('#helpClose').addEventListener('click',()=>helpDialog.close());addEventListener('resize',()=>{if(innerWidth<980)updateScale(Math.min(scale,.72))});
setTimeout(fitMap,80);const initial=location.hash.slice(1);if(nodeMap.has(initial))setTimeout(()=>showDetail(initial),150);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('../sw.js',{updateViaCache:'none'}));
