(()=>{
  "use strict";
  const data=window.BERKELEY_DATA;
  const $=(selector,root=document)=>root.querySelector(selector);
  const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const keys={mode:"berkeley-mode",completed:"berkeley-completed",notes:"berkeley-notes",font:"berkeley-font"};
  const state={
    mode:localStorage.getItem(keys.mode)||"amateur",
    completed:new Set(JSON.parse(localStorage.getItem(keys.completed)||"[]")),
    discovery:0,discoveryAnswer:null,labIndex:0,labScore:0,labAnswered:false,quizAnswers:{},deferredInstall:null,map:data.maps[0].id
  };

  function esc(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
  function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),2400)}
  function showDialog(html){const dialog=$("#contentDialog");$("#dialogContent").innerHTML=html;dialog.showModal();dialog.scrollTop=0}
  function closeDialog(){const dialog=$("#contentDialog");if(dialog.open)dialog.close()}

  function renderDiscovery(){
    const step=data.discovery[state.discovery];const percent=((state.discovery+(state.discoveryAnswer!==null?1:0))/data.discovery.length)*100;
    $("#discovery").innerHTML=`<div class="discovery-head"><div><span>Esperimento mentale</span><span>${state.discovery+1} / ${data.discovery.length}</span></div><div class="discovery-track"><span style="width:${percent}%"></span></div></div><div class="discovery-body"><h3>${step.title}</h3><p>${step.prompt}</p>${state.discoveryAnswer===null?`<div class="choice-list">${step.choices.map((choice,index)=>`<button data-discovery-choice="${index}">${choice.label}</button>`).join("")}</div>`:`<div class="consequence"><strong>${step.choices[state.discoveryAnswer].title}</strong><p>${step.choices[state.discoveryAnswer].text}</p></div><button class="next-button" data-discovery-next>${state.discovery===data.discovery.length-1?"Ricomincia l’esperimento":"Continua →"}</button>`}</div>`;
  }
  function chooseDiscovery(index){state.discoveryAnswer=index;renderDiscovery()}
  function nextDiscovery(){if(state.discovery===data.discovery.length-1){state.discovery=0}else state.discovery+=1;state.discoveryAnswer=null;renderDiscovery()}

  function moduleContent(module){return state.mode==="student"?module.student:module.amateur}
  function renderModules(){
    $("#moduleGrid").innerHTML=data.modules.map(module=>{const content=moduleContent(module);return `<button class="module-card ${state.completed.has(module.id)?"complete":""}" style="--accent:${module.accent}" data-module="${module.id}"><span class="module-index">${module.number} · ${module.kicker}</span><h3>${module.title}</h3><p>${content.summary}</p><footer><span>${state.mode==="student"?"Argomento e fonti":"Spiegazione ed esempio"}</span><span>→</span></footer></button>`}).join("");
  }
  function openModule(id){
    const module=data.modules.find(item=>item.id===id);if(!module)return;const content=moduleContent(module);
    const body=state.mode==="student"?`<div class="detail-grid"><div class="detail-box"><h3>Concetti essenziali</h3><ul class="beat-list">${content.concepts.map(item=>`<li>${item}</li>`).join("")}</ul></div><div class="detail-box"><h3>Movimento dell’argomento</h3><p>${content.argument}</p></div></div><div class="source-note"><strong>Riferimento testuale</strong><p>${content.source}</p></div><div class="warning-note"><strong>Attenzione al fraintendimento</strong><p>${content.warning}</p></div>`:`<p>${content.narrative}</p><div class="detail-grid"><div class="detail-box"><h3>Passaggi</h3><ul class="beat-list">${content.beats.map(item=>`<li>${item}</li>`).join("")}</ul></div><div class="detail-box"><h3>Esempio</h3><p>${content.example}</p></div></div><div class="checkpoint"><strong>Punto fermo</strong><p>${content.checkpoint}</p></div>`;
    showDialog(`<article class="module-detail" data-open-module="${module.id}"><p class="kicker">${module.number} · ${module.kicker} · ${state.mode==="student"?"Studio filosofico":"Primo incontro"}</p><h2>${module.title}</h2><p class="module-question">${module.question}</p><p>${content.summary}</p>${body}<section class="quick-check"><h3>Controllo rapido</h3><p>${module.check.question}</p><div class="quick-options">${module.check.options.map((option,index)=>`<button data-quick="${index}" data-correct="${module.check.correct}">${option}</button>`).join("")}</div><p class="quick-feedback" aria-live="polite"></p></section><button class="complete-button" data-complete="${module.id}">${state.completed.has(module.id)?"Tappa completata ✓":"Segna come completata"}</button></article>`);
  }
  function answerQuick(button){const box=button.closest(".quick-check");if(box.dataset.answered)return;box.dataset.answered="true";const selected=Number(button.dataset.quick);const correct=Number(button.dataset.correct);$$('[data-quick]',box).forEach(item=>{item.disabled=true;if(Number(item.dataset.quick)===correct)item.classList.add("correct");else if(item===button)item.classList.add("wrong")});const module=data.modules.find(item=>item.id===button.closest("[data-open-module]").dataset.openModule);$(".quick-feedback",box).innerHTML=selected===correct?`<strong>Corretto.</strong> ${module.check.feedback}`:`<strong>Da rivedere.</strong> ${module.check.feedback}<br><small>${module.check.recovery}</small>`}
  function completeModule(id){state.completed.add(id);localStorage.setItem(keys.completed,JSON.stringify([...state.completed]));renderModules();updateProgress();const button=$(`[data-complete="${id}"]`);if(button)button.textContent="Tappa completata ✓";toast("Tappa salvata sul dispositivo")}
  function setMode(mode){state.mode=mode;localStorage.setItem(keys.mode,mode);$$('[data-mode]').forEach(button=>button.classList.toggle("active",button.dataset.mode===mode));$("#modeDescription").textContent=mode==="student"?"Argomenti, distinzioni, riferimenti testuali e problemi interpretativi.":"Spiegazioni chiare, esempi concreti e domande per entrare nel problema.";renderModules()}
  function updateProgress(){const percent=Math.round(state.completed.size/data.modules.length*100);$("#progressLabel").textContent=`${state.completed.size} di ${data.modules.length} tappe completate`;$("#progressPercent").textContent=`${percent}%`;$("#progressBar").style.width=`${percent}%`;$("#drawerProgress").textContent=`${percent}%`}

  function renderLab(){
    const item=data.labCases[state.labIndex];$("#labProgress").textContent=`Caso ${state.labIndex+1} di ${data.labCases.length}`;$("#labScore").textContent=`${state.labScore} classificazioni corrette`;
    $("#perceptionLab").innerHTML=`<article class="lab-case"><p class="eyebrow">Caso percettivo ${state.labIndex+1}</p><h3>${item.title}</h3><div class="lab-scene"><div class="lab-symbol" aria-hidden="true">${item.symbol}</div><p>${item.scene}</p></div><p><strong>${item.question}</strong></p><div class="lab-options">${item.options.map((option,index)=>`<button data-lab-answer="${index}">${option}</button>`).join("")}</div><div id="labFeedback" aria-live="polite"></div></article>`;
  }
  function answerLab(index){if(state.labAnswered)return;state.labAnswered=true;const item=data.labCases[state.labIndex];const correct=index===item.correct;if(correct)state.labScore+=1;$$('[data-lab-answer]').forEach((button,i)=>{button.disabled=true;if(i===item.correct)button.classList.add("correct");else if(i===index)button.classList.add("wrong")});$("#labScore").textContent=`${state.labScore} classificazioni corrette`;$("#labFeedback").innerHTML=`<div class="lab-feedback ${correct?"":"wrong"}"><strong>${correct?"Classificazione corretta":"Qui serve una distinzione in più"}</strong><p>${item.explanation}</p><button class="next-button" data-lab-next>${state.labIndex===data.labCases.length-1?"Ricomincia":"Caso successivo →"}</button></div>`}
  function nextLab(){if(state.labIndex===data.labCases.length-1){state.labIndex=0;state.labScore=0}else state.labIndex+=1;state.labAnswered=false;renderLab()}

  function renderSources(){$("#sourceGrid").innerHTML=data.sources.map(source=>`<article class="source-card"><span class="kind">${source.kind}</span><h3>${source.title}</h3><p>${source.text}</p><footer>${source.ref}</footer></article>`).join("")}
  function renderComics(){$("#comicStrip").innerHTML=data.comics.map((scene,index)=>`<article class="comic-card" data-scene="${String(index+1).padStart(2,"0")}"><div class="comic-visual" aria-hidden="true">${scene.icon}</div><time>${scene.year}</time><h3>${scene.title}</h3><p>${scene.text}</p><small>${scene.status}</small></article>`).join("")}
  function renderMap(){const map=data.maps.find(item=>item.id===state.map);$("#mapTabs").innerHTML=data.maps.map(item=>`<button role="tab" aria-selected="${item.id===state.map}" class="${item.id===state.map?"active":""}" data-map="${item.id}">${item.title}</button>`).join("");$("#conceptMap").innerHTML=`<p class="eyebrow">Mappa ${data.maps.indexOf(map)+1} di ${data.maps.length}</p><h3>${map.title}</h3><p>${map.intro}</p><div class="map-flow">${map.nodes.map(node=>`<div class="map-node"><strong>${node.title}</strong><p>${node.text}</p></div>`).join("")}</div>`}

  function glossaryHTML(){return `<p class="eyebrow dark">Dizionario filosofico</p><h2>Ventiquattro parole</h2><div class="glossary-grid">${data.glossary.map(([term,definition])=>`<article class="tool-item"><h3>${term}</h3><p>${definition}</p></article>`).join("")}</div>`}
  function timelineHTML(){return `<p class="eyebrow dark">Linea del tempo</p><h2>1685–1753</h2><div class="tool-list">${data.timeline.map(([year,event])=>`<article class="tool-item"><h3>${year}</h3><p>${event}</p></article>`).join("")}</div>`}
  function libraryHTML(){return `<p class="eyebrow dark">Biblioteca</p><h2>Orientarsi nelle opere</h2><div class="tool-list">${data.library.map(([title,year,text])=>`<article class="tool-item"><h3><cite>${title}</cite></h3><small>${year}</small><p>${text}</p></article>`).join("")}</div>`}
  function comparisonsHTML(){return `<p class="eyebrow dark">Confronti</p><h2>Locke, Berkeley, Hume e Kant</h2><p>La colonna “Dopo” segnala trasformazioni diverse, non una linea di derivazione automatica.</p><div class="comparison"><strong>Problema</strong><strong>Locke</strong><strong>Berkeley</strong><strong>Dopo</strong>${data.comparisons.map(row=>`<strong>${row.topic}</strong><span>${row.locke}</span><span>${row.berkeley}</span><span>${row.later}</span>`).join("")}</div>`}
  function academicSourcesHTML(){return `<p class="eyebrow dark">Fonti accademiche</p><h2>Solo università consultate</h2><p>Accesso verificato il 17 agosto 2026. Ogni collegamento indica il contenuto effettivamente sostenuto.</p><div class="tool-list">${data.academicSources.map(source=>`<article class="tool-item"><small>${source.institution}</small><h3><a href="${source.url}" target="_blank" rel="noreferrer">${source.title} ↗</a></h3><p>${source.supports}</p></article>`).join("")}</div>`}
  function quizHTML(indices=data.quiz.map((_,index)=>index)){state.quizAnswers={};return `<p class="eyebrow dark">Verifica finale</p><h2>${indices.length===data.quiz.length?"Dodici domande ragionate":"Ripeti gli errori"}</h2><p>Ogni alternativa riceve una spiegazione. Il punteggio orienta il recupero: non è un’etichetta.</p><div id="quizList">${indices.map(index=>{const item=data.quiz[index];return `<article class="tool-item quiz-question" data-quiz-question="${index}"><h3>${index+1}. ${item.q}</h3>${item.options.map((option,optionIndex)=>`<button class="quiz-option" data-quiz="${index}" data-option="${optionIndex}">${option}</button>`).join("")}<div class="quiz-feedback" aria-live="polite"></div></article>`}).join("")}</div><div id="quizSummary"></div>`}
  function answerQuiz(questionIndex,choice){if(Object.prototype.hasOwnProperty.call(state.quizAnswers,questionIndex))return;state.quizAnswers[questionIndex]=choice;const item=data.quiz[questionIndex];const article=$(`[data-quiz-question="${questionIndex}"]`);$$(`[data-quiz="${questionIndex}"]`,article).forEach(button=>{button.disabled=true;const option=Number(button.dataset.option);if(option===item.correct)button.classList.add("correct");else if(option===choice)button.classList.add("wrong")});$(".quiz-feedback",article).innerHTML=`<strong>${choice===item.correct?"Corretto":"Risposta da rivedere"}.</strong><ol>${item.options.map((option,index)=>`<li><strong>${index===item.correct?"Corretta":"Non corretta"}:</strong> ${item.why[index]}</li>`).join("")}</ol>`;renderQuizSummary()}
  function renderQuizSummary(){const visible=$$(".quiz-question").map(node=>Number(node.dataset.quizQuestion));if(!visible.every(index=>Object.prototype.hasOwnProperty.call(state.quizAnswers,index)))return;const wrong=visible.filter(index=>state.quizAnswers[index]!==data.quiz[index].correct);const correct=visible.length-wrong.length;const fragile=[...new Set(wrong.map(index=>data.quiz[index].module))];const acquired=[...new Set(visible.filter(index=>!wrong.includes(index)).map(index=>data.quiz[index].module))];$("#quizSummary").innerHTML=`<div class="quiz-summary"><h3>Esito: ${correct} / ${visible.length}</h3><p><strong>Nuclei acquisiti:</strong> ${acquired.length?acquired.map(id=>data.modules.find(module=>module.id===id).title).join(", "):"da consolidare"}.</p><p><strong>Nuclei fragili:</strong> ${fragile.length?fragile.map(id=>data.modules.find(module=>module.id===id).title).join(", "):"nessuno in questa prova"}.</p></div>${fragile.map(id=>{const module=data.modules.find(item=>item.id===id);return `<article class="recovery-card"><h4>Recupero · ${module.title}</h4><p>${module.amateur.summary}</p><p><strong>Nuovo esempio:</strong> ${module.amateur.example}</p><p><strong>Seconda domanda:</strong> ${module.check.question}</p><div class="quick-options" data-recovery="${id}">${module.check.options.map((option,index)=>`<button data-recovery-answer="${index}" data-correct="${module.check.correct}">${option}</button>`).join("")}</div><p class="quick-feedback"></p></article>`}).join("")}${wrong.length?`<button class="complete-button" data-retry="${wrong.join(",")}">Ripeti soltanto le ${wrong.length} domande sbagliate</button>`:`<p class="recovery-card"><strong>Percorso concluso.</strong> Hai distinto idee, spiriti, materia, realtà e funzione di Dio senza cadere nei fraintendimenti principali.</p>`}`}
  function answerRecovery(button){const group=button.closest("[data-recovery]");if(group.dataset.answered)return;group.dataset.answered="true";const choice=Number(button.dataset.recoveryAnswer);const correct=Number(button.dataset.correct);$$('[data-recovery-answer]',group).forEach((item,index)=>{item.disabled=true;if(index===correct)item.classList.add("correct");else if(item===button)item.classList.add("wrong")});const module=data.modules.find(item=>item.id===group.dataset.recovery);group.nextElementSibling.innerHTML=choice===correct?`<strong>Recupero riuscito.</strong> ${module.check.feedback}`:`<strong>Ancora un passaggio.</strong> ${module.check.recovery}`}
  function openTool(tool){const content={glossary:glossaryHTML,timeline:timelineHTML,library:libraryHTML,comparisons:comparisonsHTML,sources:academicSourcesHTML,quiz:quizHTML}[tool];if(content)showDialog(content())}

  function renderDrawer(){const links=[["#home","Copertina"],["#scopro","Scopro"],["#studio","Studio"],["#laboratorio","Laboratorio"],["#fonti","Approfondisco"],["#fumetti","A fumetti"],["#mappe","Mappe"],["#strumenti","Strumenti"]];$("#drawerNav").innerHTML=links.map(([href,label])=>`<a href="${href}">${label}</a>`).join("")}
  function toggleDrawer(open){$("#drawer").classList.toggle("open",open);$("#drawer").setAttribute("aria-hidden",String(!open));$("#menuButton").setAttribute("aria-expanded",String(open));if(open)$("#drawerClose").focus()}
  function toggleNotes(open){$("#notesPanel").classList.toggle("open",open);$("#notesPanel").setAttribute("aria-hidden",String(!open));if(open)$("#notesArea").focus()}
  function saveNotes(){localStorage.setItem(keys.notes,$("#notesArea").value);$("#notesStatus").textContent="Salvato";setTimeout(()=>$("#notesStatus").textContent="",1200)}
  function exportNotes(){const blob=new Blob([`Taccuino — George Berkeley\n\n${$("#notesArea").value}`],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="taccuino-berkeley.txt";link.click();URL.revokeObjectURL(url)}
  function search(query){const target=$("#searchResults");const term=query.trim().toLowerCase();if(term.length<2){target.innerHTML="";return}const results=[];data.modules.forEach(module=>{const hay=JSON.stringify(module).toLowerCase();if(hay.includes(term))results.push({type:"module",id:module.id,title:module.title,meta:"Tappa di studio"})});data.glossary.forEach(([name,definition])=>{if(`${name} ${definition}`.toLowerCase().includes(term))results.push({type:"glossary",id:name,title:name,meta:definition})});data.sources.forEach((source,index)=>{if(JSON.stringify(source).toLowerCase().includes(term))results.push({type:"source",id:index,title:source.title,meta:source.kind})});target.innerHTML=results.length?results.slice(0,14).map(result=>`<button class="search-result" data-search-type="${result.type}" data-search-id="${result.id}"><strong>${result.title}</strong><br><small>${result.meta}</small></button>`).join(""):`<p>Nessun risultato per “${esc(query)}”.</p>`}

  function bindEvents(){
    document.addEventListener("click",event=>{
      const hotspot=event.target.closest("[data-hotspot]");if(hotspot){const item=data.hotspots[hotspot.dataset.hotspot];showDialog(`<p class="eyebrow dark">Copertina interattiva</p><h2>${item.title}</h2><p>${item.text}</p>`);return}
      const discoveryChoice=event.target.closest("[data-discovery-choice]");if(discoveryChoice){chooseDiscovery(Number(discoveryChoice.dataset.discoveryChoice));return}
      if(event.target.closest("[data-discovery-next]")){nextDiscovery();return}
      const mode=event.target.closest("[data-mode]");if(mode){setMode(mode.dataset.mode);return}
      const module=event.target.closest("[data-module]");if(module){openModule(module.dataset.module);return}
      const quick=event.target.closest("[data-quick]");if(quick){answerQuick(quick);return}
      const complete=event.target.closest("[data-complete]");if(complete){completeModule(complete.dataset.complete);return}
      const labAnswer=event.target.closest("[data-lab-answer]");if(labAnswer){answerLab(Number(labAnswer.dataset.labAnswer));return}
      if(event.target.closest("[data-lab-next]")){nextLab();return}
      const map=event.target.closest("[data-map]");if(map){state.map=map.dataset.map;renderMap();return}
      const tool=event.target.closest("[data-tool]");if(tool){openTool(tool.dataset.tool);return}
      const quiz=event.target.closest("[data-quiz]");if(quiz){answerQuiz(Number(quiz.dataset.quiz),Number(quiz.dataset.option));return}
      const recovery=event.target.closest("[data-recovery-answer]");if(recovery){answerRecovery(recovery);return}
      const retry=event.target.closest("[data-retry]");if(retry){$("#dialogContent").innerHTML=quizHTML(retry.dataset.retry.split(",").map(Number));return}
      const result=event.target.closest("[data-search-type]");if(result){$("#searchDialog").close();if(result.dataset.searchType==="module")openModule(result.dataset.searchId);else if(result.dataset.searchType==="glossary")showDialog(glossaryHTML());else{$("#fonti").scrollIntoView();toast("Scheda trovata in Approfondisco")};return}
      if(event.target.closest('[data-close="drawer"]'))toggleDrawer(false)
    });
    $("#menuButton").addEventListener("click",()=>toggleDrawer(true));$("#indexButton").addEventListener("click",()=>toggleDrawer(true));$("#drawerClose").addEventListener("click",()=>toggleDrawer(false));$$('#drawerNav a').forEach(link=>link.addEventListener("click",()=>toggleDrawer(false)));
    $("#fontButton").addEventListener("click",()=>{const large=!document.body.classList.contains("large-text");document.body.classList.toggle("large-text",large);localStorage.setItem(keys.font,large?"large":"normal");toast(large?"Testo ingrandito":"Dimensione standard")});
    $("#notesButton").addEventListener("click",()=>toggleNotes(true));$("#notesClose").addEventListener("click",()=>toggleNotes(false));$("#notesArea").addEventListener("input",()=>{clearTimeout(saveNotes.timer);saveNotes.timer=setTimeout(saveNotes,350)});$("#exportNotes").addEventListener("click",exportNotes);
    $("#searchButton").addEventListener("click",()=>{$("#searchDialog").showModal();setTimeout(()=>$("#searchInput").focus(),30)});$("#searchClose").addEventListener("click",()=>$("#searchDialog").close());$("#searchInput").addEventListener("input",event=>search(event.target.value));$("#dialogClose").addEventListener("click",closeDialog);
    $("#installButton").addEventListener("click",async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null}else toast("Usa “Aggiungi alla schermata Home” dal menu del browser")});
    window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();state.deferredInstall=event});
    document.addEventListener("keydown",event=>{if(event.key==="Escape"){toggleDrawer(false);toggleNotes(false)}})
  }
  function init(){
    if(!data)throw new Error("Dati Berkeley non disponibili");
    $("#notesArea").value=localStorage.getItem(keys.notes)||"";if(localStorage.getItem(keys.font)==="large")document.body.classList.add("large-text");
    renderDiscovery();renderModules();renderLab();renderSources();renderComics();renderMap();renderDrawer();updateProgress();bindEvents();setMode(state.mode);
    if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"}).catch(error=>console.warn("Service worker non registrato",error)));
  }
  init();
})();
