window.BERKELEY_DATA={
  hotspots:{
    eye:{title:"Percepire non è copiare",text:"Berkeley parte da ciò che appare alla mente: colori, suoni, resistenze, piaceri e dolori. Chiamare queste idee «copie» di una materia invisibile non spiega l’esperienza: aggiunge un termine che non potremmo confrontare con ciò che percepiamo."},
    tree:{title:"L’albero non scompare",text:"L’immaterialismo non nega l’albero ordinario. Nega che, oltre all’insieme stabile e condivisibile delle qualità sensibili, serva una sostanza materiale per definizione impercepibile."},
    light:{title:"Un ordine che non dipende da noi",text:"Le idee dei sensi sono involontarie, vivide e ordinate. Berkeley ne attribuisce la causa a uno spirito infinito. Dio non è un’aggiunta decorativa: regge la causalità e la continuità del mondo."}
  },
  discovery:[
    {title:"Il giardino vuoto",prompt:"Chiudi la porta. Nel giardino non c’è alcun osservatore umano. Che cosa intendi quando dici che l’albero esiste ancora?",choices:[
      {label:"Esiste come materia, anche se nessuno la percepisce",title:"Hai introdotto un supporto invisibile",text:"Ora Berkeley ti chiederebbe: quali caratteristiche possiede questa materia, se ogni colore, forma, durezza e dimensione è conosciuta soltanto nella percezione?"},
      {label:"Esisterebbe se qualcuno entrasse nel giardino",title:"Hai scelto una regolarità possibile",text:"È una risposta vicina a un passaggio dei Principi: dire che il tavolo esiste può significare che lo percepiremmo nelle circostanze adatte. Resta da spiegare che cosa fonda questa possibilità."},
      {label:"Qualche mente deve percepirlo adesso",title:"Hai spostato il problema sul percipiente",text:"Questa via conduce alla funzione di Dio nei Dialoghi. Ma attenzione: dire soltanto «Dio lo vede» non elimina tutte le difficoltà sul modo in cui un essere infinito avrebbe idee sensibili."}
    ]},
    {title:"Che cosa percepisci?",prompt:"Guardi una mela. Quale elemento è immediatamente presente?",choices:[
      {label:"Colore, forma visiva, profumo e resistenza",title:"Sei rimasto nell’esperienza",text:"Sono idee sensibili. Berkeley dirà che il nome «mela» raccoglie qualità che ricorrono insieme secondo un ordine stabile."},
      {label:"La materia che sostiene tutte le qualità",title:"Hai formulato un’inferenza",text:"Il substrato non è visto, toccato o annusato. Berkeley contesta che questa inferenza abbia un contenuto intelligibile."},
      {label:"Una copia mentale e, dietro, la vera mela",title:"Hai adottato il rappresentazionalismo",text:"Se conosci soltanto la copia, come confronterai la copia con l’originale? Per Berkeley il velo delle idee alimenta lo scetticismo che pretendeva di evitare."}
    ]},
    {title:"Una qualità stabile?",prompt:"La stessa acqua sembra calda a una mano fredda e fresca a una mano calda. Dove si trova il calore?",choices:[
      {label:"Nell’esperienza relativa al percipiente",title:"È l’attacco alle qualità secondarie",text:"Berkeley usa casi di relatività per mostrare che caldo, freddo, sapore e colore non possono essere proprietà semplicemente identiche e assolute nell’oggetto materiale."},
      {label:"Una delle due mani deve avere torto",title:"Serve un criterio ulteriore",text:"Quale percezione rivela la qualità «vera»? Berkeley estende il dubbio a prospettiva, grandezza e moto, rendendo fragile la separazione fra qualità primarie e secondarie."}
    ]},
    {title:"Idea o spirito?",prompt:"Il colore verde è un’idea. Ma che cosa percepisce il verde?",choices:[
      {label:"Un’altra idea",title:"Le idee non agiscono",text:"Per Berkeley un’idea è passiva: può essere percepita, non può percepire. Occorre distinguere il percepito dal percipiente."},
      {label:"Una mente o spirito",title:"Hai trovato l’altro polo dell’ontologia",text:"Lo spirito è attivo: comprende e vuole. Non ne abbiamo un’immagine sensibile; ne abbiamo una nozione attraverso la nostra attività."}
    ]},
    {title:"Sogno o realtà",prompt:"Se tutto ciò che percepiamo sono idee, che cosa distingue il giardino reale da quello sognato?",choices:[
      {label:"Nulla: Berkeley rende tutto illusorio",title:"È il fraintendimento più comune",text:"Berkeley insiste sulla differenza: le idee reali sono più vivide, ordinate, coerenti e indipendenti dalla nostra volontà."},
      {label:"Ordine, vividezza, coerenza e involontarietà",title:"La realtà conserva criteri",text:"Il mondo reale non dipende dalla fantasia privata. Le regolarità condivise sono ciò che la scienza scopre e ciò che rende prevedibile l’esperienza."}
    ]},
    {title:"La posta in gioco",prompt:"Che cosa elimina davvero l’immaterialismo?",choices:[
      {label:"Gli alberi, le pietre e i corpi",title:"No: elimina la loro materia impercepibile",text:"Gli oggetti ordinari restano. Berkeley ne cambia l’ontologia: sono collezioni ordinate di idee, non sostanze materiali dietro le idee."},
      {label:"Un substrato materiale indipendente da ogni mente",title:"Hai raggiunto la tesi",text:"Per Berkeley la materia non è il mondo concreto: è una duplicazione teorica che produce scetticismo. La sua vittoria, però, dipende dalla tenuta degli argomenti su idee, spiriti e Dio."}
    ]}
  ],
  modules:[
    {id:"prima",number:"01",accent:"#c49b4d",kicker:"Il mondo precedente",title:"Locke, scienza ed esperienza",question:"Se conosciamo mediante idee, come raggiungiamo un mondo esterno?",amateur:{summary:"Berkeley eredita da Locke la centralità dell’esperienza, ma sospetta che la materia posta dietro le idee renda il mondo meno, non più, conoscibile.",narrative:"La filosofia moderna distingue spesso ciò che appare alla mente dalle cose materiali che dovrebbero causarlo. Locke ritiene che le idee delle qualità primarie possano somigliare alle qualità dei corpi, mentre colori e sapori dipendono dal modo in cui siamo affetti. Berkeley prende sul serio il punto di partenza empirico: se tutto ciò che conosciamo direttamente sono idee, con quale diritto affermiamo una sostanza che non è mai percepita? Non rifiuta l’esperienza; radicalizza la domanda su ciò che l’esperienza autorizza.",beats:["Le idee sono gli oggetti immediati della conoscenza.","La materia dovrebbe esistere indipendentemente dalla mente.","Il confronto fra idea e materia non può essere percepito.","Berkeley mira a bloccare scetticismo e materialismo."],example:"Se possiedi soltanto una fotografia e non puoi mai vedere l’originale, non puoi verificare la somiglianza. Berkeley contesta proprio questo ponte invisibile.",checkpoint:"Berkeley non abbandona l’empirismo: ne usa le premesse contro la sostanza materiale."},student:{summary:"L’obiettivo polemico è soprattutto il dualismo rappresentazionalista cartesiano e lockiano, non soltanto il materialismo riduzionista.",concepts:["Teoria delle idee","Rappresentazionalismo","Qualità primarie e secondarie","Sostanza materiale","Scetticismo"],argument:"Se percepiamo immediatamente idee, una pretesa somiglianza con un originale non ideale richiederebbe un confronto al quale non abbiamo accesso. Il cosiddetto likeness principle afferma inoltre che un’idea può somigliare soltanto a un’idea.",source:"Principles §§1–9; Stanford Encyclopedia of Philosophy, §§2–3; IEP, §§3–4.",warning:"Non attribuire a Locke una teoria ingenua della «copia»: la sua posizione è più articolata e discussa dagli studiosi."},check:{question:"Qual è la mossa iniziale di Berkeley?",options:["Negare che abbiamo percezioni","Usare l’empirismo per interrogare la materia impercepita","Sostituire l’esperienza con la matematica"],correct:1,feedback:"Berkeley conserva il punto di partenza empirico e mette in questione ciò che non può comparire nell’esperienza.",recovery:"Riparti dalla differenza fra ciò che è immediatamente percepito e ciò che viene soltanto postulato."}},
    {id:"vita",number:"02",accent:"#9e7f9f",kicker:"Biografia e contesto",title:"Irlanda, Trinity e contraddizioni",question:"Quanto della vita di un filosofo può spiegare la sua filosofia?",amateur:{summary:"Berkeley si forma al Trinity College Dublin, diventa chierico e vescovo, progetta un collegio missionario e partecipa al sistema coloniale e schiavista del suo tempo.",narrative:"Nato nel 1685 presso Kilkenny, entra al Trinity a quindici anni e diventa fellow nel 1707. Negli anni del college pubblica le opere che lo rendono celebre. In seguito tenta di fondare un collegio nelle Bermuda per formare missionari; attende invano i fondi governativi a Rhode Island. I documenti studiati da Trinity e Yale attestano che acquistò persone schiavizzate e sostenne un progetto assimilazionista. Questi fatti vanno detti senza attenuazioni, ma non autorizzano a trasformare la metafisica in un’allegoria automatica della politica.",beats:["1685: nascita presso Kilkenny.","1700–1724: formazione e incarichi al Trinity.","1729–1731: permanenza a Rhode Island.","1734: vescovo di Cloyne.","1753: morte a Oxford."],example:"Una biografia illumina problemi, interessi e scelte; non dimostra da sola la verità o la falsità di un argomento.",checkpoint:"Riconoscere la grandezza filosofica non richiede di cancellare le responsabilità storiche."},student:{summary:"La ricostruzione distingue tre piani: cronologia documentata, contesto istituzionale e interpretazione del rapporto fra vita e pensiero.",concepts:["Church of Ireland","Trinity College Dublin","Bermuda scheme","Colonialismo missionario","Schiavitù"],argument:"Il Working Paper di Trinity documenta incarichi, progetto americano, proprietà di Whitehall e acquisto di persone schiavizzate. La storia istituzionale di Yale conferma la connessione fra beneficenza universitaria e lavoro schiavizzato.",source:"Trinity College Dublin, Working Paper on Berkeley’s Legacies, 2023; Yale and Slavery, 2024.",warning:"Evita sia l’agiografia sia il determinismo biografico: il contesto non sostituisce l’analisi degli argomenti."},check:{question:"Quale affermazione è metodologicamente corretta?",options:["La proprietà di schiavi dimostra che l’immaterialismo è falso","La biografia va documentata e distinta dalla validità degli argomenti","La filosofia permette di ignorare le azioni storiche"],correct:1,feedback:"Responsabilità biografica e valutazione filosofica sono entrambe necessarie, ma non sono la stessa operazione.",recovery:"Distingui fatti documentati, contesto e interpretazione causale."}},
    {id:"visione",number:"03",accent:"#73a8b3",kicker:"Teoria della visione",title:"Impariamo a vedere la distanza",question:"La distanza è immediatamente visibile oppure viene suggerita dall’esperienza?",amateur:{summary:"Berkeley sostiene che distanza, grandezza e posizione non siano lette geometricamente dall’occhio: impariamo a collegare segni visivi e conseguenze tattili.",narrative:"Ciò che vediamo immediatamente comprende luce e colore. La profondità non è contenuta nell’immagine come un’etichetta: l’esperienza associa certe variazioni visive a movimenti, sforzi e sensazioni tattili. La vista funziona come un linguaggio: i segni visivi annunciano che cosa potremmo toccare o che cosa potrebbe giovare o danneggiare il corpo. La Nuova teoria della visione del 1709 prepara alcune distinzioni successive, ma non presuppone semplicemente tutto l’immaterialismo maturo.",beats:["La distanza non è immediatamente vista.","Vista e tatto hanno oggetti immediati distinti.","L’esperienza costruisce correlazioni stabili.","I segni visivi consentono previsione e azione."],example:"Un bambino impara che un’immagine visiva sempre più grande segnala l’avvicinarsi dell’oggetto: non risolve inconsciamente un teorema.",checkpoint:"Vedere è già interpretare segni appresi attraverso l’esperienza."},student:{summary:"La teoria anti-geometrica spiega distanza, grandezza e posizione mediante correlazioni acquisite fra idee visive e tangibili.",concepts:["Oggetti propri della vista","Idee tangibili","Distanza mediata","Linguaggio visivo","Problema di Molyneux"],argument:"Poiché la distanza è una linea diretta verso l’occhio, non proietta una grandezza visiva propria. Gli indizi visivi acquistano significato attraverso la connessione esperita con idee tattili e motorie.",source:"New Theory of Vision §§1–3, 51, 59, 147; IEP, Essays on Vision; SEP §4.1.",warning:"Il rapporto fra teoria della visione e immaterialismo è discusso: non presentare il testo del 1709 come semplice capitolo preliminare dei Principles."},check:{question:"Per Berkeley la distanza visiva è…",options:["calcolata da una geometria innata","immediatamente colorata","suggerita da correlazioni apprese"],correct:2,feedback:"La distanza è mediata dall’esperienza che connette segni visivi e idee tattili.",recovery:"Pensa alla vista come a un linguaggio: il segno non è ciò che significa."}},
    {id:"astrazione",number:"04",accent:"#a37da1",kicker:"Critica del linguaggio",title:"Il triangolo impossibile",question:"Per pensare in generale dobbiamo possedere immagini senza caratteristiche particolari?",amateur:{summary:"Berkeley rifiuta l’idea di un triangolo che sia insieme tutti i triangoli e nessuno in particolare. Un’idea particolare può funzionare come segno generale.",narrative:"Quando il geometra disegna un triangolo, il disegno è determinato: ha lati e angoli precisi. Eppure la dimostrazione può valere per ogni triangolo, perché trascura le caratteristiche irrilevanti. Berkeley sostiene quindi che la generalità dipende dall’uso rappresentativo di idee particolari, non dalla costruzione di immagini contraddittorie. Questa critica colpisce la materia astratta privata di tutte le qualità sensibili.",beats:["Ogni idea immaginata è determinata.","La generalità appartiene alla funzione del segno.","Possiamo considerare selettivamente un aspetto.","La materia totalmente priva di qualità perde contenuto."],example:"Il disegno di un cane preciso può rappresentare «il cane» in una lezione, senza diventare una figura che abbia tutte le razze e nessuna.",checkpoint:"Generale non significa visivamente indeterminato: significa capace di valere per molti casi."},student:{summary:"L’anti-astrazionismo contesta la teoria lockiana dell’idea generale astratta, non ogni capacità di generalizzare o distinguere aspetti.",concepts:["Idea particolare","Segno generale","Attenzione selettiva","Triangolo astratto","Nominalismo"],argument:"Se un’idea deve essere percepibile o immaginabile, un contenuto che combina determinazioni incompatibili non può costituire un’idea. La generalità è spiegata pragmaticamente dal riferimento indifferente a più particolari.",source:"Introduction to the Principles §§11–16; NTV §§122–127; IEP §3.",warning:"Berkeley non nega concetti generali e ragionamento matematico; nega un certo modello iconico dell’astrazione."},check:{question:"Come diventa generale un’idea particolare?",options:["Perde tutte le caratteristiche","Viene usata come segno per molti casi simili","Diventa una sostanza materiale"],correct:1,feedback:"La generalità è una funzione rappresentativa, non un’immagine priva di determinazioni.",recovery:"Ricorda il triangolo disegnato: particolare nella figura, generale nell’uso."}},
    {id:"qualita",number:"05",accent:"#b98162",kicker:"Primo attacco alla materia",title:"Caldo, colore, forma e moto",question:"Le qualità primarie possono restare fuori dalla mente se quelle secondarie dipendono dal percipiente?",amateur:{summary:"Berkeley estende gli argomenti di relatività da colore e calore a forma, grandezza e moto; inoltre sostiene che non possiamo immaginare estensione senza qualità sensibili.",narrative:"Locke distingue qualità primarie, come estensione e figura, da qualità secondarie, come colore e sapore. Berkeley osserva che anche grandezza e forma cambiano secondo distanza, prospettiva e strumenti. Soprattutto, non riusciamo a rappresentare un’estensione che non abbia alcun colore o altra qualità sensibile. La separazione teorica non coincide con una separazione concepibile.",beats:["Caldo e freddo variano con il percipiente.","La forma visiva varia con la prospettiva.","L’estensione non appare senza qualità sensibili.","Il criterio della distinzione perde fondamento."],example:"La stessa moneta appare circolare di fronte e ovale di sbieco: quale profilo è la forma visiva assoluta?",checkpoint:"Berkeley non dice che tutto è arbitrario: dice che tutte le qualità sensibili appartengono all’esperienza."},student:{summary:"Gli argomenti combinano relatività percettiva e inseparabilità concepibile delle qualità primarie e secondarie.",concepts:["Relatività percettiva","Inseparabilità","Qualità primarie","Qualità secondarie","Microscopio"],argument:"Se estensione e moto non possono essere concepiti senza una qualità sensibile ammessa come mind-dependent, manca il fondamento per attribuirli a un substrato non percepito. Gli argomenti, però, restano contestabili.",source:"Principles §§9–15; First Dialogue; SEP §2.2; IEP §4.",warning:"La variazione dell’apparenza non prova automaticamente che non esista una proprietà disposizionale dell’oggetto: è una pressione argomentativa, non una formula magica."},check:{question:"Perché la distinzione di Locke vacilla?",options:["Perché non esistono differenze percettive","Perché le qualità primarie sono inseparabili dalle secondarie nell’idea","Perché Berkeley rifiuta la geometria"],correct:1,feedback:"L’inseparabilità nell’esperienza e la relatività indeboliscono il privilegio delle qualità primarie.",recovery:"Prova a immaginare una figura estesa che non abbia alcuna qualità sensibile."}},
    {id:"materia",number:"06",accent:"#8d8a66",kicker:"Immaterialismo",title:"Il substrato che nessuno incontra",question:"Che cosa aggiunge la materia alle qualità che percepiamo?",amateur:{summary:"La materia è definita come supporto delle qualità, ma il supporto non è una qualità e non può essere percepito. Berkeley lo considera un’aggiunta vuota.",narrative:"Diciamo che il tavolo è duro, marrone, esteso e resistente. Se togliamo tutte queste qualità perché sono idee, resta una «cosa» che dovrebbe sostenerle senza possederne alcuna in modo percepibile. Berkeley non conclude che il tavolo non esiste; conclude che la sostanza materiale separata dalle qualità non svolge un lavoro intelligibile. Il tavolo ordinario è proprio l’insieme ordinato che vediamo e tocchiamo.",beats:["Il substrato non è una qualità sensibile.","Non può essere confrontato con un’idea.","Non spiega come cause non mentali producano idee.","Gli oggetti ordinari restano collezioni stabili di idee."],example:"Dopo aver tolto buccia, polpa, profumo, sapore, forma e peso da una mela, chiamare il resto «la vera mela» non chiarisce che cosa sia rimasto.",checkpoint:"Immaterialismo non significa eliminazione degli oggetti, ma rifiuto della materia mind-independent."},student:{summary:"La critica combina likeness principle, anti-astrazionismo e insufficienza esplicativa del substratum.",concepts:["Substratum","Mind-independence","Likeness principle","Causalità","Parsimonia"],argument:"Una sostanza definita solo come incognito supporto non è oggetto di idea né termine dotato di contenuto determinato. Inoltre, essendo concepita come passiva, non spiega causalmente le idee.",source:"Principles §§8–24; SEP §2.1; IEP §4.",warning:"La critica mostra che una certa concezione della materia è problematica; non obbliga senza ulteriori argomenti ogni forma di realismo contemporaneo."},check:{question:"Che cosa nega Berkeley?",options:["Il tavolo percepito","La regolarità naturale","Una sostanza materiale indipendente e impercepibile"],correct:2,feedback:"Il bersaglio è la materia come supporto mind-independent, non l’oggetto ordinario.",recovery:"Separa «mondo fisico percepito» e «sostanza materiale postulata»."}},
    {id:"esse",number:"07",accent:"#d0ab4f",kicker:"La tesi celebre",title:"Esse est percipi",question:"In che senso l’esistenza delle cose sensibili consiste nell’essere percepite?",amateur:{summary:"Colori, suoni, resistenze e forme esistono come idee presenti a una mente. Per le cose sensibili, essere significa essere percepite.",narrative:"Berkeley chiama «cosa» un gruppo di idee che ricorre insieme: la mela è colore, sapore, profumo, consistenza e altre possibilità ordinate. Non esiste una seconda mela nascosta dietro la prima. La formula esse est percipi riguarda le cose non pensanti. Applicarla alla mente sarebbe un errore, perché la mente esiste come ciò che percepisce e vuole.",beats:["Le idee esistono nell’essere percepite.","Gli oggetti sono collezioni ordinate di idee.","La realtà non equivale alla fantasia personale.","Lo spirito non è un’idea percepita."],example:"La pietra è perfettamente reale: durezza, peso, colore e dolore del calcio sono esperienze non arbitrarie. Berkeley nega soltanto una pietra ulteriore e impercepibile.",checkpoint:"La formula completa distingue percipi e percipere: percepito e percepiente."},student:{summary:"L’ontologia ammette idee passive e spiriti attivi; gli oggetti fisici sono bundle di idee individuati da co-occorrenza e denominazione.",concepts:["Esse est percipi","Aut percipere","Bundle di idee","Oggetto ordinario","Idealismo"],argument:"Dato che gli oggetti sensibili sono ciò che percepiamo e percepiamo immediatamente idee, Berkeley identifica gli oggetti ordinari con collezioni di idee, contestando la mediazione materiale.",source:"Principles §§1–7; SEP §§2.1 e 3.1; IEP §4.",warning:"«Essere è essere percepito» non vale senza distinzione per gli spiriti: essi sono soggetti attivi, non contenuti sensibili."},check:{question:"A che cosa si applica direttamente esse est percipi?",options:["Alle idee e cose sensibili","Soltanto a Dio","Agli spiriti nello stesso modo"],correct:0,feedback:"Le cose sensibili esistono come percepite; gli spiriti esistono come percepienti e volenti.",recovery:"Scrivi due colonne: idea passiva / spirito attivo."}},
    {id:"spiriti",number:"08",accent:"#79a99a",kicker:"L’altro polo",title:"Idee passive, spiriti attivi",question:"Se un’idea non può agire, chi percepisce e chi causa?",amateur:{summary:"Le idee sono contenuti passivi. Lo spirito comprende e vuole; non è un’immagine mentale, ma il soggetto dell’esperienza.",narrative:"Un colore non vede e un dolore non decide. Berkeley chiama spirito l’essere semplice e attivo che percepisce idee e opera attraverso la volontà. Non possiamo avere un’idea dello spirito, perché un’immagine passiva non può somigliare a un principio attivo. Possiamo però averne una nozione a partire dal nostro stesso percepire e volere. Questo punto rende il sistema meno semplice di quanto sembri e apre difficoltà serie.",beats:["Idea: passiva e percepita.","Spirito: attivo e percepiente.","La mente non è una figura interna.","La nozione non è un’idea sensibile."],example:"Puoi rappresentare il suono di una campana; non puoi rappresentare come suono il soggetto che lo ascolta.",checkpoint:"Berkeley sostituisce il dualismo mente-materia con la distinzione mente-idea."},student:{summary:"La teoria delle notions, esplicitata nelle edizioni del 1734, tenta di spiegare la conoscenza di sé e degli spiriti senza ridurli a idee.",concepts:["Spirito","Volontà","Intelletto","Nozione","Attività"],argument:"Poiché le idee sono inerti, non possono causare né percepire. L’esperienza della nostra attività fornisce il modello semantico per parlare di spiriti finiti e, analogicamente, di Dio.",source:"Principles §§25–27, 89, 139–142; SEP §§3.1.2 e 3.2.6; IEP §5.",warning:"Il concetto di spirito non è privo di problemi: il materialista può accusarlo di somigliare al substrato impercepibile che Berkeley rifiuta."},check:{question:"Perché non abbiamo un’idea dello spirito?",options:["Perché lo spirito non esiste","Perché un’idea passiva non rappresenta un principio attivo","Perché tutte le idee sono false"],correct:1,feedback:"Lo spirito è conosciuto come attività, non raffigurato come contenuto sensibile.",recovery:"Distingui ciò che appare da colui al quale appare."}},
    {id:"dio",number:"09",accent:"#d1b275",kicker:"Il garante",title:"Dio e l’ordine del reale",question:"Da dove vengono le idee sensibili che non controlliamo?",amateur:{summary:"Le percezioni sensibili sono involontarie, vivide e regolari. Berkeley le attribuisce a uno spirito diverso e infinitamente più potente: Dio.",narrative:"Posso immaginare una mela blu, ma non posso decidere che il muro davanti a me scompaia. Le idee dei sensi si impongono secondo regole. Non possono essere causate da altre idee, perché le idee sono passive; non dipendono interamente dalla mia volontà. Berkeley conclude che provengono da un altro spirito. La vastità e l’ordine dell’esperienza lo conducono allo spirito infinito. Dio spiega anche perché possiamo parlare di oggetti non percepiti da una mente umana, ma la modalità precisa della continuità resta discussa.",beats:["Le idee sensibili non sono volontarie.","Le idee non hanno potere causale.","Occorre un altro spirito come causa.","Regolarità e complessità conducono a Dio."],example:"Puoi scegliere di immaginare il sole spento; non puoi spegnerlo con un atto di volontà. La differenza segnala una causa non finita.",checkpoint:"Dio è interno alla struttura causale del sistema, non una decorazione religiosa."},student:{summary:"L’argomento procede per eliminazione: idee passive, io finito insufficiente, altro spirito; dalla sistematicità si inferisce lo spirito infinito.",concepts:["Involontarietà","Causa spirituale","Leggi di natura","Percezione divina","Decreto divino"],argument:"PHK 25 elimina la causalità delle idee; PHK 29–33 distingue senso e immaginazione. Nei Dialoghi, Berkeley collega inoltre continuità e mente divina, generando problemi interpretativi sulle idee di Dio.",source:"Principles §§25–33, 48; Three Dialogues, pp. 212–215, 253; SEP §§3.1.3 e 3.2.4.",warning:"Non ridurre la soluzione a «Dio guarda tutto»: gli studiosi discutono se la continuità dipenda da percezione, volontà o decreti divini."},check:{question:"Quale proprietà distingue le idee sensibili dalla fantasia?",options:["Sono sempre piacevoli","Sono ordinate e indipendenti dalla nostra volontà","Sono materiali"],correct:1,feedback:"Vividezza, ordine, coerenza e involontarietà fondano la distinzione.",recovery:"Confronta una mela immaginata con quella che resiste al tuo gesto."}},
    {id:"obiezioni",number:"10",accent:"#b96f65",kicker:"Mettere il sistema sotto pressione",title:"Sogno, errore, solipsismo",question:"Se gli oggetti sono idee, come distinguiamo realtà, illusione e punti di vista diversi?",amateur:{summary:"Berkeley risponde con ordine e coerenza: il sogno non possiede la stabilità del mondo condiviso. L’errore riguarda spesso ciò che inferiamo, non l’idea presente.",narrative:"Un remo nell’acqua appare piegato: la percezione visiva non mente su ciò che appare; sbaglieresti prevedendo che, estratto, continuerà ad apparire e a farsi toccare come piegato. La realtà è un sistema di percezioni connesse da regole. Due persone non possiedono numericamente la stessa idea, ma possono parlare dello stesso oggetto perché le loro esperienze appartengono allo stesso insieme ordinato. Il problema resta filosoficamente impegnativo.",beats:["Il sogno manca dell’ordine stabile del senso.","Errore significa inferenza o previsione fallita.","Gli oggetti raccolgono molte idee possibili.","Il mondo non dipende dalla volontà del singolo."],example:"Vedi una torre rotonda da lontano e quadrata da vicino: non hai due mondi, ma percezioni diverse inserite in una regola di esplorazione.",checkpoint:"Mind-dependent non significa dipendente dalla mia mente privata."},student:{summary:"Le risposte combinano criteri fenomenologici, regolarità nomologica, bundle theory e senso «volgare» dell’identità.",concepts:["Reale/immaginario","Errore inferenziale","Identità dell’oggetto","Inter-soggettività","Solipsismo"],argument:"Le idee reali sono stabili, vivide, ordinate e non volontarie; l’errore sorge nelle inferenze su altre idee attese. L’identità condivisa viene spiegata mediante bundle e regolarità, ma resta una difficoltà teorica.",source:"Principles §§29–34; Three Dialogues, p. 238; SEP §§3.2.1, 3.2.4–5.",warning:"Non dichiarare «risolto» il problema dell’oggetto comune: la ricostruzione è interpretativa e contestata."},check:{question:"Dove si colloca l’errore del remo piegato?",options:["Nell’idea visiva presente","Nell’inferenza su come apparirà e si farà toccare","Nell’esistenza dell’acqua"],correct:1,feedback:"L’apparenza è quella che è; può essere errata la previsione che ne ricaviamo.",recovery:"Separa percezione attuale e aspettativa su percezioni future."}},
    {id:"opere",number:"11",accent:"#7c9eaa",kicker:"Scrivere per convincere",title:"Principi e Dialoghi",question:"Perché lo stesso sistema viene esposto prima come trattato e poi come dialogo?",amateur:{summary:"I Principi costruiscono l’argomento in forma serrata; i Dialoghi fanno vivere obiezioni e resistenze attraverso Hylas e Philonous.",narrative:"Nel 1710 Berkeley pubblica il Trattato sui principi della conoscenza umana. Il testo definisce le idee, critica materia e astrazione, distingue spiriti e idee e affronta obiezioni. Tre anni dopo i Dialoghi rendono il confronto più concreto: Hylas, «materia», difende il realismo; Philonous, «amante dello spirito», lo conduce attraverso calore, sapore, forma e continuità. La forma dialogica non è un ornamento: mostra la pressione progressiva dell’argomento.",beats:["Principles: architettura sistematica.","Dialogues: obiezioni in scena.","Hylas incarna la resistenza materialista.","Philonous rappresenta la strategia berkeleyana."],example:"Un trattato presenta la mappa; un dialogo ti fa percorrere la strada e inciampare nelle obiezioni.",checkpoint:"La forma letteraria modifica il modo in cui il lettore sperimenta la necessità dell’argomento."},student:{summary:"Il passaggio di genere risponde anche alla ricezione incomprensiva dei Principles e consente una dialettica più ricca con realismo diretto e rappresentazionalismo.",concepts:["PHK","Three Dialogues","Hylas","Philonous","Strategia dialogica"],argument:"Il primo Dialogo usa argomenti di relatività contro il realismo ingenuo; i successivi riformulano materia, Dio, scienza e senso comune, permettendo a Berkeley di separare tesi e risposte.",source:"Principles, 1710; Three Dialogues, 1713; SEP §§2–3; IEP, Life and Works.",warning:"Hylas non è un semplice sciocco: le sue obiezioni conservano problemi che il sistema non neutralizza definitivamente."},check:{question:"Che funzione ha la forma dialogica?",options:["Sostituisce gli argomenti con una storia","Mette in scena obiezioni e passaggi dell’argomento","Nasconde il ruolo di Dio"],correct:1,feedback:"Il dialogo trasforma l’esposizione in un percorso di resistenza e risposta.",recovery:"Confronta una tesi dichiarata con una tesi conquistata attraverso obiezioni."}},
    {id:"eredita",number:"12",accent:"#8b80b0",kicker:"Eredità e confini",title:"Da Berkeley a Hume e Kant",question:"Che cosa resta dell’immaterialismo quando altri filosofi ne accettano alcune mosse e ne rifiutano il fondamento?",amateur:{summary:"Berkeley influenza Hume e costringe Kant a distinguere il proprio idealismo. Ma non è un precursore della fisica quantistica né della teoria della simulazione.",narrative:"Hume raccoglie la critica empiristica delle sostanze e la spinge verso esiti che Berkeley non avrebbe accettato, mettendo sotto pressione anche il sé e la causalità. Kant considera Berkeley un avversario da cui distinguere l’idealismo trascendentale: il fatto che conosciamo fenomeni non significa per Kant che gli oggetti siano semplicemente idee private. L’eredità più feconda di Berkeley è la domanda sul rapporto fra esperienza, oggettività e realtà. I paralleli con la quantistica confondono la misura fisica con uno sguardo cosciente e non vengono usati qui.",beats:["Hume radicalizza la critica empiristica.","Kant distingue idealismo empirico e trascendentale.","L’influenza non equivale a identità.","Quantistica e simulazione non provano Berkeley."],example:"Un filosofo può rendere inevitabile una domanda anche quando quasi nessuno accetta la sua risposta.",checkpoint:"L’eredità di Berkeley è un problema aperto sulla realtà, non una profezia scientifica."},student:{summary:"La ricezione va formulata come influenza selettiva e contrasto: Hume e Kant non sono conclusioni lineari del berkeleismo.",concepts:["Scetticismo humeano","Bundle theory","Idealismo trascendentale","Realismo empirico","Anacronismo"],argument:"Berkeley dissolve la materia lockiana mantenendo spiriti e Dio; Hume sottopone anche tali nozioni a critica; Kant riconfigura la dipendenza delle condizioni conoscitive senza ridurre il mondo empirico a contenuto privato.",source:"SEP, introduzione e bibliografia; IEP, British Empiricism; confronti testuali con Kant da trattare come distinzione critica.",warning:"Evita la catena semplicistica Berkeley → Hume → Kant e ogni uso dell’«osservatore» quantistico come mente cosciente."},check:{question:"Qual è la formulazione storicamente corretta?",options:["Berkeley inventa la meccanica quantistica","Hume e Kant ripetono Berkeley","Berkeley influenza e provoca risposte differenti"],correct:2,feedback:"Influenza significa selezione, trasformazione e spesso rifiuto di parti del sistema.",recovery:"Sostituisci la linea retta con tre operazioni: accogliere, trasformare, contestare."}}
  ],
  labCases:[
    {symbol:"◐",title:"La moneta obliqua",scene:"Una moneta circolare, osservata di sbieco, appare ovale.",question:"Che cosa è immediatamente percepito?",options:["La forma visiva ovale","La forma materiale assoluta","Il calcolo geometrico inconsapevole","La sostanza della moneta"],correct:0,explanation:"È data l’idea visiva ovale. La circolarità è collegata ad altre viste e al tatto: è una previsione ordinata, non un dato visivo nascosto."},
    {symbol:"≈",title:"Le due mani",scene:"Una mano fredda e una calda entrano nella stessa acqua tiepida: la prima avverte calore, la seconda freschezza.",question:"Quale classificazione segue l’argomento di Berkeley?",options:["Due sostanze materiali diverse","Qualità relativa al percipiente","Una mano non percepisce nulla","Il calore è un’idea astratta"],correct:1,explanation:"Il caso mette sotto pressione l’idea di un calore unico, identico e indipendente. Non mostra che l’esperienza sia arbitraria."},
    {symbol:"↔",title:"La torre lontana",scene:"Da lontano la torre sembra rotonda; avvicinandoti la vedi quadrata.",question:"Dove si trova l’errore?",options:["Nella prima idea visiva","Nel cambiamento di posizione","Nell’inferenza che resterà rotonda da vicino","In ogni percezione"],correct:2,explanation:"Per Berkeley la percezione attuale non mente su se stessa. È falsa la previsione che ignora le regole che connettono punti di vista diversi."},
    {symbol:"☾",title:"Il giardino sognato",scene:"Nel sogno attraversi un giardino vivido, ma gli eventi mutano senza regole stabili.",question:"Quale criterio separa il sogno dal giardino reale?",options:["Il sogno non contiene idee","Ordine, coerenza e indipendenza dalla volontà","Il reale è sempre più colorato","La materia del sogno pesa meno"],correct:1,explanation:"Le idee del senso appartengono a un sistema regolare e condivisibile; la fantasia è più dipendente dal soggetto e meno coerente."},
    {symbol:"□",title:"La stanza chiusa",scene:"Nessuna mente umana entra nella stanza per un’ora.",question:"Quale risposta è più accurata?",options:["Per Berkeley la stanza è annientata e ricreata a caso","La regolarità e lo spirito divino fondano ciò che percepiremmo","La materia si percepisce da sola","Non esistono differenze fra possibile e reale"],correct:1,explanation:"Berkeley richiama regolarità, percepibilità e Dio. La continuità precisa resta un problema interpretativo: non va banalizzata."},
    {symbol:"✦",title:"Il colore sotto la lampada",scene:"Una stoffa verde appare quasi nera in penombra e brillante sotto una lampada.",question:"Che cosa aggiunge la sostanza materiale alla descrizione immediata?",options:["Un colore vero visibile soltanto alla materia","Una causa che percepiamo direttamente","Nulla che compaia come qualità sensibile","La volontà della stoffa"],correct:2,explanation:"Berkeley non nega la stoffa o le regole ottiche; contesta il bisogno di un supporto impercepibile oltre la serie ordinata delle idee."}
  ],
  sources:[
    {kind:"Fonte primaria",title:"La Nuova teoria della visione",text:"Distanza, grandezza e posizione vengono spiegate attraverso connessioni apprese fra idee visive e tattili. La teoria non va retroproiettata senza cautele sull’intero immaterialismo.",ref:"NTV §§1–3, 51, 59, 147"},
    {kind:"Fonte primaria",title:"L’Introduzione ai Principi",text:"Berkeley critica l’idea generale astratta: un’idea particolare può rappresentare molti casi senza diventare un’immagine contraddittoria.",ref:"Introduction §§11–16"},
    {kind:"Fonte primaria",title:"I Principi",text:"Il testo presenta oggetti della conoscenza, esse est percipi, critica della materia, distinzione fra idee e spiriti, causalità divina e obiezioni.",ref:"PHK §§1–34, 89, 105, 139–142"},
    {kind:"Fonte primaria",title:"I Tre dialoghi",text:"Hylas e Philonous attraversano relatività percettiva, materia, identità dell’oggetto, Dio e senso comune. La forma dialogica rende visibili resistenze reali.",ref:"Three Dialogues, 1713"},
    {kind:"Interpretazione",title:"Dio e continuità",text:"La lettura secondo cui Dio semplicemente «vede sempre tutto» incontra difficoltà: percezione, volontà e decreti divini sono distinti nelle ricostruzioni contemporanee.",ref:"Stanford Encyclopedia of Philosophy, §3.2.4"},
    {kind:"Problema aperto",title:"Il Master Argument",text:"Dal fatto che devo pensare un albero per concepirlo non segue senza discussione che l’albero concepito non possa essere mind-independent. La SEP presenta anche questa obiezione.",ref:"Principles §§22–23; SEP §2.2.1"},
    {kind:"Ricostruzione",title:"Berkeley e la schiavitù",text:"Fonti istituzionali di Trinity e Yale documentano proprietà di persone schiavizzate, progetto missionario assimilazionista e memoria universitaria controversa.",ref:"TCD Working Paper, 2023; Yale and Slavery, 2024"},
    {kind:"Scelta editoriale",title:"Perché non c’è la quantistica",text:"L’osservatore della teoria quantistica non equivale a una mente cosciente. Un’analogia vaga non è una continuità storica né una prova dell’immaterialismo.",ref:"Esclusione motivata: nessuna fonte universitaria consultata autorizza quella conclusione"}
  ],
  comics:[
    {year:"1685–1700",icon:"⌂",title:"Kilkenny",text:"Nasce presso Kilkenny e studia al Kilkenny College prima di entrare giovanissimo al Trinity.",status:"Documentato"},
    {year:"1700–1709",icon:"▥",title:"Trinity College",text:"Studia, diventa fellow e ricopre incarichi accademici. Nel 1709 è anche bibliotecario.",status:"Documentato"},
    {year:"1709",icon:"◉",title:"Imparare a vedere",text:"Pubblica la Nuova teoria della visione: la distanza è suggerita da correlazioni apprese.",status:"Documentato"},
    {year:"1710",icon:"◇",title:"I Principi",text:"Attacca astrazione e materia, presenta idee, spiriti e il nucleo dell’immaterialismo.",status:"Documentato"},
    {year:"1713",icon:"◌",title:"Hylas e Philonous",text:"Il confronto dialogico trasforma le obiezioni del lettore in tappe dell’argomento.",status:"Ricostruzione visuale"},
    {year:"1724–1731",icon:"⚓",title:"Il progetto americano",text:"Progetta il collegio nelle Bermuda e attende a Rhode Island fondi che non arriveranno.",status:"Documentato"},
    {year:"1730–1731",icon:"⛓",title:"Whitehall",text:"Acquista persone schiavizzate. Il progetto missionario è intrecciato a colonialismo e assimilazione.",status:"Documentato da TCD e Yale"},
    {year:"1734–1753",icon:"✧",title:"Cloyne e Oxford",text:"Diventa vescovo di Cloyne, pubblica The Querist e Siris; muore a Oxford nel 1753.",status:"Documentato"}
  ],
  maps:[
    {id:"locke",title:"Da Locke a Berkeley",intro:"La stessa premessa empirica cambia direzione.",nodes:[{title:"Idee",text:"Oggetti immediati della conoscenza."},{title:"Somiglianza?",text:"Come confrontare l’idea con la materia non percepita?"},{title:"Immaterialismo",text:"L’oggetto ordinario è una collezione di idee."}]},
    {id:"qualita",title:"Le qualità",intro:"La frontiera fra primario e secondario si dissolve.",nodes:[{title:"Colore e calore",text:"Dipendono dal percipiente."},{title:"Forma e moto",text:"Variano con prospettiva e riferimento."},{title:"Inseparabilità",text:"Non concepiamo estensione senza qualità sensibili."}]},
    {id:"ontologia",title:"Idea → percezione → spirito",intro:"Due nature, non una sola sostanza.",nodes:[{title:"Idea",text:"Passiva, percepita, senza causalità."},{title:"Percepire",text:"Relazione in cui l’idea esiste."},{title:"Spirito",text:"Attivo, comprende e vuole."}]},
    {id:"materia",title:"La critica della materia",intro:"Il substrato perde funzione e contenuto.",nodes:[{title:"Qualità sensibili",text:"Sono idee."},{title:"Supporto ignoto",text:"Non è percepito né rappresentabile."},{title:"Economia ontologica",text:"Resta il mondo fisico, non la materia indipendente."}]},
    {id:"dio",title:"Dio e permanenza",intro:"Causalità e continuità non sono la stessa domanda.",nodes:[{title:"Idee involontarie",text:"Non dipendono dalla mia volontà."},{title:"Altro spirito",text:"Deve causare l’ordine sensibile."},{title:"Dio",text:"Spirito infinito; percezione e decreto restano discussi."}]},
    {id:"obiezioni",title:"Obiezione → risposta",intro:"Il sistema vive sotto pressione.",nodes:[{title:"Tutto è sogno",text:"Obiezione: nessuna realtà esterna."},{title:"Ordine",text:"Risposta: vividezza, coerenza, involontarietà."},{title:"Problema residuo",text:"Identità condivisa e continuità richiedono teoria."}]},
    {id:"eredita",title:"Berkeley → Hume → Kant",intro:"Influenza non significa ripetizione.",nodes:[{title:"Berkeley",text:"Critica materia, conserva spiriti e Dio."},{title:"Hume",text:"Radicalizza la critica empiristica."},{title:"Kant",text:"Ridefinisce idealismo e oggettività trascendentale."}]}
  ],
  glossary:[
    ["Astrazione","Operazione con cui si separano caratteristiche; Berkeley contesta l’idea astratta intesa come immagine indeterminata."],["Aut percipere","«O percepire»: integrazione necessaria per ricordare che gli spiriti non esistono come idee percepite."],["Bundle","Insieme stabile di idee che chiamiamo oggetto."],["Causalità","Potere attivo che Berkeley attribuisce agli spiriti, non alle idee passive."],["De Motu","Opera del 1721 sulla natura del moto e sul linguaggio della scienza."],["Esse est percipi","Per le cose sensibili, essere consiste nell’essere percepite."],["Hylas","Interlocutore materialista dei Dialoghi; il nome rinvia alla materia."],["Idea","Contenuto passivo percepito: colore, suono, resistenza, immagine o ricordo."],["Idealismo","Tesi secondo cui la realtà comprende menti e contenuti dipendenti dalla mente."],["Immaterialismo","Negazione di una sostanza materiale indipendente dalla mente."],["Involontarietà","Carattere delle idee sensibili che non possiamo produrre o modificare a piacere."],["Likeness principle","Principio secondo cui un’idea può somigliare soltanto a un’idea."],["Materia","Presunta sostanza mind-independent che Berkeley giudica priva di contenuto intelligibile."],["Master Argument","Argomento sulla pretesa inconcepibilità di un oggetto esistente senza essere concepito."],["Mind-dependent","Dipendente dall’esistenza o attività di una mente; non significa arbitrario o privato."],["Nozione","Modo in cui Berkeley parla della conoscenza dello spirito senza ridurlo a idea sensibile."],["Oggetto ordinario","Collezione coerente di idee, come mela, pietra o albero."],["Philonous","«Amante dello spirito», portavoce di Berkeley nei Dialoghi."],["Qualità primaria","Per Locke: solidità, estensione, figura, numero e mobilità, attribuite ai corpi stessi."],["Qualità secondaria","Colore, suono, sapore, caldo e altre qualità dipendenti dal modo in cui percepiamo."],["Rappresentazionalismo","Teoria secondo cui percepiamo le cose materiali mediante idee che le rappresentano."],["Segno visivo","Idea della vista che suggerisce una possibile idea tattile o conseguenza pratica."],["Spirito","Essere attivo che percepisce e vuole; può essere finito o infinito."],["Substratum","Supporto delle qualità postulato dalla teoria della sostanza materiale."]
  ],
  timeline:[
    ["1685","Nasce presso Kilkenny, in Irlanda."],["1700","Entra al Trinity College Dublin."],["1707","Diventa fellow del Trinity."],["1709","Pubblica An Essay Towards a New Theory of Vision."],["1710","Pubblica A Treatise Concerning the Principles of Human Knowledge."],["1713","Pubblica Three Dialogues between Hylas and Philonous."],["1721","Pubblica De Motu."],["1724","Diventa decano di Derry e promuove il progetto delle Bermuda."],["1729–1731","Vive a Rhode Island; acquista Whitehall e persone schiavizzate."],["1732","Rientra in Europa dopo il mancato finanziamento del progetto."],["1734","Diventa vescovo di Cloyne."],["1744","Pubblica Siris."],["1753","Muore a Oxford."]
  ],
  library:[
    ["An Essay Towards a New Theory of Vision","1709","Distanza, grandezza, posizione e linguaggio visivo."],["A Treatise Concerning the Principles of Human Knowledge","1710; rev. 1734","Esposizione dell’immaterialismo e delle sue conseguenze."],["Three Dialogues between Hylas and Philonous","1713; rev. 1734","Difesa dialogica dell’idealismo e del senso comune."],["Passive Obedience","1712","Filosofia morale e politica."],["De Motu","1721","Critica di concetti assoluti di forza e causa nella scienza del moto."],["Alciphron","1732","Dialoghi in difesa del cristianesimo contro i liberi pensatori."],["The Querist","1735–1737","Domande e proposte sull’economia irlandese."],["Siris","1744","Catena di riflessioni che muove dall’acqua di catrame a temi metafisici." ]
  ],
  comparisons:[
    {topic:"Oggetto",locke:"Sostanza materiale con qualità; l’essenza reale resta ignota.",berkeley:"Collezione ordinata di idee dipendenti dalla mente.",later:"Hume sospende la sostanza; Kant distingue fenomeno e cosa in sé."},
    {topic:"Mente",locke:"Sostanza pensante conosciuta attraverso riflessione.",berkeley:"Spirito attivo conosciuto mediante nozione, non idea.",later:"Hume parla di fascio di percezioni; Kant dell’unità trascendentale."},
    {topic:"Causalità",locke:"Potere nelle sostanze, benché oscuro.",berkeley:"Solo gli spiriti sono cause; la natura mostra regolarità-segni.",later:"Hume critica la connessione necessaria; Kant la tratta come categoria."},
    {topic:"Idealismo",locke:"Realismo rappresentativo discusso.",berkeley:"Idealismo e immaterialismo.",later:"Kant rifiuta l’equivalenza fra idealismo trascendentale e berkeleismo."}
  ],
  quiz:[
    {q:"Qual è il bersaglio principale dell’immaterialismo?",options:["Gli oggetti quotidiani","La sostanza materiale indipendente dalla mente","La regolarità scientifica"],correct:1,why:["Berkeley conserva pietre, alberi e corpi come collezioni di idee.","Esatto: contesta il supporto impercepibile posto dietro le qualità.","Le regolarità restano il compito della scienza."],module:"materia"},
    {q:"Perché la distanza non è immediatamente vista?",options:["Non possiede una grandezza visiva propria e viene suggerita da segni","L’occhio calcola male","La distanza è un’idea innata"],correct:0,why:["Esatto: l’esperienza collega idee visive e tattili.","Berkeley rifiuta proprio la spiegazione geometrica tacita.","La sua teoria è empirica, non innatista."],module:"visione"},
    {q:"Come spiega Berkeley la generalità?",options:["Con un’immagine senza qualità","Con l’uso generale di idee particolari","Con una sostanza universale"],correct:1,why:["Un’immagine completamente indeterminata è il bersaglio della critica.","Esatto: un particolare può rappresentare molti casi.","La sostanza universale non svolge questa funzione."],module:"astrazione"},
    {q:"Che rapporto c’è fra qualità primarie e secondarie?",options:["Le prime sono percepite da Dio, le seconde dagli uomini","Le prime sono sempre vere","Sono inseparabili nella percezione e entrambe relative al percipiente"],correct:2,why:["La distinzione non riguarda due spettatori.","Prospettiva e moto mettono sotto pressione questa pretesa.","Esatto: è la strategia di Berkeley contro la distinzione lockiana."],module:"qualita"},
    {q:"Esse est percipi si applica nello stesso modo agli spiriti?",options:["Sì","No: gli spiriti esistono come percepienti e volenti","Solo agli spiriti finiti"],correct:1,why:["Confonderebbe passivo e attivo.","Esatto: per le idee percipi, per gli spiriti percipere.","La distinzione vale anche parlando dello spirito infinito."],module:"esse"},
    {q:"Perché le idee non possono essere cause?",options:["Sono passive","Sono tutte immaginarie","Sono materiali"],correct:0,why:["Esatto: in esse non è percepito potere attivo.","Le idee del senso sono reali nel sistema.","Berkeley nega che siano materiali."],module:"spiriti"},
    {q:"Da che cosa Berkeley inferisce l’esistenza di Dio?",options:["Dal consenso politico","Dall’ordine involontario delle idee sensibili","Da un esperimento ottico isolato"],correct:1,why:["Il consenso non fonda l’argomento.","Esatto: idee passive e involontarie richiedono un altro spirito.","La teoria della visione non basta da sola."],module:"dio"},
    {q:"Che cosa distingue il mondo reale dal sogno?",options:["La presenza di materia percepita","Ordine, coerenza, vividezza e involontarietà","L’assenza totale di idee nel sogno"],correct:1,why:["La materia non è percepita nel sistema.","Esatto: sono i criteri della rerum natura.","Anche il sogno contiene idee."],module:"obiezioni"},
    {q:"Nel caso del remo piegato, dove può sorgere l’errore?",options:["Nell’idea visiva presente","Nell’inferenza su future percezioni","Nell’acqua che non esiste"],correct:1,why:["L’idea presente è quella che appare.","Esatto: la previsione può essere smentita dall’esperienza.","Berkeley non nega l’acqua ordinaria."],module:"obiezioni"},
    {q:"Qual è il valore filosofico dei Dialoghi?",options:["Eliminano le obiezioni","Mettono in scena la progressione fra obiezione e risposta","Raccontano la biografia di Berkeley"],correct:1,why:["Le obiezioni restano centrali.","Esatto: Hylas e Philonous incarnano la dialettica.","Non sono una biografia."],module:"opere"},
    {q:"Quale rapporto fra vita e filosofia è corretto?",options:["La biografia sostituisce l’analisi","Le responsabilità storiche vanno documentate senza dedurre automaticamente la metafisica","Il pensiero cancella le azioni"],correct:1,why:["La validità di un argomento richiede analisi.","Esatto: i piani sono connessi ma distinti.","La grandezza teorica non assolve la storia."],module:"vita"},
    {q:"Quale affermazione sull’eredità è corretta?",options:["Berkeley anticipa la quantistica","Hume e Kant trasformano o contestano problemi resi urgenti da Berkeley","Kant ripete esse est percipi"],correct:1,why:["L’osservazione quantistica non equivale a coscienza.","Esatto: influenza non significa identità.","Kant distingue esplicitamente il proprio idealismo."],module:"eredita"}
  ],
  academicSources:[
    {institution:"Stanford University",title:"George Berkeley — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/berkeley/",supports:"Argomenti contro la materia, ontologia, Dio, obiezioni, visione ed eredità."},
    {institution:"University of Tennessee at Martin",title:"George Berkeley — Internet Encyclopedia of Philosophy",url:"https://iep.utm.edu/george-berkeley-british-empiricist/",supports:"Biografia, teoria della visione, astrazione, idealismo, immaterialismo e nozioni."},
    {institution:"University of Tennessee at Martin",title:"British Empiricism — Internet Encyclopedia of Philosophy",url:"https://iep.utm.edu/british-empiricism/",supports:"Confronto fra Locke, Berkeley e Hume; formula percipi aut percipere."},
    {institution:"Trinity College Dublin",title:"Working Paper on Berkeley’s Legacies at Trinity",url:"https://www.tcd.ie/media/tcd/seniordean/pdfs/berkeleyTLRWGworkingpaper.pdf",supports:"Incarichi al Trinity, progetto americano, persone schiavizzate e memoria istituzionale."},
    {institution:"Trinity College Dublin",title:"Denaming the Berkeley Library",url:"https://www.tcd.ie/library/about/denaming.php",supports:"Decisione del 2023, motivazioni e continuità dello studio filosofico."},
    {institution:"Yale University",title:"Yale and Slavery: A History — Berkeley Divinity School",url:"https://berkeleydivinity.yale.edu/posts/2024-02-29-yale-and-slavery-a-history",supports:"Whitehall, progetto missionario, schiavitù e beneficenza verso Yale."}
  ]
};
