window.SOCRATE_DATA={
 modules:[
  {id:'mondo',n:'01',title:'Il mondo di Socrate',subtitle:'Atene, guerra e crisi della polis',question:'Che cosa accade alla verità quando una città perde le proprie certezze?',status:'Ricostruzione storica',body:['Socrate vive l’apogeo e la crisi di Atene: l’età di Pericle, la guerra del Peloponneso, la sconfitta del 404, il governo dei Trenta e la restaurazione democratica del 403 a.C. Il processo avviene quattro anni dopo, nel 399.','La sofistica risponde alle esigenze della polis democratica: educazione, linguaggio, capacità di argomentare. Non esiste però un’unica dottrina sofistica. Protagora, Gorgia, Prodico e Ippia non vanno fusi in una caricatura collettiva.'],essentials:['Restaurazione democratica: 403 a.C.','Processo e morte: 399 a.C.','La crisi politica non spiega da sola il processo.'],terms:['polis','paideia','doxa'],check:{q:'Quando fu restaurata la democrazia dopo i Trenta?',a:['399 a.C.','403 a.C.','423 a.C.'],correct:1}},
  {id:'questione',n:'02',title:'Il problema socratico',subtitle:'Quattro fonti, nessun ritratto neutrale',question:'Come ricostruire un filosofo che non ha lasciato scritti?',status:'Problema aperto',body:['Aristofane offre una caricatura comica contemporanea; Senofonte difende un maestro pratico e pio; Platone costruisce il ritratto filosoficamente più potente; Aristotele, nato dopo la morte di Socrate, ne isola alcuni contributi metodologici.','La distinzione rigida tra dialoghi “socratici” fedeli e dialoghi “platonici” è utile per orientarsi, ma resta un’ipotesi di lavoro, non un registratore storico.'],essentials:['Nessuna fonte è una trascrizione neutrale.','Il confronto fra fonti conta più della ricerca di una frase autentica.','Il Socrate storico resta in parte irraggiungibile.'],terms:['questione socratica','testimonianza','logos sokratikos'],check:{q:'Quale fonte conobbe Socrate soprattutto attraverso Platone?',a:['Aristofane','Senofonte','Aristotele'],correct:2}},
  {id:'frattura',n:'03',title:'La frattura',subtitle:'Dal sapere dichiarato al sapere esaminato',question:'Come puoi affermare di sapere ciò che dici di sapere?',status:'Interpretazione plausibile',body:['La formula “dalla natura all’uomo” coglie una tendenza, ma non un taglio netto: interessi umani e politici esistevano già, mentre Socrate non è semplicemente estraneo a ogni discorso sulla natura.','La frattura decisiva è pratica: una tesi non vale per il prestigio di chi la pronuncia. Deve attraversare domande, esempi, conseguenze e possibili contraddizioni.'],essentials:['La svolta non è assoluta né improvvisa.','L’esame riguarda soprattutto concetti etici.','Il punto di partenza è il limite del proprio sapere.'],terms:['anthropos','physis','esame'],check:{q:'Qual è la domanda più radicalmente socratica?',a:['Chi lo ha detto?','Come sai di saperlo?','Quanto è antico?'],correct:1}},
  {id:'metodo',n:'04',title:'Il metodo',subtitle:'Dialogo, élenchos e aporia',question:'Una contraddizione distrugge il dialogo o lo rende finalmente serio?',status:'Testimonianza platonica',body:['Nei dialoghi giovanili di Platone, Socrate chiede spesso “che cos’è?”, ottiene una definizione e ne verifica la coerenza con altre convinzioni dell’interlocutore. L’élenchos non è un algoritmo infallibile: mette alla prova un insieme di credenze.','Ironia, confutazione, aporia e maieutica non formano una scala fissa attestata in ogni dialogo. La celebre immagine della levatrice è sviluppata soprattutto nel Teeteto, opera platonica tarda: attribuirla senza cautele al Socrate storico è improprio.'],essentials:['Élenchos significa esame/confutazione.','Aporia è difficoltà, non sconfitta.','La maieutica è soprattutto una costruzione del Teeteto platonico.'],terms:['ironia','élenchos','aporia','maieutica'],check:{q:'L’aporia è…',a:['un errore da nascondere','una conclusione definitiva','un’impasse da cui riprendere la ricerca'],correct:2}},
  {id:'uomo',n:'05',title:'L’uomo',subtitle:'Psyché e vita esaminata',question:'Che cosa significa prendersi cura di sé?',status:'Testimonianza platonica',body:['Nell’Apologia platonica Socrate esorta gli Ateniesi a non anteporre ricchezza, fama e corpo alla cura della psyché. “Anima” qui non va subito letta con categorie cristiane o cartesiane: indica il centro morale e razionale della persona.','Una vita esaminata collega ragionamento e condotta. Il dialogo non serve a esibire intelligenza, ma a verificare che ciò che si professa e ciò che si vive non si contraddicano.'],essentials:['Psyché: soggetto della cura morale.','Conoscere sé stessi significa riconoscere limiti e responsabilità.','Il pensiero deve trasformare la vita.'],terms:['psyché','epimeleia','vita esaminata'],check:{q:'La cura socratica riguarda anzitutto…',a:['la reputazione','la psyché','la vittoria retorica'],correct:1}},
  {id:'etica',n:'06',title:'L’etica',subtitle:'Virtù, sapere e felicità',question:'Possiamo fare volontariamente ciò che sappiamo essere male?',status:'Ricostruzione discussa',body:['Nei primi dialoghi platonici ricorre l’idea che chi agisce male sbagli sul bene reale: desidera qualcosa che gli appare buono, ma ignora ciò che davvero lo renderebbe migliore. Da qui la formula scolastica “virtù = sapere”.','È un intellettualismo esigente e problematico: sembra sottovalutare debolezza della volontà, passioni e autoinganno. Anche per questo Platone svilupperà poi una psicologia più complessa.'],essentials:['Areté è eccellenza della persona, non moralismo.','Il male dipende da un errore sul bene.','Eudaimonia è fioritura/vita riuscita, non piacere momentaneo.'],terms:['areté','bene','eudaimonia','intellettualismo etico'],check:{q:'Per l’intellettualismo socratico, il male deriva anzitutto da…',a:['ignoranza del bene','destino biologico','disobbedienza politica'],correct:0}},
  {id:'daimonion',n:'07',title:'Il daimonion',subtitle:'Un segno divino che trattiene',question:'Come può una missione razionale convivere con un segno divino?',status:'Testimonianze divergenti',body:['Nell’Apologia di Platone il daimonion è un segno o una voce che interviene soprattutto in modo negativo: trattiene Socrate da certe azioni, non gli consegna una dottrina. Senofonte ne offre una descrizione in parte più positiva e divinatoria.','Non è corretto identificarlo senza residui con la coscienza moderna, una diagnosi clinica o un oracolo privato. È un fenomeno religioso antico raccontato da fonti con intenti diversi.'],essentials:['Platone: segno soprattutto apotropaico/proibitivo.','Senofonte: quadro non identico.','Il daimonion complica, non cancella, la razionalità socratica.'],terms:['daimonion','segno','empietà'],check:{q:'Nel racconto dell’Apologia, il segno soprattutto…',a:['ordina una dottrina','trattiene da un’azione','predice il futuro politico'],correct:1}},
  {id:'sofisti',n:'08',title:'Socrate e i sofisti',subtitle:'Vicinanze reali, differenze non assolute',question:'Cercare la verità e persuadere sono davvero attività opposte?',status:'Comparazione critica',body:['Socrate e i sofisti condividono lo spazio della polis, l’attenzione per linguaggio ed educazione e la discussione sull’areté. Agli occhi di molti Ateniesi, Socrate poteva apparire uno di loro.','Pagamento, forma dell’insegnamento e finalità dell’argomentazione segnano differenze importanti, ma non bastano a dividere “buoni” e “cattivi”. Non tutti i sofisti sono relativisti, né ogni discorso socratico è breve o privo di strategia retorica.'],essentials:['La sofistica è plurale.','Socrate non si presenta come maestro professionale.','La caricatura nasce anche dalla polemica platonica.'],terms:['sofista','retorica','paideia'],check:{q:'Quale affermazione è più rigorosa?',a:['Tutti i sofisti negano la verità','Socrate non ha nulla in comune con loro','Condividono problemi, ma differiscono spesso per scopi e pratica'],correct:2}},
  {id:'atene',n:'09',title:'Socrate e Atene',subtitle:'Democrazia, competenza e disobbedienza',question:'La maggioranza può rendere giusta una decisione ingiusta?',status:'Dati con interpretazioni',body:['Socrate critica decisioni democratiche e diffida del sapere politico non competente; ma si oppone anche agli abusi oligarchici. Nel 406 rifiuta la procedura illegale contro gli strateghi delle Arginuse; sotto i Trenta non esegue l’ordine di arrestare Leone di Salamina.','I legami con Alcibiade e Crizia pesarono probabilmente sulla percezione pubblica, ma trasformare il processo in pura vendetta politica ignora le accuse formali e l’amnistia del 403.'],essentials:['Critica della maggioranza non equivale automaticamente a programma oligarchico.','Socrate resiste a ingiustizie di regimi diversi.','Le cause profonde del processo restano discusse.'],terms:['democrazia','competenza','nomos'],check:{q:'A quale abuso Socrate si oppose sotto i Trenta?',a:['all’arresto di Leone','alla spedizione di Delio','alla restaurazione democratica'],correct:0}},
  {id:'processo',n:'10',title:'Processo e morte',subtitle:'Accusa formale, contesto, costruzione letteraria',question:'Fu condannato per religione, politica o per il modo in cui visse?',status:'Problema aperto',body:['Nel 399 Meleto, Anito e Licone accusano Socrate di non riconoscere gli dèi della città, introdurre nuove realtà divine e corrompere i giovani. Queste sono le accuse formali. Il risentimento politico e culturale è un contesto plausibile, non un capo d’accusa occulto dimostrato.','Apologia, Critone e Fedone costruiscono tre scene filosofiche: difesa, rifiuto della fuga, morte. Sono fonti indispensabili e insieme opere di Platone. Nel Critone non si dice semplicemente “obbedisci sempre”: la tesi decisiva è non rispondere all’ingiustizia con altra ingiustizia.'],essentials:['Accuse formali e motivazioni ricostruite vanno distinte.','La morte per cicuta appartiene al racconto delle fonti antiche.','Dal Fedone il Socrate platonico è particolarmente difficile da separare dallo storico.'],terms:['asebeia','Critone','Fedone'],check:{q:'Quale NON era un’accusa formale?',a:['corruzione dei giovani','empietà','ostilità alla democrazia'],correct:2}},
  {id:'eredita',n:'11',title:'L’eredità',subtitle:'Molti Socrate dopo Socrate',question:'Perché un uomo senza libri genera intere scuole?',status:'Dato storico e ricezioni',body:['Platone non è l’unico erede. Antistene, Aristippo, Euclide di Megara e altri sviluppano stili diversi di vita e ricerca: da qui le tradizioni cinica, cirenaica e megarica, pur con genealogie non sempre lineari.','L’eredità più profonda non è una dottrina chiusa: è l’idea che una vita umana debba rendere ragione di sé attraverso il dialogo e accettare il rischio della confutazione.'],essentials:['Esistono più scuole socratiche.','Platone amplifica e trasforma il maestro.','Il dialogo diventa un modello di filosofia vissuta.'],terms:['cinici','cirenaici','megarici'],check:{q:'Qual è l’eredità comune più prudente da attribuire a Socrate?',a:['una metafisica completa','la pratica della vita esaminata','la teoria delle Idee'],correct:1}}
 ],
 locations:[
  {id:'agora',n:1,title:'Agorà',subtitle:'Dialogo · ironia · domande',question:'Che cos’è la giustizia?',tag:'Testimonianza convergente',text:'Le fonti collocano Socrate negli spazi pubblici, dove interroga cittadini e visitatori. Il dialogo comincia da una definizione concreta e ne misura le conseguenze. Non è una lezione frontale: l’interlocutore è responsabile delle proprie risposte.'},
  {id:'ginnasio',n:2,title:'Ginnasio',subtitle:'Educazione · giovani · sofisti',question:'Si può insegnare la virtù?',tag:'Questione discussa',text:'Socrate frequenta giovani e adulti ma nega, nell’Apologia platonica, di essere un maestro a pagamento. Il contrasto con i sofisti è reale e insieme polemico: condividono molti problemi della paideia democratica.'},
  {id:'acropoli',n:3,title:'Acropoli',subtitle:'Religione · daimonion · empietà',question:'Un segno divino rende irrazionale una scelta?',tag:'Testimonianze divergenti',text:'Il Socrate delle fonti non è semplicemente ateo. La missione legata a Delfi e il daimonion mostrano un rapporto personale e problematico con il divino; proprio questo rapporto può aver alimentato l’accusa di introdurre nuove realtà divine.'},
  {id:'pnice',n:4,title:'Pnice',subtitle:'Politica · democrazia · competenza',question:'La maggioranza può rendere giusta un’ingiustizia?',tag:'Dati con interpretazioni',text:'Nel 406 Socrate si oppose alla procedura collettiva e illegale contro gli strateghi delle Arginuse. Sotto i Trenta rifiutò di arrestare Leone. Non si lascia ridurre né a democratico esemplare né a nemico della democrazia.'},
  {id:'tribunale',n:5,title:'Tribunale',subtitle:'Il processo del 399 a.C.',question:'Giudichi un reato o un modo di vivere?',tag:'Accuse certe, cause discusse',text:'Meleto, Anito e Licone sostengono le accuse di empietà e corruzione dei giovani. Il clima politico successivo alla guerra aiuta a capire il processo, ma non autorizza a sostituire le accuse documentate con una causa segreta presentata come certa.'},
  {id:'carcere',n:6,title:'Carcere',subtitle:'Critone · leggi · coerenza',question:'È giusto fuggire da una sentenza ingiusta?',tag:'Testimonianza platonica',text:'Nel Critone le Leggi personificate sostengono che la fuga danneggerebbe l’ordine giuridico e violerebbe un accordo. Ma l’argomento nasce dopo un principio più radicale: non si deve mai compiere ingiustizia, neppure in risposta a un torto.'},
  {id:'ultimo',n:7,title:'Ultimo Socrate',subtitle:'Morte · Fedone · eredità',question:'La coerenza vale più della vita?',tag:'Socrate platonico',text:'Il Fedone narra l’ultimo giorno e fa della morte il banco di prova della filosofia. Da questo punto è particolarmente difficile separare il Socrate storico dal Socrate costruito filosoficamente da Platone.'}
 ],
 campaigns:[
  {id:'potidea',title:'Potidea',date:'432–429 a.C. circa',text:'Nel Simposio platonico Alcibiade ricorda la resistenza di Socrate durante l’assedio e il suo comportamento nel salvarlo. La testimonianza è letteraria, ma il servizio militare è generalmente accettato.'},
  {id:'delio',title:'Delio',date:'424 a.C.',text:'Nel Lachete e nel Simposio Platone rappresenta Socrate saldo durante la ritirata ateniese. Il coraggio appare come dominio di sé, non come assenza di paura.'},
  {id:'anfipoli',title:'Anfipoli',date:'422 a.C.',text:'La partecipazione è ricordata nell’Apologia platonica insieme a Potidea e Delio. I dettagli della sua condotta sono molto meno ricchi: non colmare il silenzio delle fonti con leggende.'}
 ],
 glossary:[
  ['aporia','Impasse argomentativa: le risposte disponibili non reggono ancora all’esame.'],['areté','Eccellenza o virtù: capacità di realizzare bene la propria umanità.'],['daimonion','Il “segno divino” attribuito a Socrate; in Platone soprattutto trattiene, in Senofonte il quadro è diverso.'],['dialegesthai','Dialogare, ragionare insieme attraverso domande e risposte.'],['doxa','Opinione o credenza, da sottoporre a esame.'],['élenchos','Esame/confutazione che mostra l’incoerenza tra una tesi e altre convinzioni ammesse.'],['epimeleia','Cura, sollecitudine; nella formula “cura dell’anima” indica un esercizio morale.'],['eudaimonia','Vita riuscita o fiorente; non semplice piacere momentaneo.'],['ironia','Distanza fra ciò che Socrate sembra concedere e l’esame che prepara; non semplice sarcasmo.'],['logos','Discorso, ragione, argomento: parola che deve rendere conto di sé.'],['maieutica','Arte della levatrice. Immagine elaborata nel Teeteto platonico; la sua storicità socratica è discussa.'],['nomos','Legge, norma o costume condiviso della polis.'],['paideia','Formazione culturale, politica e morale del cittadino.'],['psyché','Il sé morale e razionale di cui occorre avere cura; “anima” senza sovrapporre subito categorie posteriori.'],['sofista','Esperto e spesso maestro itinerante di educazione e parola pubblica; il gruppo è internamente plurale.'],['techné','Sapere pratico competente, capace di spiegare il proprio metodo e il proprio fine.']
 ],
 timeline:[
  ['470/469 a.C. circa','Nascita di Socrate','Data tradizionale, non perfettamente certa.'],['461–429 a.C.','Età di Pericle','Crescita della democrazia e dell’impero ateniese.'],['432–429 a.C. circa','Potidea','Socrate presta servizio come oplita.'],['431–404 a.C.','Guerra del Peloponneso','Il lungo conflitto trasforma e logora Atene.'],['424 a.C.','Delio','Ritirata ateniese; le fonti celebrano la fermezza di Socrate.'],['422 a.C.','Anfipoli','Ultima delle tre campagne ricordate nell’Apologia.'],['406 a.C.','Arginuse','Socrate si oppone alla procedura illegale contro gli strateghi.'],['404/403 a.C.','Trenta Tiranni','Socrate rifiuta l’ordine di arrestare Leone di Salamina.'],['403 a.C.','Restaurazione democratica','Democrazia e amnistia dopo la guerra civile.'],['399 a.C.','Processo e morte','Condanna per empietà e corruzione dei giovani.']
 ],
 sources:[
  {name:'Aristofane',work:'Nuvole (423 a.C.)',kind:'Testimonianza contemporanea e comica',portrait:'Socrate naturalista e sofista sospeso fra le nuvole.',value:'Mostra la percezione pubblica e gli stereotipi già attivi.',limit:'La caricatura teatrale non è una biografia né un trattato.'},
  {name:'Senofonte',work:'Memorabili, Apologia, Simposio',kind:'Testimonianza apologetica',portrait:'Maestro pratico, pio, utile agli amici e alla città.',value:'Conferma temi etici, vita pubblica e segno divino.',limit:'Difende Socrate e tende a normalizzarlo.'},
  {name:'Platone',work:'Dialoghi e Apologia',kind:'Costruzione filosofico-letteraria',portrait:'Interrogatore, tafano, modello della vita filosofica.',value:'Fonte più ricca per metodo, etica, processo e morte.',limit:'Il personaggio diventa anche veicolo del pensiero platonico.'},
  {name:'Aristotele',work:'Metafisica e altre opere',kind:'Ricostruzione successiva',portrait:'Ricercatore di definizioni universali e ragionamenti induttivi.',value:'Distingue Socrate dalla teoria platonica delle Idee.',limit:'Non lo conobbe e lo legge attraverso proprie categorie.'}
 ]
};
